query CommitteeTeamQuery($committeeId: ID!) @blocking {
	findFirstCommittee(where: { id: $committeeId }) {
		id
		abbreviation
		name
		stateOfDebate
		status
		statusHeadline
		statusUntil
		totalPresent
		simpleMajority
		twoThirdsMajority
		paperSupportThreshold
		whiteboardContent
		activeAgendaItem {
			id
			title
		}
		agendaItems {
			id
			title
		}
		members {
			id
			present
			representation {
				id
				type
				name
				regionalGroup
				alpha2Code
				alpha3Code
				faIcon
			}
		}
	}
}
