query CommitteeTeamQuery($committeeId: ID!) @blocking {
	findFirstCommittee(where: { id: $committeeId }) {
		id
		abbreviation
		name
		stateOfDebate
		status
		statusHeadline
		statusUntil
		totalPresent
		simpleMajority
		twoThirdsMajority
		paperSupportThreshold
		activeAgendaItem {
			id
			title
		}
		agendaItems {
			id
			title
		}
		whiteboardContent
	}
}
