query CommitteeTeamQuery($committeeId: ID!) @blocking {
  findFirstCommittee(where: { id: $committeeId }) {
    id
    abbreviation
    name
    stateOfDebate
    status
    statusHeadline
    statusUntil
    totalPresent
    simpleMajority
    twoThirdsMajority
    paperSupportThreshold
    whiteboardContent
    lastResolutionAdoptionDate
    activeAgendaItem {
      id
      title
      speakersList {
        id
        type
        isClosed
        speakingTime
        startTimestamp
        timeLeft
        speakers {
          id
          position
          overwriteName
          committeeMember {
            id
            representation {
              id
              type
              name
              regionalGroup
              alpha2Code
              alpha3Code
              faIcon
            }
            present
          }
          conferenceMember {
            id
            representation {
              id
              type
              name
              regionalGroup
              alpha2Code
              alpha3Code
              faIcon
            }
          }
        }
      }
    }
    agendaItems {
      id
      title
    }
    members {
      id
      present
      representation {
        id
        type
        name
        regionalGroup
        alpha2Code
        alpha3Code
        faIcon
      }
    }
    conference {
      uniqueConferenceMembers {
        id
        representation {
          id
          type
          name
          alpha2Code
          alpha3Code
          faIcon
        }
      }
    }
  }
}
