import type { ResolutionEditorLabels } from '@deutschemodelunitednations/munify-resolution-editor/i18n';
import * as m from '$lib/paraglide/messages';

export function getResolutionLabels(): ResolutionEditorLabels {
	return {
		resolutionEditor: m.resolutionEditor(),
		resolution: m.resolution(),
		resolutionPreview: m.resolutionPreview(),
		resolutionShowPreview: m.resolutionShowPreview(),
		resolutionHidePreview: m.resolutionHidePreview(),
		resolutionCommittee: m.resolutionCommittee(),
		resolutionPreambleClauses: m.resolutionPreambleClauses(),
		resolutionOperativeClauses: m.resolutionOperativeClauses(),
		resolutionSubClauses: m.resolutionSubClauses(),
		resolutionAddClause: m.resolutionAddClause(),
		resolutionAddFirstClause: m.resolutionAddFirstClause(),
		resolutionDeleteClause: m.resolutionDeleteClause(),
		resolutionDeleteBlock: m.resolutionDeleteBlock(),
		resolutionMoveUp: m.resolutionMoveUp(),
		resolutionMoveDown: m.resolutionMoveDown(),
		resolutionIndent: m.resolutionIndent(),
		resolutionOutdent: m.resolutionOutdent(),
		resolutionAddSubClause: m.resolutionAddSubClause(),
		resolutionAddSibling: m.resolutionAddSibling(),
		resolutionAddNested: m.resolutionAddNested(),
		resolutionAddContinuation: m.resolutionAddContinuation(),
		resolutionPreamblePlaceholder: m.resolutionPreamblePlaceholder(),
		resolutionOperativePlaceholder: m.resolutionOperativePlaceholder(),
		resolutionSubClausePlaceholder: m.resolutionSubClausePlaceholder(),
		resolutionContinuationPlaceholder: m.resolutionContinuationPlaceholder(),
		resolutionNoPreambleClauses: m.resolutionNoPreambleClauses(),
		resolutionNoOperativeClauses: m.resolutionNoOperativeClauses(),
		resolutionNoClausesYet: m.resolutionNoClausesYet(),
		resolutionUnknownPhrase: m.resolutionUnknownPhrase(),
		phraseLookup: m.phraseLookup(),
		phraseLookupTitle: m.phraseLookupTitle(),
		phraseLookupSearch: m.phraseLookupSearch(),
		phraseLookupDisclaimer: m.phraseLookupDisclaimer(),
		phraseLookupNoResults: m.phraseLookupNoResults(),
		phraseCopied: m.phraseCopied(),
		copyFailed: m.copyFailed(),
		resolutionImport: m.resolutionImport(),
		resolutionImportPreamble: m.resolutionImportPreamble(),
		resolutionImportOperative: m.resolutionImportOperative(),
		resolutionImportButton: m.resolutionImportButton({ count: '{count}' }),
		resolutionImportPreview: m.resolutionImportPreview({ count: '{count}' }),
		resolutionImportHintPreamble: m.resolutionImportHintPreamble(),
		resolutionImportHintOperative: m.resolutionImportHintOperative(),
		resolutionImportTipsTitle: m.resolutionImportTipsTitle(),
		resolutionImportTipsPreamble1: m.resolutionImportTipsPreamble1(),
		resolutionImportTipsPreamble2: m.resolutionImportTipsPreamble2(),
		resolutionImportTipsPreamble3: m.resolutionImportTipsPreamble3(),
		resolutionImportTipsOperative1: m.resolutionImportTipsOperative1(),
		resolutionImportTipsOperative2: m.resolutionImportTipsOperative2(),
		resolutionImportTipsOperative3: m.resolutionImportTipsOperative3(),
		resolutionImportTipsOperative4: m.resolutionImportTipsOperative4(),
		resolutionImportLLMTitle: m.resolutionImportLLMTitle(),
		resolutionImportLLMInstructions: m.resolutionImportLLMInstructions(),
		resolutionImportLLMCopyPrompt: m.resolutionImportLLMCopyPrompt(),
		resolutionImportLLMCopied: m.resolutionImportLLMCopied(),
		resolutionImportLLMPromptPreamble: m.resolutionImportLLMPromptPreamble(),
		resolutionImportLLMPromptOperative: m.resolutionImportLLMPromptOperative(),
		resolutionExport: m.resolutionExport(),
		resolutionImportResolution: m.resolutionImportResolution(),
		resolutionImportResolutionHint: m.resolutionImportResolutionHint(),
		resolutionImportResolutionFile: m.resolutionImportResolutionFile(),
		resolutionImportResolutionButton: m.resolutionImportResolutionButton(),
		resolutionImportResolutionInvalid: m.resolutionImportResolutionInvalid(),
		resolutionImportResolutionWarnings: m.resolutionImportResolutionWarnings(),
		resolutionImportResolutionEmpty: m.resolutionImportResolutionEmpty(),
		resolutionSponsoringDelegations: m.resolutionSponsoringDelegations(),
		resolutionAuthoringDelegation: m.resolutionAuthoringDelegation(),
		resolutionDisclaimer: m.resolutionDisclaimer({ conferenceName: '{conferenceName}' }),
		amendmentProposed: m.amendmentProposed(),
		amendmentAdd: m.amendmentAdd(),
		amendmentDelete: m.amendmentDelete(),
		amendmentAlterText: m.amendmentAlterText(),
		amendmentAlterPosition: m.amendmentAlterPosition(),
		amendmentRejectedClause: m.amendmentRejectedClause(),
		operativeParagraph: m.operativeParagraph(),
		operativeParagraphShowDiff: m.operativeParagraphShowDiff(),
		operativeParagraphHideDiff: m.operativeParagraphHideDiff(),
		operativeParagraphInvalidMarkup: m.operativeParagraphInvalidMarkup(),
		operativeParagraphEmpty: m.operativeParagraphEmpty(),
		operativeParagraphOldVersion: m.operativeParagraphOldVersion(),
		operativeParagraphNewVersion: m.operativeParagraphNewVersion(),
		close: m.close(),
		cancel: m.cancel(),
		copy: m.copy()
	};
}
