"""
Indicates exactly one field must be supplied and this field must not be `null`.
"""
directive @oneOf on INPUT_OBJECT

type Committee {
  abbreviation: String!
  allowDelegationsToAddThemselvesToSpeakersList: Boolean!
  conference(where: ConferenceWhereInputArgument): Conference!
  conferenceId: ID!
  createdAt: DateTime!
  id: ID!
  name: String!
  showWhiteboard: Boolean!
  stateOfDebate: String
  status: CommitteeStatusEnum!
  statusHeadline: String
  statusUntil: DateTime!
  updatedAt: DateTime!
  whiteboardContent: String
}

type CommitteeMember {
  committee(where: CommitteeWhereInputArgument): Committee!
  committeeId: ID!
  conferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  conferenceMemberId: ID!
  createdAt: DateTime!
  id: ID!
  present: Boolean!
  role: String!
  updatedAt: DateTime!
}

input CommitteeMemberWhereInputArgument {
  committeeId: ID
  conferenceMemberId: ID
  createdAt: DateTime
  id: ID
  present: Boolean
  role: String
  updatedAt: DateTime
}

enum CommitteeStatusEnum {
  formal
  informal
  pause
  suspension
}

input CommitteeWhereInputArgument {
  abbreviation: String
  allowDelegationsToAddThemselvesToSpeakersList: Boolean
  conferenceId: ID
  createdAt: DateTime
  id: ID
  name: String
  showWhiteboard: Boolean
  stateOfDebate: String
  status: CommitteeStatusEnum
  statusHeadline: String
  statusUntil: DateTime
  updatedAt: DateTime
  whiteboardContent: String
}

type Conference {
  committees(where: CommitteeWhereInputArgument): [Committee!]!
  createdAt: DateTime!
  enabled: Boolean!
  id: ID!
  members(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  pressWebsite: String
  updatedAt: DateTime!
}

type ConferenceMember {
  conference(where: ConferenceWhereInputArgument): Conference!
  conferenceId: ID!
  createdAt: DateTime!
  id: ID!
  role: RoleEnum!
  updatedAt: DateTime!
  user(where: UserWhereInputArgument): User!
  userId: String!
}

input ConferenceMemberWhereInputArgument {
  conferenceId: ID
  createdAt: DateTime
  id: ID
  role: RoleEnum
  updatedAt: DateTime
  userId: String
}

input ConferenceWhereInputArgument {
  createdAt: DateTime
  enabled: Boolean
  id: ID
  pressWebsite: String
  updatedAt: DateTime
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTime

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  dummy: User
}

type Query {
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyCommittee(where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyUser(where: UserWhereInputArgument): [User!]!
}

enum RoleEnum {
  admin
  participant
  spectator
  team
}

type Subscription {
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyCommittee(where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyUser(where: UserWhereInputArgument): [User!]!
}

type User {
  conferenceMemberships(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  createdAt: DateTime!
  email: String!
  familyName: String!
  givenName: String!
  id: String!
  locale: String!
  preferredUsername: String!
  updatedAt: DateTime!
}

input UserWhereInputArgument {
  createdAt: DateTime
  email: String
  familyName: String
  givenName: String
  id: String
  locale: String
  preferredUsername: String
  updatedAt: DateTime
}
