type AgendaItem {
  committee(where: CommitteeWhereInputArgument): Committee
  committeeId: ID!
  createdAt: DateTime!
  id: ID!
  isActive: Boolean
  resolutionPapers(limit: Int, offset: Int, where: ResolutionPaperWhereInputArgument): [ResolutionPaper!]!
  speakersList(limit: Int, offset: Int, where: SpeakersListWhereInputArgument): [SpeakersList!]!
  title: String!
  updatedAt: DateTime
}

input AgendaItemWhereInputArgument {
  committee: CommitteeWhereInputArgument
  committeeId: ID
  createdAt: DateTime
  id: ID
  resolutionPapers: ResolutionPaperWhereInputArgument
  speakersList: SpeakersListWhereInputArgument
  title: String
  updatedAt: DateTime
}

type Amendment {
  createdAt: DateTime!
  id: ID!
  newContent: JSON
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  proposer(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  proposerCommitteeMemberId: ID!
  sponsors(limit: Int, offset: Int, where: AmendmentSponsorWhereInputArgument): [AmendmentSponsor!]!
  status: AmendmentStatusEnum!
  targetClauseId: ID
  targetOperativeIndex: Int
  targetPosition: Int
  type: AmendmentTypeEnum!
  updatedAt: DateTime
}

type AmendmentSponsor {
  amendment(where: AmendmentWhereInputArgument): Amendment!
  amendmentId: ID!
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  committeeMemberId: ID!
  createdAt: DateTime!
  id: ID!
  updatedAt: DateTime
}

input AmendmentSponsorWhereInputArgument {
  amendment: AmendmentWhereInputArgument
  amendmentId: ID
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  createdAt: DateTime
  id: ID
  updatedAt: DateTime
}

enum AmendmentStatusEnum {
  ACCEPTED
  CONSENSUS_ADOPTED
  PENDING
  REJECTED
  SUBMITTED
  WITHDRAWN
}

enum AmendmentTypeEnum {
  ADD
  ALTER_POSITION
  ALTER_TEXT
  DELETE
}

input AmendmentWhereInputArgument {
  createdAt: DateTime
  id: ID
  newContent: JSON
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  proposer: CommitteeMemberWhereInputArgument
  proposerCommitteeMemberId: ID
  sponsors: AmendmentSponsorWhereInputArgument
  status: AmendmentStatusEnum
  targetClauseId: ID
  targetOperativeIndex: Int
  targetPosition: Int
  type: AmendmentTypeEnum
  updatedAt: DateTime
}

enum CommentVisibilityEnum {
  PUBLIC
  TEAM_ONLY
}

type Committee {
  abbreviation: String!
  activeAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem
  activeAgendaItemId: ID
  activeDraftResolution(where: ResolutionPaperWhereInputArgument): ResolutionPaper
  activeDraftResolutionId: ID
  agendaItems(limit: Int, offset: Int, where: AgendaItemWhereInputArgument): [AgendaItem!]!
  allowDelegationsToAddThemselvesToSpeakersList: Boolean!
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  createdAt: DateTime!
  currentOperativeIndex: Int
  customPaperSupportThreshold: Int
  customSimpleMajority: Int
  customTwoThirdsMajority: Int
  id: ID!
  lastResolutionAdoptionDate: DateTime
  maxDraftResolutions: Int!
  members(limit: Int, offset: Int, where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  name: String!
  paperSupportThreshold: Int
  resolutionPapers(limit: Int, offset: Int, where: ResolutionPaperWhereInputArgument): [ResolutionPaper!]!
  showWhiteboard: Boolean!
  simpleMajority: Int
  stateOfDebate: String
  status: CommitteeStatusEnum!
  statusHeadline: String!
  statusUntil: DateTime!
  supportReEvaluationOpen: Boolean!
  totalPresent: Int
  twoThirdsMajority: Int
  updatedAt: DateTime
  whiteboardContent: String
}

type CommitteeMember {
  amendmentSponsors(limit: Int, offset: Int, where: AmendmentSponsorWhereInputArgument): [AmendmentSponsor!]!
  committee(where: CommitteeWhereInputArgument): Committee!
  committeeId: ID!
  createdAt: DateTime!
  createdPapers(limit: Int, offset: Int, where: ResolutionPaperWhereInputArgument): [ResolutionPaper!]!
  id: ID!
  paperSponsors(limit: Int, offset: Int, where: PaperSponsorWhereInputArgument): [PaperSponsor!]!
  presenceChangedTimestamps(limit: Int, offset: Int, where: PresenceChangedTimestampWhereInputArgument): [PresenceChangedTimestamp!]!
  present: Boolean!
  proposedAmendments(limit: Int, offset: Int, where: AmendmentWhereInputArgument): [Amendment!]!
  representation(where: RepresentationWhereInputArgument): Representation!
  representationId: ID!
  updatedAt: DateTime
  users(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
}

input CommitteeMemberWhereInputArgument {
  amendmentSponsors: AmendmentSponsorWhereInputArgument
  committee: CommitteeWhereInputArgument
  committeeId: ID
  createdAt: DateTime
  createdPapers: ResolutionPaperWhereInputArgument
  id: ID
  paperSponsors: PaperSponsorWhereInputArgument
  presenceChangedTimestamps: PresenceChangedTimestampWhereInputArgument
  present: Boolean
  proposedAmendments: AmendmentWhereInputArgument
  representation: RepresentationWhereInputArgument
  representationId: ID
  updatedAt: DateTime
  users: ConferenceUserWhereInputArgument
}

enum CommitteeStatusEnum {
  FORMAL
  INFORMAL
  MODERATED_INFORMAL
  PAUSE
  SUSPENSION
}

input CommitteeWhereInputArgument {
  abbreviation: String
  activeAgendaItem: AgendaItemWhereInputArgument
  activeAgendaItemId: ID
  activeDraftResolution: ResolutionPaperWhereInputArgument
  activeDraftResolutionId: ID
  agendaItems: AgendaItemWhereInputArgument
  allowDelegationsToAddThemselvesToSpeakersList: Boolean
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  createdAt: DateTime
  currentOperativeIndex: Int
  customPaperSupportThreshold: Int
  customSimpleMajority: Int
  customTwoThirdsMajority: Int
  id: ID
  lastResolutionAdoptionDate: DateTime
  maxDraftResolutions: Int
  members: CommitteeMemberWhereInputArgument
  name: String
  resolutionPapers: ResolutionPaperWhereInputArgument
  showWhiteboard: Boolean
  stateOfDebate: String
  status: CommitteeStatusEnum
  statusHeadline: String
  statusUntil: DateTime
  supportReEvaluationOpen: Boolean
  updatedAt: DateTime
  whiteboardContent: String
}

type Conference {
  committees(limit: Int, offset: Int, where: CommitteeWhereInputArgument): [Committee!]!
  createdAt: DateTime!
  hasModeratedCaucus: Boolean!
  id: ID!
  members(limit: Int, offset: Int, where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  pressWebsite: String
  representations(limit: Int, offset: Int, where: RepresentationWhereInputArgument): [Representation!]!
  title: String!

  """
  Returns a conference member for each existent representation. Useful to display a non duplicated list of non state actors.
  """
  uniqueConferenceMembers(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]
  updatedAt: DateTime
  users(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
}

type ConferenceMember {
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  createdAt: DateTime!
  id: ID!
  representation(where: RepresentationWhereInputArgument): Representation!
  representationId: ID!
  speakerOnList(limit: Int, offset: Int, where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  updatedAt: DateTime
  users(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
}

input ConferenceMemberWhereInputArgument {
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  createdAt: DateTime
  id: ID
  representation: RepresentationWhereInputArgument
  representationId: ID
  speakerOnList: SpeakerOnListWhereInputArgument
  updatedAt: DateTime
  users: ConferenceUserWhereInputArgument
}

type ConferenceUser {
  clauseLocks(limit: Int, offset: Int, where: PaperClauseLockWhereInputArgument): [PaperClauseLock!]!
  comments(limit: Int, offset: Int, where: ResolutionCommentWhereInputArgument): [ResolutionComment!]!
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember
  committeeMemberId: ID
  conference(where: ConferenceWhereInputArgument): Conference!
  conferenceId: ID!
  conferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember
  conferenceMemberId: ID
  conferenceUserType: ConferenceUserTypeEnum!
  createdAt: DateTime!
  id: ID!
  paperEditors(limit: Int, offset: Int, where: PaperEditorWhereInputArgument): [PaperEditor!]!
  updatedAt: DateTime
  user(where: UserWhereInputArgument): User
  userEmail: String!
}

enum ConferenceUserTypeEnum {
  ADMIN
  DELEGATE
  NON_STATE_ACTOR
  SPECTATOR
  TEAM
}

input ConferenceUserWhereInputArgument {
  clauseLocks: PaperClauseLockWhereInputArgument
  comments: ResolutionCommentWhereInputArgument
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  conferenceMember: ConferenceMemberWhereInputArgument
  conferenceMemberId: ID
  conferenceUserType: ConferenceUserTypeEnum
  createdAt: DateTime
  id: ID
  paperEditors: PaperEditorWhereInputArgument
  updatedAt: DateTime
  user: UserWhereInputArgument
  userEmail: String
}

input ConferenceWhereInputArgument {
  committees: CommitteeWhereInputArgument
  createdAt: DateTime
  hasModeratedCaucus: Boolean
  id: ID
  members: ConferenceMemberWhereInputArgument
  pressWebsite: String
  representations: RepresentationWhereInputArgument
  title: String
  updatedAt: DateTime
  users: ConferenceUserWhereInputArgument
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTime

"""Import data. You can find the JSON schema here: /api/schema/import"""
input ImportData {
  agendaItems: [ImportDataAgendaItem!]!
  committeeMembers: [ImportDataCommitteeMember!]!
  committees: [ImportDataCommittee!]!
  conferenceMembers: [ImportDataConferenceMember!]!
  conferenceUsers: [ImportDataConferenceUser!]
  id: ID!
  representations: [ImportDataRepresentation!]!
  title: String!
}

input ImportDataAgendaItem {
  committeeId: ID!
  id: ID
  title: String!
}

input ImportDataCommittee {
  abbreviation: String!
  id: ID!
  name: String!
}

input ImportDataCommitteeMember {
  committeeId: ID!
  id: ID!
  representationId: ID!
}

input ImportDataConferenceMember {
  id: ID!
  representationId: ID!
}

input ImportDataConferenceUser {
  committeeMemberId: ID
  conferenceMemberId: ID
  conferenceUserType: ConferenceUserTypeEnum!
  id: ID
  userEmail: String!
}

input ImportDataRepresentation {
  alpha2Code: String
  alpha3Code: String
  faIcon: String
  id: ID!
  name: String
  regionalGroup: RegionalGroupEnum
  representationType: RepresentationTypeEnum!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  acquireClauseLock(clauseId: String!, paperId: ID!): PaperClauseLock
  addSpeakerOnList(committeeMemberId: ID, conferenceMemberId: ID, position: Int, speakersListId: ID!): SpeakerOnList
  addSponsor(committeeMemberId: ID!, paperId: ID!): PaperSponsor
  clearSpeakersList(id: ID!): SpeakersList
  createAgendaItem(committeeId: ID!, title: String!): AgendaItem
  createComment(clauseId: String, content: String!, paperId: ID!, parentCommentId: ID, visibility: CommentVisibilityEnum): ResolutionComment
  createCommittee(abbreviation: String!, conferenceId: ID!, name: String!): Committee
  createCommitteeMember(committeeId: ID!, representationId: ID!): CommitteeMember
  createConferenceMember(conferenceId: ID!, representationId: ID!): ConferenceMember
  createConferenceUser(conferenceId: ID!, conferenceUserType: ConferenceUserTypeEnum!, userEmail: String!): ConferenceUser
  createRepresentation(alpha2Code: String, alpha3Code: String, conferenceId: ID!, faIcon: String, name: String, type: RepresentationTypeEnum!): Representation
  createResolutionPaper(agendaItemId: ID!, committeeId: ID!, title: String): ResolutionPaper
  createShareCode(paperId: ID!, permission: ShareCodePermissionEnum!): PaperShareCode
  deleteComment(commentId: ID!): Boolean
  deleteCommittee(id: ID!): Boolean
  deleteCommitteeMember(id: ID!): Boolean
  deleteConferenceMember(id: ID!): Boolean
  deleteConferenceUser(id: ID!): Boolean
  deleteRepresentation(id: ID!): Boolean
  deleteShareCode(shareCodeId: ID!): Boolean
  importDelegatorConference(data: ImportData!): Conference
  moveSpeakerToPosition(id: ID!, position: Int!): SpeakerOnList
  promoteToDraftResolution(paperId: ID!): ResolutionPaper
  recordVoteResult(outcome: VoteOutcomeEnum!, paperId: ID!, votesAbstain: Int, votesAgainst: Int!, votesFor: Int!): ResolutionPaper
  redeemShareCode(code: String!): ShareCodeRedemptionResult
  releaseAllMyLocks(paperId: ID!): Boolean
  releaseClauseLock(clauseId: String!, paperId: ID!): Boolean
  removeEditor(conferenceUserId: ID!, paperId: ID!): Boolean
  removeSpeakerOnList(speakerOnListId: ID!): SpeakersList
  removeSponsor(committeeMemberId: ID!, paperId: ID!): Boolean
  selfAddToSpeakersList(speakersListId: ID!): SpeakerOnList
  selfRemoveFromSpeakersList(speakersListId: ID!): SpeakersList
  setPresenceForCommitteeMembers(ids: [ID!]!, present: Boolean!): [CommitteeMember!]
  softDeletePaper(paperId: ID!): Boolean
  submitPaper(paperId: ID!): ResolutionPaper
  updateComment(commentId: ID!, content: String!): ResolutionComment
  updateCommittee(abbreviation: String, activeAgendaItemId: ID, activeDraftResolutionId: ID, allowDelegationsToAddThemselvesToSpeakersList: Boolean, clearActiveDraftResolution: Boolean, currentOperativeIndex: Int, id: ID!, lastResolutionAdoptionDate: DateTime, maxDraftResolutions: Int, name: String, showWhiteboard: Boolean, stateOfDebate: String, status: CommitteeStatusEnum, statusHeadline: String, statusUntil: DateTime, supportReEvaluationOpen: Boolean, whiteboardContent: String): Committee
  updateConference(hasModeratedCaucus: Boolean, id: ID!, pressWebsite: String, title: String): Conference
  updateConferenceUser(committeeMemberId: ID, conferenceMemberId: ID, conferenceUserType: ConferenceUserTypeEnum!, id: ID!): ConferenceUser
  updatePaperContent(content: JSON!, paperId: ID!): ResolutionPaper
  updatePaperTitle(paperId: ID!, title: String!): ResolutionPaper
  updateSpeakerOnList(id: ID!, overwriteName: String): SpeakerOnList
  updateSpeakersList(id: ID!, isClosed: Boolean, speakingTime: Int, startTimestamp: DateTime, stopTimer: Boolean = false, timeLeft: Int): SpeakersList
}

type OperativeClauseVote {
  clauseId: ID!
  createdAt: DateTime!
  id: ID!
  outcome: VoteOutcomeEnum!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  updatedAt: DateTime
  votesAbstain: Int!
  votesAgainst: Int!
  votesFor: Int!
}

input OperativeClauseVoteWhereInputArgument {
  clauseId: ID
  createdAt: DateTime
  id: ID
  outcome: VoteOutcomeEnum
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  updatedAt: DateTime
  votesAbstain: Int
  votesAgainst: Int
  votesFor: Int
}

type PaperClauseLock {
  acquiredAt: DateTime!
  clauseId: ID!
  conferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  conferenceUserId: ID!
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  updatedAt: DateTime
}

input PaperClauseLockWhereInputArgument {
  acquiredAt: DateTime
  clauseId: ID
  conferenceUser: ConferenceUserWhereInputArgument
  conferenceUserId: ID
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  updatedAt: DateTime
}

type PaperContentSnapshot {
  content: JSON
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  trigger: String
  updatedAt: DateTime
}

input PaperContentSnapshotWhereInputArgument {
  content: JSON
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  trigger: String
  updatedAt: DateTime
}

type PaperEditor {
  conferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  conferenceUserId: ID!
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  updatedAt: DateTime
}

input PaperEditorWhereInputArgument {
  conferenceUser: ConferenceUserWhereInputArgument
  conferenceUserId: ID
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  updatedAt: DateTime
}

type PaperShareCode {
  code: String!
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  permission: ShareCodePermissionEnum!
  updatedAt: DateTime
}

input PaperShareCodeWhereInputArgument {
  code: String
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  permission: ShareCodePermissionEnum
  updatedAt: DateTime
}

type PaperSponsor {
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  committeeMemberId: ID!
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  updatedAt: DateTime
}

input PaperSponsorWhereInputArgument {
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  updatedAt: DateTime
}

enum PaperStatusEnum {
  AMENDMENT_PHASE
  DRAFT_RESOLUTION
  FINAL
  SUBMITTED
  WORKING_PAPER
}

type PresenceChangedTimestamp {
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember
  committeeMemberId: ID!
  createdAt: DateTime!
  id: ID!
  presentSetTo: Boolean!
  timestamp: DateTime!
  updatedAt: DateTime
}

input PresenceChangedTimestampWhereInputArgument {
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  createdAt: DateTime
  id: ID
  presentSetTo: Boolean
  timestamp: DateTime
  updatedAt: DateTime
}

type Query {
  findFirstAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem!
  findFirstAmendment(where: AmendmentWhereInputArgument): Amendment!
  findFirstAmendmentSponsor(where: AmendmentSponsorWhereInputArgument): AmendmentSponsor!
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstConferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  findFirstOperativeClauseVote(where: OperativeClauseVoteWhereInputArgument): OperativeClauseVote!
  findFirstPaperClauseLock(where: PaperClauseLockWhereInputArgument): PaperClauseLock!
  findFirstPaperContentSnapshot(where: PaperContentSnapshotWhereInputArgument): PaperContentSnapshot!
  findFirstPaperEditor(where: PaperEditorWhereInputArgument): PaperEditor!
  findFirstPaperShareCode(where: PaperShareCodeWhereInputArgument): PaperShareCode!
  findFirstPaperSponsor(where: PaperSponsorWhereInputArgument): PaperSponsor!
  findFirstPresenceChangedTimestamp(where: PresenceChangedTimestampWhereInputArgument): PresenceChangedTimestamp!
  findFirstRepresentation(where: RepresentationWhereInputArgument): Representation!
  findFirstResolutionComment(where: ResolutionCommentWhereInputArgument): ResolutionComment!
  findFirstResolutionPaper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  findFirstResolutionVoteResult(where: ResolutionVoteResultWhereInputArgument): ResolutionVoteResult!
  findFirstSpeakerOnList(where: SpeakerOnListWhereInputArgument): SpeakerOnList!
  findFirstSpeakersList(where: SpeakersListWhereInputArgument): SpeakersList!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyAgendaItem(limit: Int, offset: Int, where: AgendaItemWhereInputArgument): [AgendaItem!]!
  findManyAmendment(limit: Int, offset: Int, where: AmendmentWhereInputArgument): [Amendment!]!
  findManyAmendmentSponsor(limit: Int, offset: Int, where: AmendmentSponsorWhereInputArgument): [AmendmentSponsor!]!
  findManyCommittee(limit: Int, offset: Int, where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(limit: Int, offset: Int, where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(limit: Int, offset: Int, where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(limit: Int, offset: Int, where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyConferenceUser(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  findManyOperativeClauseVote(limit: Int, offset: Int, where: OperativeClauseVoteWhereInputArgument): [OperativeClauseVote!]!
  findManyPaperClauseLock(limit: Int, offset: Int, where: PaperClauseLockWhereInputArgument): [PaperClauseLock!]!
  findManyPaperContentSnapshot(limit: Int, offset: Int, where: PaperContentSnapshotWhereInputArgument): [PaperContentSnapshot!]!
  findManyPaperEditor(limit: Int, offset: Int, where: PaperEditorWhereInputArgument): [PaperEditor!]!
  findManyPaperShareCode(limit: Int, offset: Int, where: PaperShareCodeWhereInputArgument): [PaperShareCode!]!
  findManyPaperSponsor(limit: Int, offset: Int, where: PaperSponsorWhereInputArgument): [PaperSponsor!]!
  findManyPresenceChangedTimestamp(limit: Int, offset: Int, where: PresenceChangedTimestampWhereInputArgument): [PresenceChangedTimestamp!]!
  findManyRepresentation(limit: Int, offset: Int, where: RepresentationWhereInputArgument): [Representation!]!
  findManyResolutionComment(limit: Int, offset: Int, where: ResolutionCommentWhereInputArgument): [ResolutionComment!]!
  findManyResolutionPaper(limit: Int, offset: Int, where: ResolutionPaperWhereInputArgument): [ResolutionPaper!]!
  findManyResolutionVoteResult(limit: Int, offset: Int, where: ResolutionVoteResultWhereInputArgument): [ResolutionVoteResult!]!
  findManySpeakerOnList(limit: Int, offset: Int, where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  findManySpeakersList(limit: Int, offset: Int, where: SpeakersListWhereInputArgument): [SpeakersList!]!
  findManyUser(limit: Int, offset: Int, where: UserWhereInputArgument): [User!]!
  serverTime: DateTime!
}

enum RegionalGroupEnum {
  AFRICA
  ASIA_PACIFIC
  EASTERN_EUROPE
  LATIN_AMERICA_CARIBBEAN
  WESTERN_EUROPE_OTHERS
}

type Representation {
  alpha2Code: String
  alpha3Code: String
  committeeMembers(limit: Int, offset: Int, where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  conferenceMembers(limit: Int, offset: Int, where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  createdAt: DateTime!
  faIcon: String
  id: ID!
  name: String
  regionalGroup: RegionalGroupEnum
  type: RepresentationTypeEnum!
  updatedAt: DateTime
}

enum RepresentationTypeEnum {
  DELEGATION
  NSA
  UN
}

input RepresentationWhereInputArgument {
  alpha2Code: String
  alpha3Code: String
  committeeMembers: CommitteeMemberWhereInputArgument
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  conferenceMembers: ConferenceMemberWhereInputArgument
  createdAt: DateTime
  faIcon: String
  id: ID
  name: String
  regionalGroup: RegionalGroupEnum
  type: RepresentationTypeEnum
  updatedAt: DateTime
}

type ResolutionComment {
  author(where: ConferenceUserWhereInputArgument): ConferenceUser!
  authorConferenceUserId: ID!
  clauseId: ID
  content: String!
  createdAt: DateTime!
  id: ID!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  parentComment(where: ResolutionCommentWhereInputArgument): ResolutionComment
  parentCommentId: ID
  replies(limit: Int, offset: Int, where: ResolutionCommentWhereInputArgument): [ResolutionComment!]!
  updatedAt: DateTime
  visibility: CommentVisibilityEnum!
}

input ResolutionCommentWhereInputArgument {
  author: ConferenceUserWhereInputArgument
  authorConferenceUserId: ID
  clauseId: ID
  content: String
  createdAt: DateTime
  id: ID
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  parentComment: ResolutionCommentWhereInputArgument
  parentCommentId: ID
  replies: ResolutionCommentWhereInputArgument
  updatedAt: DateTime
  visibility: CommentVisibilityEnum
}

type ResolutionPaper {
  agendaItem(where: AgendaItemWhereInputArgument): AgendaItem!
  agendaItemId: ID!
  amendments(limit: Int, offset: Int, where: AmendmentWhereInputArgument): [Amendment!]!
  clauseLocks(limit: Int, offset: Int, where: PaperClauseLockWhereInputArgument): [PaperClauseLock!]!
  comments(limit: Int, offset: Int, where: ResolutionCommentWhereInputArgument): [ResolutionComment!]!
  committee(where: CommitteeWhereInputArgument): Committee!
  committeeId: ID!
  content: JSON
  createdAt: DateTime!
  creator(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  creatorCommitteeMemberId: ID!
  deletedAt: DateTime
  documentNumber: String
  editors(limit: Int, offset: Int, where: PaperEditorWhereInputArgument): [PaperEditor!]!
  id: ID!
  operativeClauseVotes(limit: Int, offset: Int, where: OperativeClauseVoteWhereInputArgument): [OperativeClauseVote!]!
  sequenceNumber: Int
  shareCodes(limit: Int, offset: Int, where: PaperShareCodeWhereInputArgument): [PaperShareCode!]!
  snapshots(limit: Int, offset: Int, where: PaperContentSnapshotWhereInputArgument): [PaperContentSnapshot!]!
  sponsors(limit: Int, offset: Int, where: PaperSponsorWhereInputArgument): [PaperSponsor!]!
  status: PaperStatusEnum!
  title: String
  updatedAt: DateTime
  voteResult(where: ResolutionVoteResultWhereInputArgument): ResolutionVoteResult
}

input ResolutionPaperWhereInputArgument {
  agendaItem: AgendaItemWhereInputArgument
  agendaItemId: ID
  amendments: AmendmentWhereInputArgument
  clauseLocks: PaperClauseLockWhereInputArgument
  comments: ResolutionCommentWhereInputArgument
  committee: CommitteeWhereInputArgument
  committeeId: ID
  content: JSON
  createdAt: DateTime
  creator: CommitteeMemberWhereInputArgument
  creatorCommitteeMemberId: ID
  deletedAt: DateTime
  documentNumber: String
  editors: PaperEditorWhereInputArgument
  id: ID
  operativeClauseVotes: OperativeClauseVoteWhereInputArgument
  sequenceNumber: Int
  shareCodes: PaperShareCodeWhereInputArgument
  snapshots: PaperContentSnapshotWhereInputArgument
  sponsors: PaperSponsorWhereInputArgument
  status: PaperStatusEnum
  title: String
  updatedAt: DateTime
  voteResult: ResolutionVoteResultWhereInputArgument
}

type ResolutionVoteResult {
  createdAt: DateTime!
  id: ID!
  outcome: VoteOutcomeEnum!
  paper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  paperId: ID!
  updatedAt: DateTime
  votesAbstain: Int!
  votesAgainst: Int!
  votesFor: Int!
}

input ResolutionVoteResultWhereInputArgument {
  createdAt: DateTime
  id: ID
  outcome: VoteOutcomeEnum
  paper: ResolutionPaperWhereInputArgument
  paperId: ID
  updatedAt: DateTime
  votesAbstain: Int
  votesAgainst: Int
  votesFor: Int
}

enum ShareCodePermissionEnum {
  EDIT
  SPONSOR
}

type ShareCodeRedemptionResult {
  paperId: ID
  permission: String
}

type SpeakerOnList {
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember
  committeeMemberId: ID
  conferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember
  conferenceMemberId: ID
  createdAt: DateTime!
  id: ID!
  overwriteName: String
  position: Int!
  speakersList(where: SpeakersListWhereInputArgument): SpeakersList
  speakersListId: ID!
  updatedAt: DateTime
}

input SpeakerOnListWhereInputArgument {
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  conferenceMember: ConferenceMemberWhereInputArgument
  conferenceMemberId: ID
  createdAt: DateTime
  id: ID
  overwriteName: String
  position: Int
  speakersList: SpeakersListWhereInputArgument
  speakersListId: ID
  updatedAt: DateTime
}

type SpeakersList {
  agendaItem(where: AgendaItemWhereInputArgument): AgendaItem
  agendaItemId: ID!
  createdAt: DateTime!
  id: ID!
  isClosed: Boolean!
  speakers(limit: Int, offset: Int, where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  speakingTime: Int!
  startTimestamp: DateTime
  timeLeft: Int!
  type: SpeakersListCategoryEnum!
  updatedAt: DateTime
}

enum SpeakersListCategoryEnum {
  COMMENT_LIST
  SPEAKERS_LIST
}

input SpeakersListWhereInputArgument {
  agendaItem: AgendaItemWhereInputArgument
  agendaItemId: ID
  createdAt: DateTime
  id: ID
  isClosed: Boolean
  speakers: SpeakerOnListWhereInputArgument
  speakingTime: Int
  startTimestamp: DateTime
  timeLeft: Int
  type: SpeakersListCategoryEnum
  updatedAt: DateTime
}

type Subscription {
  findFirstAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem!
  findFirstAmendment(where: AmendmentWhereInputArgument): Amendment!
  findFirstAmendmentSponsor(where: AmendmentSponsorWhereInputArgument): AmendmentSponsor!
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstConferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  findFirstOperativeClauseVote(where: OperativeClauseVoteWhereInputArgument): OperativeClauseVote!
  findFirstPaperClauseLock(where: PaperClauseLockWhereInputArgument): PaperClauseLock!
  findFirstPaperContentSnapshot(where: PaperContentSnapshotWhereInputArgument): PaperContentSnapshot!
  findFirstPaperEditor(where: PaperEditorWhereInputArgument): PaperEditor!
  findFirstPaperShareCode(where: PaperShareCodeWhereInputArgument): PaperShareCode!
  findFirstPaperSponsor(where: PaperSponsorWhereInputArgument): PaperSponsor!
  findFirstPresenceChangedTimestamp(where: PresenceChangedTimestampWhereInputArgument): PresenceChangedTimestamp!
  findFirstRepresentation(where: RepresentationWhereInputArgument): Representation!
  findFirstResolutionComment(where: ResolutionCommentWhereInputArgument): ResolutionComment!
  findFirstResolutionPaper(where: ResolutionPaperWhereInputArgument): ResolutionPaper!
  findFirstResolutionVoteResult(where: ResolutionVoteResultWhereInputArgument): ResolutionVoteResult!
  findFirstSpeakerOnList(where: SpeakerOnListWhereInputArgument): SpeakerOnList!
  findFirstSpeakersList(where: SpeakersListWhereInputArgument): SpeakersList!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyAgendaItem(limit: Int, offset: Int, where: AgendaItemWhereInputArgument): [AgendaItem!]!
  findManyAmendment(limit: Int, offset: Int, where: AmendmentWhereInputArgument): [Amendment!]!
  findManyAmendmentSponsor(limit: Int, offset: Int, where: AmendmentSponsorWhereInputArgument): [AmendmentSponsor!]!
  findManyCommittee(limit: Int, offset: Int, where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(limit: Int, offset: Int, where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(limit: Int, offset: Int, where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(limit: Int, offset: Int, where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyConferenceUser(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  findManyOperativeClauseVote(limit: Int, offset: Int, where: OperativeClauseVoteWhereInputArgument): [OperativeClauseVote!]!
  findManyPaperClauseLock(limit: Int, offset: Int, where: PaperClauseLockWhereInputArgument): [PaperClauseLock!]!
  findManyPaperContentSnapshot(limit: Int, offset: Int, where: PaperContentSnapshotWhereInputArgument): [PaperContentSnapshot!]!
  findManyPaperEditor(limit: Int, offset: Int, where: PaperEditorWhereInputArgument): [PaperEditor!]!
  findManyPaperShareCode(limit: Int, offset: Int, where: PaperShareCodeWhereInputArgument): [PaperShareCode!]!
  findManyPaperSponsor(limit: Int, offset: Int, where: PaperSponsorWhereInputArgument): [PaperSponsor!]!
  findManyPresenceChangedTimestamp(limit: Int, offset: Int, where: PresenceChangedTimestampWhereInputArgument): [PresenceChangedTimestamp!]!
  findManyRepresentation(limit: Int, offset: Int, where: RepresentationWhereInputArgument): [Representation!]!
  findManyResolutionComment(limit: Int, offset: Int, where: ResolutionCommentWhereInputArgument): [ResolutionComment!]!
  findManyResolutionPaper(limit: Int, offset: Int, where: ResolutionPaperWhereInputArgument): [ResolutionPaper!]!
  findManyResolutionVoteResult(limit: Int, offset: Int, where: ResolutionVoteResultWhereInputArgument): [ResolutionVoteResult!]!
  findManySpeakerOnList(limit: Int, offset: Int, where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  findManySpeakersList(limit: Int, offset: Int, where: SpeakersListWhereInputArgument): [SpeakersList!]!
  findManyUser(limit: Int, offset: Int, where: UserWhereInputArgument): [User!]!
}

type User {
  conferenceMemberships(limit: Int, offset: Int, where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  createdAt: DateTime!
  email: String!
  familyName: String!
  givenName: String!
  id: ID!
  locale: String
  preferredUsername: String!
  updatedAt: DateTime
}

input UserWhereInputArgument {
  conferenceMemberships: ConferenceUserWhereInputArgument
  createdAt: DateTime
  email: String
  familyName: String
  givenName: String
  id: ID
  locale: String
  preferredUsername: String
  updatedAt: DateTime
}

enum VoteOutcomeEnum {
  ADOPTED
  REJECTED
  SENT_BACK
}