"""
Indicates exactly one field must be supplied and this field must not be `null`.
"""
directive @oneOf on INPUT_OBJECT

type AgendaItem {
  committee(where: CommitteeWhereInputArgument): Committee
  committeeId: ID!
  createdAt: DateTime!
  id: ID!
  speakersList(where: SpeakersListWhereInputArgument): [SpeakersList!]!
  title: String!
  updatedAt: DateTime
}

input AgendaItemWhereInputArgument {
  committee: CommitteeWhereInputArgument
  committeeId: ID
  createdAt: DateTime
  id: ID
  speakersList: SpeakersListWhereInputArgument
  title: String
  updatedAt: DateTime
}

type Committee {
  abbreviation: String!
  activeAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem
  activeAgendaItemId: ID
  agendaItems(where: AgendaItemWhereInputArgument): [AgendaItem!]!
  allowDelegationsToAddThemselvesToSpeakersList: Boolean!
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  createdAt: DateTime!
  customPaperSupportThreshold: Int
  customSimpleMajority: Int
  customTwoThirdsMajority: Int
  id: ID!
  members(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  name: String!
  paperSupportThreshold: Int
  showWhiteboard: Boolean!
  simpleMajority: Int
  stateOfDebate: String
  status: CommitteeStatusEnum!
  statusHeadline: String!
  statusUntil: DateTime!
  totalPresent: Int
  twoThirdsMajority: Int
  updatedAt: DateTime
  whiteboardContent: String
}

type CommitteeMember {
  committeeId: ID!
  createdAt: DateTime!
  id: ID!
  present: Boolean!
  representationId: ID!
  updatedAt: DateTime
}

input CommitteeMemberWhereInputArgument {
  committeeId: ID
  createdAt: DateTime
  id: ID
  present: Boolean
  representationId: ID
  updatedAt: DateTime
}

enum CommitteeStatusEnum {
  FORMAL
  INFORMAL
  PAUSE
  SUSPENSION
}

input CommitteeWhereInputArgument {
  abbreviation: String
  activeAgendaItem: AgendaItemWhereInputArgument
  activeAgendaItemId: ID
  agendaItems: AgendaItemWhereInputArgument
  allowDelegationsToAddThemselvesToSpeakersList: Boolean
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  createdAt: DateTime
  customPaperSupportThreshold: Int
  customSimpleMajority: Int
  customTwoThirdsMajority: Int
  id: ID
  members: CommitteeMemberWhereInputArgument
  name: String
  showWhiteboard: Boolean
  stateOfDebate: String
  status: CommitteeStatusEnum
  statusHeadline: String
  statusUntil: DateTime
  updatedAt: DateTime
  whiteboardContent: String
}

type Conference {
  committees(where: CommitteeWhereInputArgument): [Committee!]!
  createdAt: DateTime!
  id: ID!
  members(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  pressWebsite: String
  representations(where: RepresentationWhereInputArgument): [Representation!]!
  title: String!
  updatedAt: DateTime
  users(where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
}

type ConferenceMember {
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  createdAt: DateTime!
  id: ID!
  representation(where: RepresentationWhereInputArgument): Representation
  representationId: ID!
  speakerOnList(where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  updatedAt: DateTime
}

input ConferenceMemberWhereInputArgument {
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  createdAt: DateTime
  id: ID
  representation: RepresentationWhereInputArgument
  representationId: ID
  speakerOnList: SpeakerOnListWhereInputArgument
  updatedAt: DateTime
}

type ConferenceUser {
  committeeMemberId: ID
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  conferenceMemberId: ID
  conferenceUserType: ConferenceUserTypeEnum!
  createdAt: DateTime!
  id: ID!
  updatedAt: DateTime
  user(where: UserWhereInputArgument): User
  userId: String!
}

enum ConferenceUserTypeEnum {
  ADMIN
  DELEGATE
  NON_STATE_ACTOR
  SPECTATOR
  TEAM
}

input ConferenceUserWhereInputArgument {
  committeeMemberId: ID
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  conferenceMemberId: ID
  conferenceUserType: ConferenceUserTypeEnum
  createdAt: DateTime
  id: ID
  updatedAt: DateTime
  user: UserWhereInputArgument
  userId: String
}

input ConferenceWhereInputArgument {
  committees: CommitteeWhereInputArgument
  createdAt: DateTime
  id: ID
  members: ConferenceMemberWhereInputArgument
  pressWebsite: String
  representations: RepresentationWhereInputArgument
  title: String
  updatedAt: DateTime
  users: ConferenceUserWhereInputArgument
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTime

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  addSpeakerOnList(committeeMemberId: ID, conferenceMemberId: ID, position: Int, speakersListId: ID!): SpeakerOnList
  clearSpeakersList(id: ID!): SpeakersList
  moveSpeakerToPosition(id: ID!, position: Int!): SpeakerOnList
  removeSpeakerOnList(speakerOnListId: ID!): SpeakersList
  setPresenceForCommitteeMembers(ids: [ID!]!, present: Boolean!): [CommitteeMember!]
  updateCommittee(activeAgendaItemId: ID, id: ID!, showWhiteboard: Boolean, stateOfDebate: String, status: CommitteeStatusEnum, statusHeadline: String, statusUntil: DateTime, whiteboardContent: String): Committee
  updateSpeakersList(id: ID!, isClosed: Boolean, speakingTime: Int, startTimestamp: DateTime, timeLeft: Int): SpeakersList
}

type Query {
  findFirstAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem!
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstConferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  findFirstRepresentation(where: RepresentationWhereInputArgument): Representation!
  findFirstSpeakerOnList(where: SpeakerOnListWhereInputArgument): SpeakerOnList!
  findFirstSpeakersList(where: SpeakersListWhereInputArgument): SpeakersList!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyAgendaItem(where: AgendaItemWhereInputArgument): [AgendaItem!]!
  findManyCommittee(where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyConferenceUser(where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  findManyRepresentation(where: RepresentationWhereInputArgument): [Representation!]!
  findManySpeakerOnList(where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  findManySpeakersList(where: SpeakersListWhereInputArgument): [SpeakersList!]!
  findManyUser(where: UserWhereInputArgument): [User!]!
  serverTime: DateTime!
}

enum RegionalGroupEnum {
  AFRICA
  ASIA_PACIFIC
  EASTERN_EUROPE
  LATIN_AMERICA_CARIBBEAN
  WESTERN_EUROPE_OTHERS
}

type Representation {
  alpha2Code: String
  alpha3Code: String
  committeeMembers(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  conference(where: ConferenceWhereInputArgument): Conference
  conferenceId: ID!
  conferenceMembers(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  createdAt: DateTime!
  id: ID!
  name: String
  regionalGroup: RegionalGroupEnum
  type: RepresentationTypeEnum!
  updatedAt: DateTime
}

enum RepresentationTypeEnum {
  DELEGATION
  NSA
  UN
}

input RepresentationWhereInputArgument {
  alpha2Code: String
  alpha3Code: String
  committeeMembers: CommitteeMemberWhereInputArgument
  conference: ConferenceWhereInputArgument
  conferenceId: ID
  conferenceMembers: ConferenceMemberWhereInputArgument
  createdAt: DateTime
  id: ID
  name: String
  regionalGroup: RegionalGroupEnum
  type: RepresentationTypeEnum
  updatedAt: DateTime
}

type SpeakerOnList {
  committeeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember
  committeeMemberId: ID
  conferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember
  conferenceMemberId: ID
  createdAt: DateTime!
  id: ID!
  position: Int!
  speakersList(where: SpeakersListWhereInputArgument): SpeakersList
  speakersListId: ID!
  updatedAt: DateTime
}

input SpeakerOnListWhereInputArgument {
  committeeMember: CommitteeMemberWhereInputArgument
  committeeMemberId: ID
  conferenceMember: ConferenceMemberWhereInputArgument
  conferenceMemberId: ID
  createdAt: DateTime
  id: ID
  position: Int
  speakersList: SpeakersListWhereInputArgument
  speakersListId: ID
  updatedAt: DateTime
}

type SpeakersList {
  agendaItem(where: AgendaItemWhereInputArgument): AgendaItem
  agendaItemId: ID!
  createdAt: DateTime!
  id: ID!
  isClosed: Boolean!
  speakers(where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  speakingTime: Int!
  startTimestamp: DateTime
  timeLeft: Int!
  type: SpeakersListCategoryEnum!
  updatedAt: DateTime
}

enum SpeakersListCategoryEnum {
  COMMENT_LIST
  SPEAKERS_LIST
}

input SpeakersListWhereInputArgument {
  agendaItem: AgendaItemWhereInputArgument
  agendaItemId: ID
  createdAt: DateTime
  id: ID
  isClosed: Boolean
  speakers: SpeakerOnListWhereInputArgument
  speakingTime: Int
  startTimestamp: DateTime
  timeLeft: Int
  type: SpeakersListCategoryEnum
  updatedAt: DateTime
}

type Subscription {
  findFirstAgendaItem(where: AgendaItemWhereInputArgument): AgendaItem!
  findFirstCommittee(where: CommitteeWhereInputArgument): Committee!
  findFirstCommitteeMember(where: CommitteeMemberWhereInputArgument): CommitteeMember!
  findFirstConference(where: ConferenceWhereInputArgument): Conference!
  findFirstConferenceMember(where: ConferenceMemberWhereInputArgument): ConferenceMember!
  findFirstConferenceUser(where: ConferenceUserWhereInputArgument): ConferenceUser!
  findFirstRepresentation(where: RepresentationWhereInputArgument): Representation!
  findFirstSpeakerOnList(where: SpeakerOnListWhereInputArgument): SpeakerOnList!
  findFirstSpeakersList(where: SpeakersListWhereInputArgument): SpeakersList!
  findFirstUser(where: UserWhereInputArgument): User!
  findManyAgendaItem(where: AgendaItemWhereInputArgument): [AgendaItem!]!
  findManyCommittee(where: CommitteeWhereInputArgument): [Committee!]!
  findManyCommitteeMember(where: CommitteeMemberWhereInputArgument): [CommitteeMember!]!
  findManyConference(where: ConferenceWhereInputArgument): [Conference!]!
  findManyConferenceMember(where: ConferenceMemberWhereInputArgument): [ConferenceMember!]!
  findManyConferenceUser(where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  findManyRepresentation(where: RepresentationWhereInputArgument): [Representation!]!
  findManySpeakerOnList(where: SpeakerOnListWhereInputArgument): [SpeakerOnList!]!
  findManySpeakersList(where: SpeakersListWhereInputArgument): [SpeakersList!]!
  findManyUser(where: UserWhereInputArgument): [User!]!
}

type User {
  conferenceMemberships(where: ConferenceUserWhereInputArgument): [ConferenceUser!]!
  createdAt: DateTime!
  email: String!
  familyName: String!
  givenName: String!
  id: String!
  locale: String
  preferredUsername: String!
  updatedAt: DateTime
}

input UserWhereInputArgument {
  conferenceMemberships: ConferenceUserWhereInputArgument
  createdAt: DateTime
  email: String
  familyName: String
  givenName: String
  id: String
  locale: String
  preferredUsername: String
  updatedAt: DateTime
}
