#!/usr/bin/env bash
# Guided builder for the MUNify CHASE Pi display image.
# Prompts for CHASE base URL + OIDC details only; WiFi is provisioned at
# first boot via the kiosk's own AP + captive portal, so the SSID does
# not need to be known at flash time. No secrets are committed to the repo.
set -euo pipefail
cd "$(dirname "$0")"

echo "MUNify CHASE — Pi display image builder"
echo

read -rp "CHASE base URL (e.g. https://chase.example.org): " BASE_URL
read -rp "OIDC discovery URL (…/.well-known/openid-configuration): " OIDC_AUTHORITY
read -rp "OIDC client id (shared display app): " OIDC_CLIENT_ID

# Escape a value for safe embedding in a Nix "..." string literal.
# Order matters: backslash first, then quote, then dollar (neutralises ${...}).
escape_nix_string() {
	local s=$1
	s=${s//\\/\\\\}
	s=${s//\"/\\\"}
	s=${s//\$/\\\$}
	printf '%s' "$s"
}

cat > local.nix <<EOF
# Generated by build-image.sh — DO NOT COMMIT (gitignored).
{ ... }:
{
  services.chaseKiosk = {
    enable = true;
    baseUrl = "$(escape_nix_string "$BASE_URL")";
    oidcAuthority = "$(escape_nix_string "$OIDC_AUTHORITY")";
    oidcClientId = "$(escape_nix_string "$OIDC_CLIENT_ID")";
  };
}
EOF
chmod 600 local.nix

echo
echo "Wrote local.nix. Building SD image (this takes a while)…"
nix build --impure \
  '.#nixosConfigurations.chase-kiosk.config.system.build.sdImage'

echo
echo "Done. Flash ./result/sd-image/*.img.zst to an SD card, e.g.:"
echo "  zstdcat result/sd-image/*.img.zst | sudo dd of=/dev/sdX bs=4M status=progress"
