#!/usr/bin/env bash
# Guided builder for the MUNify CHASE Pi display image.
# Prompts for CHASE base URL + OIDC details only; WiFi is provisioned at
# first boot via the kiosk's own AP + captive portal, so the SSID does
# not need to be known at flash time. No secrets are committed to the repo.
set -euo pipefail
cd "$(dirname "$0")"

echo "MUNify CHASE — Pi display image builder"
echo

# A base URL missing its scheme (e.g. "chase.example.org" instead of
# "https://chase.example.org") doesn't fail loudly — chase-kiosk-helper.py
# embeds it verbatim as the session-bridge form's `action`, and a browser
# treats a scheme-less action as *relative* to whatever page it's on (the
# kiosk's own local bootstrap page), silently posting the OIDC tokens back
# to 127.0.0.1:8081 instead of the real CHASE server. That surfaces on the
# kiosk screen as an opaque "501 Unsupported method" page with nothing to
# suggest the actual cause, so this is validated up front instead.
while true; do
	read -rp "CHASE base URL (e.g. https://chase.example.org): " BASE_URL
	case "$BASE_URL" in
	http://* | https://*) break ;;
	*) echo "Must start with http:// or https:// — got \"$BASE_URL\"." ;;
	esac
done

while true; do
	read -rp "OIDC discovery URL (…/.well-known/openid-configuration): " OIDC_AUTHORITY
	case "$OIDC_AUTHORITY" in
	http://* | https://*) break ;;
	*) echo "Must start with http:// or https:// — got \"$OIDC_AUTHORITY\"." ;;
	esac
done

read -rp "OIDC client id (shared display app): " OIDC_CLIENT_ID

read -rp "SSH access method:
  1) SSH public key (recommended)
  2) Random password
  3) Disable SSH

Choice [1]: " SSH_MODE

SSH_MODE=${SSH_MODE:-1}

SSH_CONFIG=""

# Escape a value for safe embedding in a Nix "..." string literal.
# Order matters: backslash first, then quote, then dollar (neutralises ${...}).
escape_nix_string() {
	local s=$1
	s=${s//\\/\\\\}
	s=${s//\"/\\\"}
	s=${s//\$/\\\$}
	printf '%s' "$s"
}

case "$SSH_MODE" in

1)
    DEFAULT_KEY="$HOME/.ssh/id_ed25519.pub"
    read -rp "SSH public key [$DEFAULT_KEY]: " SSH_KEY_PATH
    SSH_KEY_PATH=${SSH_KEY_PATH:-$DEFAULT_KEY}

    if [[ ! -f "$SSH_KEY_PATH" ]]; then
        echo "Public key not found: $SSH_KEY_PATH"
        exit 1
    fi

    SSH_KEY="$(<"$SSH_KEY_PATH")"

    SSH_CONFIG=$(cat <<EOF
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  users.users.admin = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    openssh.authorizedKeys.keys = [
      "$(escape_nix_string "$SSH_KEY")"
    ];
  };
EOF
)
;;

2)
    SSH_PASSWORD="$(openssl rand -base64 18 | tr -d '=+/')"
    SSH_PASSWORD_HASH="$(mkpasswd -m yescrypt --stdin <<< "$SSH_PASSWORD")"

    echo
    echo "======================================"
    echo "SSH credentials"
    echo "======================================"
    echo "Username: admin"
    echo "Password: $SSH_PASSWORD"
    echo "======================================"
    echo

    SSH_CONFIG=$(cat <<EOF
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
      PermitRootLogin = "no";
    };
  };

  users.users.admin = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    hashedPassword = "$(escape_nix_string "$SSH_PASSWORD_HASH")";
  };
EOF
)
;;

3)
    SSH_CONFIG=""
;;

*)
    echo "Invalid SSH choice"
    exit 1
;;

esac

cat > local.nix <<EOF
# Generated by build-image.sh — DO NOT COMMIT (gitignored).
{ ... }:
{
  services.chaseKiosk = {
    enable = true;
    baseUrl = "$(escape_nix_string "$BASE_URL")";
    oidcAuthority = "$(escape_nix_string "$OIDC_AUTHORITY")";
    oidcClientId = "$(escape_nix_string "$OIDC_CLIENT_ID")";
  };

$SSH_CONFIG
}
EOF
chmod 600 local.nix

echo
echo "Wrote local.nix."

# Nix flakes only see git-tracked files. local.nix is gitignored on purpose
# (it holds instance-specific config — OIDC client id, base URL, and an SSH
# key/password hash), so it must be force-staged — never committed — for the
# flake evaluator to find it. Unstage it again on exit, success or failure,
# so it can't end up in a later `git commit` by accident; the trap runs
# regardless of how the script exits (including Ctrl-C or `nix build`
# failing under `set -e`). The file itself is left in place, just untracked
# again, so re-running the build doesn't require re-entering everything.
git add -f local.nix
trap 'git restore --staged local.nix 2>/dev/null || git reset -- local.nix 2>/dev/null || true' EXIT

echo "Building SD image (this takes a while)…"
nix build --impure \
  '.#nixosConfigurations.chase-kiosk.config.system.build.sdImage'

echo
echo "Done. Flash ./result/sd-image/*.img.zst to an SD card, e.g.:"
echo "  zstdcat result/sd-image/*.img.zst | sudo dd of=/dev/sdX bs=4M status=progress"