// Kept free of app imports, the screenshot script outside SvelteKit uses it too

export const SCREENSHOT_THEMES = ['light', 'dark'] as const;

/** Generated by `bun run docs:screenshots`, see scripts/docs-screenshots/ */
export function screenshotPath(locale: string, theme: string, id: string) {
	return `/docs-assets/screenshots/${locale}/${theme}/${id}.jpg`;
}
