query CommitteePresentationQuery($committeeId: ID!) @blocking {
	findFirstCommittee(where: { id: $committeeId }) {
		id
		abbreviation
		name
		status
		statusHeadline
		statusUntil
		activeAgendaItem {
			id
			title
		}
		whiteboardContent
		customSimpleMajority
		customTwoThirdsMajority
		customPaperSupportThreshold
	}
}
