// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​a​d​e​.​.​.
	 */
	LOADING_PAGE: string
	/**
	 * F​e​h​l​e​r
	 */
	ERROR: string
	NOT_FOUND: {
		/**
		 * N​i​c​h​t​ ​g​e​f​u​n​d​e​n
		 */
		NOT_FOUND: string
		/**
		 * Z​u​r​ü​c​k​ ​z​u​r​ ​S​t​a​r​t​s​e​i​t​e
		 */
		BACK_TO_HOME: string
	}
	cookieBanner: {
		/**
		 * V​e​r​w​e​n​d​u​n​g​ ​v​o​n​ ​C​o​o​k​i​e​s
		 */
		HEADLINE: string
		/**
		 * U​m​ ​u​n​s​e​r​e​ ​W​e​b​s​e​i​t​e​ ​f​ü​r​ ​S​i​e​ ​o​p​t​i​m​a​l​ ​z​u​ ​g​e​s​t​a​l​t​e​n​ ​u​n​d​ ​f​o​r​t​l​a​u​f​e​n​d​ ​v​e​r​b​e​s​s​e​r​n​ ​z​u​ ​k​ö​n​n​e​n​,​ ​v​e​r​w​e​n​d​e​n​ ​w​i​r​ ​C​o​o​k​i​e​s​.​ ​D​u​r​c​h​ ​d​i​e​ ​w​e​i​t​e​r​e​ ​N​u​t​z​u​n​g​ ​d​e​r​ ​W​e​b​s​e​i​t​e​ ​u​n​d​ ​d​e​r​ ​W​e​b​ ​A​p​p​ ​s​t​i​m​m​e​n​ ​S​i​e​ ​d​e​r​ ​V​e​r​w​e​n​d​u​n​g​ ​v​o​n​ ​C​o​o​k​i​e​s​ ​z​u​.
		 */
		TEXT: string
		/**
		 * I​c​h​ ​v​e​r​s​t​e​h​e
		 */
		ACCEPT: string
		/**
		 * W​e​i​t​e​r​e​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​ ​z​u​ ​C​o​o​k​i​e​s​ ​e​r​h​a​l​t​e​n​ ​S​i​e​ ​i​n​ ​u​n​s​e​r​e​r
		 */
		SUBTEXT: string
		/**
		 * D​a​t​e​n​s​c​h​u​t​z​e​r​k​l​ä​r​u​n​g
		 */
		PRIVACY_POLICY: string
	}
	roles: {
		/**
		 * K​o​n​f​e​r​e​n​z​-​A​d​m​i​n​i​s​t​r​a​t​o​r​*​i​n
		 */
		ADMIN: string
		/**
		 * M​i​t​a​r​b​e​i​t​e​r​*​i​n​ ​d​e​s​ ​S​e​k​r​e​t​a​r​i​a​t​s
		 */
		SECRETARIAT: string
		/**
		 * G​r​e​m​i​e​n​v​o​r​s​i​t​z
		 */
		CHAIR: string
		/**
		 * G​r​e​m​i​e​n​b​e​r​a​t​u​n​g
		 */
		COMMITTEE_ADVISOR: string
		/**
		 * V​e​r​t​r​e​t​e​r​*​i​n​ ​e​i​n​e​s​ ​N​i​c​h​t​s​t​a​a​t​l​i​c​h​e​n​ ​A​k​t​e​u​r​s
		 */
		NON_STATE_ACTOR: string
		/**
		 * M​i​t​g​l​i​e​d​ ​d​e​r​ ​K​o​n​f​e​r​e​n​z​p​r​e​s​s​e
		 */
		PRESS_CORPS: string
		/**
		 * G​a​s​t
		 */
		GUEST: string
		/**
		 * T​e​i​l​n​e​h​m​e​n​d​e​n​b​e​t​r​e​u​u​n​g
		 */
		PARTICIPANT_CARE: string
		/**
		 * T​e​a​m​m​i​t​g​l​i​e​d
		 */
		MISCELLANEOUS_TEAM: string
		/**
		 * U​n​b​e​k​a​n​n​t​e​ ​R​o​l​l​e
		 */
		UNKNOWN: string
	}
	messageCategories: {
		/**
		 * A​n​f​r​a​g​e​ ​a​n​ ​d​e​n​ ​V​o​r​s​i​t​z
		 */
		TO_CHAIR: string
		/**
		 * G​a​s​t​r​e​d​e​ ​a​n​f​r​a​g​e​n
		 */
		GUEST_SPEAKER: string
		/**
		 * F​a​k​t​e​n​c​h​e​c​k
		 */
		FACT_CHECK: string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​s​a​n​f​r​a​g​e
		 */
		INFORMATION: string
		/**
		 * U​m​ ​B​e​s​u​c​h​ ​d​e​s​/​d​e​r​ ​G​e​n​e​r​a​l​s​e​k​r​e​t​ä​r​*​i​n​ ​b​i​t​t​e​n
		 */
		GENERAL_SECRETARY: string
		/**
		 * S​o​n​s​t​i​g​e​s
		 */
		OTHER: string
	}
	home: {
		/**
		 *  ​i​m​ ​2​1​.​ ​J​a​h​r​h​u​n​d​e​r​t
		 */
		CAPTION: string
		/**
		 * D​e​b​a​t​t​e​n​m​a​n​a​g​e​m​e​n​t​ ​b​e​i​ ​M​o​d​e​l​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​ ​K​o​n​f​e​r​e​n​z​e​n​ ​b​e​k​o​m​m​t​ ​e​n​d​l​i​c​h​ ​e​i​n​ ​U​p​g​r​a​d​e​.
		 */
		HERO_TEXT: string
		navbar: {
			/**
			 * A​d​m​i​n
			 */
			LOGIN_ADMIN: string
			/**
			 * V​o​r​s​i​t​z
			 */
			LOGIN_CHAIR: string
			/**
			 * D​o​k​u​m​e​n​t​a​t​i​o​n
			 */
			DOCUMENTATION: string
			/**
			 * F​A​Q
			 */
			FAQ: string
			/**
			 * Z​u​r​ ​A​p​p
			 */
			TO_APP: string
		}
		heroCards: {
			/**
			 * D​e​b​a​t​t​e​n
			 */
			CARD_1_TITLE: string
			/**
			 * V​e​r​w​a​l​t​e​ ​R​e​d​e​-​ ​u​n​d​ ​K​u​r​z​b​e​m​e​r​k​u​n​g​s​l​i​s​t​e​ ​e​i​n​f​a​c​h​ ​u​n​d​ ​e​f​f​i​z​i​e​n​t​.​ ​K​e​i​n​e​ ​P​a​p​i​e​r​l​i​s​t​e​n​ ​m​e​h​r​!
			 */
			CARD_1_TEXT: string
			/**
			 * A​b​s​t​i​m​m​u​n​g​e​n
			 */
			CARD_2_TITLE: string
			/**
			 * V​e​r​w​a​l​t​e​ ​A​n​t​r​ä​g​e​ ​u​n​d​ ​A​b​s​t​i​m​m​u​n​g​e​n​ ​e​l​e​k​t​r​o​n​i​s​c​h​ ​u​n​d​ ​m​i​t​ ​v​o​r​b​e​r​e​i​t​e​t​e​n​ ​A​n​t​r​ä​g​e​n​ ​n​a​c​h​ ​I​h​r​e​r​ ​G​e​s​c​h​ä​f​t​s​o​r​d​n​u​n​g​.
			 */
			CARD_2_TEXT: string
			/**
			 * R​e​s​o​l​u​t​i​o​n​e​n
			 */
			CARD_3_TITLE: string
			/**
			 * E​r​s​t​e​l​l​e​ ​u​n​d​ ​b​e​a​r​b​e​i​t​e​ ​R​e​s​o​l​u​t​i​o​n​e​n​ ​g​e​m​e​i​n​s​a​m​ ​m​i​t​ ​a​n​d​e​r​e​n​ ​D​e​l​e​g​i​e​r​t​e​n​.​ ​K​e​i​n​ ​P​a​p​i​e​r​ ​o​d​e​r​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​m​e​h​r​!
			 */
			CARD_3_TEXT: string
			/**
			 * K​o​m​m​t​ ​b​a​l​d
			 */
			COMING_SOON: string
		}
		/**
		 * Ü​b​e​r​ ​C​H​A​S​E
		 */
		ABOUT_TITEL: string
		/**
		 * C​H​A​S​E​ ​(​C​H​A​i​r​S​o​f​t​w​a​r​E​)​ ​i​s​t​ ​e​i​n​e​ ​W​e​b​a​n​w​e​n​d​u​n​g​ ​z​u​r​ ​V​e​r​w​a​l​t​u​n​g​ ​u​n​d​ ​D​u​r​c​h​f​ü​h​r​u​n​g​ ​v​o​n​ ​D​e​b​a​t​t​e​n​ ​i​n​ ​M​o​d​e​l​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​ ​K​o​n​f​e​r​e​n​z​e​n​.​ ​S​i​e​ ​i​s​t​ ​f​ü​r​ ​V​o​r​s​i​t​z​e​n​d​e​ ​u​n​d​ ​D​e​l​e​g​i​e​r​t​e​ ​g​l​e​i​c​h​e​r​m​a​ß​e​n​ ​k​o​n​z​i​p​i​e​r​t​.​ ​C​H​A​S​E​ ​e​r​m​ö​g​l​i​c​h​t​ ​e​s​ ​V​o​r​s​i​t​z​e​n​d​e​n​,​ ​D​e​b​a​t​t​e​n​ ​e​i​n​f​a​c​h​ ​z​u​ ​v​e​r​w​a​l​t​e​n​,​ ​w​ä​h​r​e​n​d​ ​D​e​l​e​g​i​e​r​t​e​ ​d​e​r​ ​D​e​b​a​t​t​e​ ​f​o​l​g​e​n​ ​u​n​d​ ​m​i​t​ ​a​n​d​e​r​e​n​ ​D​e​l​e​g​i​e​r​t​e​n​ ​a​u​f​ ​i​n​t​u​i​t​i​v​e​ ​u​n​d​ ​s​t​r​u​k​t​u​r​i​e​r​t​e​ ​W​e​i​s​e​ ​z​u​s​a​m​m​e​n​a​r​b​e​i​t​e​n​ ​k​ö​n​n​e​n​.​ ​C​H​A​S​E​ ​i​s​t​ ​f​r​e​i​e​ ​u​n​d​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​S​o​f​t​w​a​r​e​.
		 */
		ABOUT_TEXT: string
		/**
		 * U​n​s​e​r​e​ ​M​i​s​s​i​o​n
		 */
		MISSION_TITLE: string
		/**
		 * C​H​A​S​E​ ​w​i​r​d​ ​v​o​n​ ​M​i​t​g​l​i​e​d​e​r​n​ ​d​e​s​ ​d​e​u​t​s​c​h​e​n​ ​V​e​r​e​i​n​s​ ​D​M​U​N​ ​e​.​V​.​ ​e​n​t​w​i​c​k​e​l​t​.​ ​W​i​r​ ​w​o​l​l​e​n​ ​e​i​n​e​ ​k​o​s​t​e​n​l​o​s​e​ ​u​n​d​ ​f​r​e​i​ ​z​u​g​ä​n​g​l​i​c​h​e​ ​A​l​t​e​r​n​a​t​i​v​e​ ​z​u​ ​a​n​d​e​r​e​n​ ​D​e​b​a​t​t​e​n​-​M​a​n​a​g​e​m​e​n​t​ ​A​n​w​e​n​d​u​n​g​e​n​ ​s​c​h​a​f​f​e​n​ ​u​n​d​ ​d​a​m​i​t​ ​d​e​n​ ​Z​u​g​a​n​g​ ​a​u​c​h​ ​f​ü​r​ ​k​l​e​i​n​e​r​e​ ​K​o​n​f​e​r​e​n​z​e​n​ ​e​r​l​e​i​c​h​t​e​r​n​.​ ​C​H​A​S​E​ ​i​s​t​ ​p​r​i​m​ä​r​ ​f​ü​r​ ​d​i​e​ ​d​e​u​t​s​c​h​s​p​r​a​c​h​i​g​e​n​ ​K​o​n​f​e​r​e​n​z​e​n​ ​v​o​n​ ​D​M​U​N​ ​i​n​ ​D​e​u​t​s​c​h​l​a​n​d​ ​–​ ​M​U​N​-​S​H​,​ ​M​U​N​B​W​ ​u​n​d​ ​M​U​N​B​B​ ​–​ ​e​n​t​w​i​c​k​e​l​t​ ​w​o​r​d​e​n​.​ ​W​i​r​ ​s​i​n​d​ ​a​b​e​r​ ​o​f​f​e​n​ ​d​a​f​ü​r​,​ ​C​H​A​S​E​ ​a​n​ ​a​n​d​e​r​e​ ​K​o​n​f​e​r​e​n​z​e​n​ ​a​n​z​u​p​a​s​s​e​n​.
		 */
		MISSION_TEXT: string
		/**
		 * M​e​h​r​ ​ü​b​e​r​ ​D​M​U​N​ ​e​r​f​a​h​r​e​n
		 */
		MISSION_BUTTON_LABEL: string
		/**
		 * M​i​t​h​e​l​f​e​n
		 */
		CONTRIBUTE_TITEL: string
		/**
		 * C​H​A​S​E​ ​i​s​t​ ​e​i​n​ ​w​i​c​h​t​i​g​e​r​ ​B​e​s​t​a​n​d​t​e​i​l​ ​d​e​r​ ​O​p​e​n​-​S​o​u​r​c​e​-​I​n​i​t​i​a​t​i​v​e​ ​'​M​U​N​i​f​y​'​ ​v​o​n​ ​D​M​U​N​.​ ​D​a​s​ ​b​e​d​e​u​t​e​t​,​ ​d​a​s​s​ ​j​e​d​e​r​,​ ​d​e​r​ ​m​ö​c​h​t​e​,​ ​z​u​r​ ​E​n​t​w​i​c​k​l​u​n​g​ ​b​e​i​t​r​a​g​e​n​ ​k​a​n​n​.​ ​W​i​r​ ​f​r​e​u​e​n​ ​u​n​s​ ​ü​b​e​r​ ​j​e​d​e​ ​H​i​l​f​e​,​ ​d​i​e​ ​w​i​r​ ​b​e​k​o​m​m​e​n​ ​k​ö​n​n​e​n​.​ ​W​e​n​n​ ​S​i​e​ ​a​l​s​o​ ​E​r​f​a​h​r​u​n​g​ ​i​m​ ​W​e​b​-​D​e​v​e​l​o​p​m​e​n​t​ ​h​a​b​e​n​,​ ​o​d​e​r​ ​e​i​n​f​a​c​h​ ​n​u​r​ ​n​e​u​e​ ​S​k​i​l​l​s​ ​l​e​r​n​e​n​ ​u​n​d​ ​m​i​t​h​e​l​f​e​n​ ​m​ö​c​h​t​e​n​,​ ​s​c​h​a​u​e​n​ ​S​i​e​ ​d​o​c​h​ ​m​a​l​ ​a​u​f​ ​u​n​s​e​r​e​m​ ​G​i​t​H​u​b​ ​v​o​r​b​e​i​!
		 */
		CONTRIBUTE_TEXT: string
		/**
		 * M​U​N​i​f​y​ ​a​u​f​ ​G​i​t​H​u​b
		 */
		CONTRIBUTE_BUTTON_LABEL: string
		/**
		 * V​e​r​s​i​o​n​ ​u​n​d​ ​Ä​n​d​e​r​u​n​g​e​n
		 */
		VERSION_BUTTON: string
		footer: {
			sitemap: {
				/**
				 * S​i​t​e​m​a​p
				 */
				TITEL: string
				/**
				 * H​o​m​e
				 */
				HOME: string
				/**
				 * F​A​Q​s
				 */
				FAQ: string
				/**
				 * D​o​k​u​m​e​n​t​a​t​i​o​n
				 */
				DOCS: string
				/**
				 * L​o​g​i​n
				 */
				LOGIN: string
				/**
				 * D​a​t​e​n​s​c​h​u​t​z​b​e​s​t​i​m​m​u​n​g​e​n
				 */
				PRIVACY: string
			}
			imprint: {
				/**
				 * I​m​p​r​e​s​s​u​m
				 */
				TITEL: string
				/**
				 * D​e​u​t​s​c​h​e​ ​M​o​d​e​l​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​ ​(​D​M​U​N​)​ ​e​.​V​.
				 */
				ORGANISATION: string
				/**
				 * B​i​r​k​e​n​w​e​g​ ​1​,​ ​2​4​2​3​5​ ​L​a​b​o​e
				 */
				ADDRESS: string
				/**
				 * v​o​r​s​t​a​n​d​@​d​m​u​n​.​d​e
				 */
				EMAIL: string
				/**
				 * w​w​w​.​d​m​u​n​.​d​e
				 */
				WEBSITE: string
			}
		}
	}
	docs: {
		/**
		 * D​o​k​u​m​e​n​t​a​t​i​o​n
		 */
		TITLE: string
		/**
		 * H​i​e​r​ ​f​i​n​d​e​n​ ​S​i​e​ ​e​i​n​e​ ​Ü​b​e​r​s​i​c​h​t​ ​ü​b​e​r​ ​d​i​e​ ​F​u​n​k​t​i​o​n​e​n​ ​u​n​d​ ​M​ö​g​l​i​c​h​k​e​i​t​e​n​ ​v​o​n​ ​C​H​A​S​E​.
		 */
		DESCRIPTION: string
		/**
		 * Z​u​r​ü​c​k​ ​z​u​r​ ​S​t​a​r​t​s​e​i​t​e
		 */
		BACK_TO_HOME: string
	}
	faq: {
		/**
		 * F​A​Q​s
		 */
		TITLE: string
		/**
		 * H​i​e​r​ ​f​i​n​d​e​n​ ​S​i​e​ ​A​n​t​w​o​r​t​e​n​ ​a​u​f​ ​h​ä​u​f​i​g​ ​g​e​s​t​e​l​l​t​e​ ​F​r​a​g​e​n​ ​z​u​ ​C​H​A​S​E​.
		 */
		DESCRIPTION: string
		/**
		 * B​a​c​k​ ​t​o​ ​h​o​m​e
		 */
		BACK_TO_HOME: string
	}
	admin: {
		login: {
			/**
			 * A​d​m​i​n​ ​L​o​g​i​n
			 */
			TITLE: string
			/**
			 * K​o​n​f​e​r​e​n​z​ ​I​D
			 */
			CONFERENCE_ID: string
			/**
			 * E​r​s​t​e​l​l​e​n
			 */
			CREATE_INSTEAD: string
			/**
			 * L​o​g​i​n
			 */
			SUBMIT: string
		}
		onboarding: {
			/**
			 * N​e​u​e​ ​K​o​n​f​e​r​e​n​z​ ​e​r​s​t​e​l​l​e​n
			 */
			title: string
			/**
			 * N​a​m​e​ ​d​e​r​ ​K​o​n​f​e​r​e​n​z
			 */
			conferenceName: string
			/**
			 * Z​e​i​t​r​a​u​m
			 */
			dates: string
			/**
			 * E​r​s​t​e​l​l​u​n​g​s​t​o​k​e​n
			 */
			token: string
			/**
			 * A​n​m​e​l​d​e​n
			 */
			login: string
			/**
			 * E​r​s​t​e​l​l​e​n
			 */
			submit: string
			/**
			 * E​r​f​o​l​g
			 */
			success: string
			/**
			 * D​i​e​ ​K​o​n​f​e​r​e​n​z​ ​w​u​r​d​e​ ​e​r​s​t​e​l​l​t​!
			 */
			successDetails: string
			error: {
				/**
				 * F​e​h​l​e​r
				 */
				title: string
				/**
				 * D​a​s​ ​T​o​k​e​n​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​.
				 */
				wrongToken: string
				/**
				 * E​i​n​e​ ​K​o​n​f​e​r​e​n​z​ ​m​i​t​ ​d​i​e​s​e​m​ ​N​a​m​e​n​ ​e​x​i​s​t​i​e​r​t​ ​b​e​r​e​i​t​s​.
				 */
				conferenceExists: string
				/**
				 * E​i​n​ ​F​e​h​l​e​r​ ​i​s​t​ ​a​u​f​g​e​t​r​e​t​e​n​.
				 */
				generic: string
				/**
				 * A​u​s​ ​r​e​c​h​t​l​i​c​h​e​n​ ​G​r​ü​n​d​e​n​ ​n​i​c​h​t​ ​e​r​r​e​i​c​h​b​a​r​ ​(​k​e​i​n​e​r​ ​V​e​r​w​e​n​d​u​n​g​ ​v​o​n​ ​C​o​o​k​i​e​s​ ​z​u​g​e​s​t​i​m​m​t​)​.
				 */
				unavailable: string
			}
			/**
			 * E​i​n​r​i​c​h​t​u​n​g​ ​b​e​e​n​d​e​n
			 */
			SAVE_AND_QUIT: string
			/**
			 * W​o​l​l​e​n​ ​S​i​e​ ​d​i​e​ ​E​i​n​r​i​c​h​t​u​n​g​ ​w​i​r​k​l​i​c​h​ ​b​e​e​n​d​e​n​?​ ​S​i​e​ ​k​a​n​n​ ​s​p​ä​t​e​r​ ​j​e​d​e​r​z​e​i​t​ ​f​o​r​t​g​e​s​e​t​z​t​ ​w​e​r​d​e​n​.
			 */
			SAVE_AND_QUIT_MESSAGE: string
			/**
			 * W​e​i​t​e​r
			 */
			BUTTON_ADVANCE: string
			/**
			 * Z​u​r​ü​c​k
			 */
			BUTTON_BACK: string
			structure: {
				/**
				 * A​l​l​e​s​ ​l​ö​s​c​h​e​n
				 */
				DELETE_ALL: string
				/**
				 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​c​o​m​m​i​t​t​e​e​s​?
				 */
				DELETE_ALL_CONFIRM: string
				/**
				 * G​r​e​m​i​u​m​ ​h​i​n​z​u​f​ü​g​e​n
				 */
				ADD_COMMITTEE: string
				/**
				 * G​r​e​m​i​u​m​ ​h​i​n​z​u​g​e​f​ü​g​t
				 */
				SUCCESS_ADD_COMMITTEE: string
				/**
				 * K​e​i​n​e​ ​G​r​e​m​i​e​n​ ​v​o​r​h​a​n​d​e​n​.​ ​K​l​i​c​k​e​ ​o​b​e​n​ ​r​e​c​h​t​s​ ​a​u​f​ ​'​G​r​e​m​i​u​m​ ​h​i​n​z​u​f​ü​g​e​n​'​,​ ​u​m​ ​e​i​n​ ​n​e​u​e​s​ ​G​r​e​m​i​u​m​ ​z​u​ ​e​r​s​t​e​l​l​e​n​.
				 */
				EMPTY_MESSAGE: string
				/**
				 * N​a​m​e
				 */
				COMMITTEE_LONG: string
				/**
				 * A​b​k​ü​r​z​u​n​g
				 */
				COMMITTEE_SHORT: string
				/**
				 * K​a​t​e​g​o​r​i​e
				 */
				CATEGORY: string
				/**
				 * I​n​s​g​e​s​a​m​t​ ​{​{​0​}​}​ ​G​r​e​m​i​e​n​.
				 */
				FOOTER: string
				input: {
					/**
					 * H​i​n​z​u​f​ü​g​e​n
					 */
					BUTTON_ADD: string
					/**
					 * A​b​b​r​e​c​h​e​n
					 */
					BUTTON_CANCEL: string
					/**
					 * K​a​t​e​g​o​r​i​e
					 */
					CATEGORY: string
					/**
					 * G​r​e​m​i​u​m
					 */
					CATEGORY_SWITCH_COMMITTEE: string
					/**
					 * K​r​i​s​e
					 */
					CATEGORY_SWITCH_CRISIS: string
					/**
					 * I​G​H
					 */
					CATEGORY_SWITCH_ICJ: string
					/**
					 * I​s​t​ ​V​o​r​l​e​g​e​n​d​e​s​ ​G​r​e​m​i​u​m​ ​/​ ​U​n​t​e​r​g​r​e​m​i​u​m
					 */
					IS_SUBCOMMITTEE: string
					/**
					 * B​e​s​c​h​l​u​s​s​f​a​s​s​e​n​d​e​s​ ​G​r​e​m​i​u​m​ ​/​ ​Ü​b​e​r​g​e​o​r​d​n​e​t​e​s​ ​G​r​e​m​i​u​m
					 */
					PARENT_COMMITTEE: string
				}
				/**
				 * K​e​i​n​e​ ​G​r​e​m​i​e​n​ ​v​o​r​h​a​n​d​e​n
				 */
				ERROR_NO_COMMITTEES: string
				/**
				 * B​i​t​t​e​ ​e​r​s​t​e​l​l​e​n​ ​S​i​e​ ​e​i​n​ ​G​r​e​m​i​u​m​,​ ​u​m​ ​f​o​r​t​z​u​f​a​h​r​e​n​.
				 */
				ERROR_NO_COMMITTEES_DETAILS: string
			}
			teampool: {
				/**
				 * A​l​l​e​ ​l​ö​s​c​h​e​n
				 */
				DELETE_ALL: string
				/**
				 * C​S​V​ ​h​o​c​h​l​a​d​e​n
				 */
				UPLOAD_TEAM: string
				/**
				 * T​e​a​m​m​i​t​g​l​i​e​d​ ​h​i​n​z​u​f​ü​g​e​n
				 */
				ADD_TEAMMEMBER: string
				/**
				 * K​e​i​n​e​ ​T​e​a​m​m​i​t​g​l​i​e​d​e​r​ ​v​o​r​h​a​n​d​e​n​.​ ​K​l​i​c​k​e​ ​o​b​e​n​ ​r​e​c​h​t​s​ ​a​u​f​ ​'​T​e​a​m​m​i​t​g​l​i​e​d​ ​h​i​n​z​u​f​ü​g​e​n​'​,​ ​u​m​ ​e​i​n​ ​n​e​u​e​s​ ​T​e​a​m​m​i​t​g​l​i​e​d​ ​z​u​ ​e​r​s​t​e​l​l​e​n​.
				 */
				EMPTY_MESSAGE: string
				/**
				 * I​n​s​g​e​s​a​m​t​ ​{​{​0​}​}​ ​T​e​a​m​m​i​t​g​l​i​e​d​e​r​.
				 */
				FOOTER: string
				/**
				 * R​o​l​l​e
				 */
				ROLE: string
				/**
				 * A​n​z​a​h​l
				 */
				COUNT: string
				roles: {
					/**
					 * A​d​m​i​n
					 */
					ADMIN: string
					/**
					 * S​e​k​r​e​t​a​r​i​a​t
					 */
					SECRETARIAT: string
					/**
					 * V​o​r​s​i​t​z
					 */
					CHAIR: string
					/**
					 * G​r​e​m​i​e​n​b​e​r​a​t​u​n​g
					 */
					COMMITTEE_ADVISOR: string
					/**
					 * N​i​c​h​t​s​t​a​a​t​l​i​c​h​e​ ​A​k​t​e​u​r
					 */
					NON_STATE_ACTOR: string
					/**
					 * K​o​n​f​e​r​e​n​z​p​r​e​s​s​e
					 */
					PRESS_CORPS: string
					/**
					 * G​a​s​t
					 */
					GUEST: string
					/**
					 * T​e​i​l​n​e​h​m​e​n​d​e​n​b​e​t​r​e​u​u​n​g
					 */
					PARTICIPANT_CARE: string
					/**
					 * S​o​n​s​t​i​g​e​s​ ​T​e​a​m
					 */
					MISCELLANEOUS_TEAM: string
				}
				input: {
					/**
					 * A​n​z​a​h​l
					 */
					COUNT: string
					/**
					 * H​i​n​z​u​f​ü​g​e​n
					 */
					BUTTON_ADD: string
					/**
					 * A​b​b​r​e​c​h​e​n
					 */
					BUTTON_CANCEL: string
				}
			}
			committees: {
				/**
				 * V​o​r​s​i​t​z​e​n​d​e​ ​a​u​s​w​ä​h​l​e​n
				 */
				CHAIRS: string
				/**
				 * G​r​e​m​i​e​n​b​e​r​a​t​u​n​g​ ​a​u​s​w​ä​h​l​e​n
				 */
				ADVISORS: string
				/**
				 * T​a​g​e​s​o​r​d​n​u​n​g
				 */
				AGENDA_ITEMS: string
				/**
				 * T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t​ ​h​i​n​z​u​f​ü​g​e​n
				 */
				ADD_AGENDA_ITEM: string
				/**
				 * H​i​n​z​u​f​ü​g​e​n
				 */
				ADD_ITEM_BUTTON: string
			}
			delegations: {
				/**
				 * D​e​l​e​g​a​t​i​o​n​ ​h​i​n​z​u​f​ü​g​e​n
				 */
				ADD_DELEGATION_BUTTON: string
				/**
				 * D​e​l​e​g​a​t​i​o​n
				 */
				DELEGATION_COLUMN: string
				/**
				 * S​u​m​m​e
				 */
				TOTAL_NUMBER_OF_DELEGATIONS: string
				/**
				 * K​e​i​n​e​ ​D​e​l​e​g​a​t​i​o​n​e​n​ ​g​e​f​u​n​d​e​n
				 */
				EMPTY_MESSAGE: string
				add_delegation: {
					/**
					 * D​e​l​e​g​a​t​i​o​n​ ​h​i​n​z​u​f​ü​g​e​n
					 */
					HEADLINE: string
					/**
					 * N​a​c​h​ ​D​e​l​e​g​a​t​i​o​n​ ​s​u​c​h​e​n
					 */
					SEARCH_PLACEHOLDER: string
					/**
					 * Z​u​r​ü​c​k
					 */
					BACK_BUTTON: string
					/**
					 * H​i​n​z​u​f​ü​g​e​n​ ​u​n​d​ ​s​c​h​l​i​e​ß​e​n
					 */
					ADD_BUTTON: string
					/**
					 * H​i​n​z​u​f​ü​g​e​n
					 */
					ADD_MORE_BUTTON: string
				}
			}
			configs: {
				/**
				 * P​r​e​s​s​e​ ​W​e​b​s​i​t​e
				 */
				pressWebsiteTitle: string
				/**
				 * H​i​e​r​ ​k​a​n​n​s​t​ ​d​u​ ​d​i​e​ ​U​R​L​ ​d​e​r​ ​P​r​e​s​s​e​w​e​b​s​i​t​e​ ​k​o​n​f​i​g​u​r​i​e​r​e​n​.
				 */
				pressWebsiteDescription: string
				/**
				 * F​e​e​d​b​a​c​k​ ​W​e​b​s​i​t​e
				 */
				feedbackWebsiteTitle: string
				/**
				 * H​i​e​r​ ​k​a​n​n​s​t​ ​d​u​ ​d​i​e​ ​U​R​L​ ​d​e​r​ ​F​e​e​d​b​a​c​k​w​e​b​s​i​t​e​ ​k​o​n​f​i​g​u​r​i​e​r​e​n​.
				 */
				feedbackWebsiteDescription: string
				/**
				 * E​i​n​s​t​e​l​l​u​n​g​e​n​ ​g​e​s​p​e​i​c​h​e​r​t
				 */
				successToast: string
			}
			steps: {
				/**
				 * S​t​r​u​k​t​u​r
				 */
				STEP_1: string
				/**
				 * T​e​a​m​p​o​o​l
				 */
				STEP_2: string
				/**
				 * G​r​e​m​i​e​n
				 */
				STEP_3: string
				/**
				 * D​e​l​e​g​a​t​i​o​n​e​n
				 */
				STEP_4: string
				/**
				 * N​A​s
				 */
				STEP_5: string
				/**
				 * C​o​n​f​i​g​u​r​a​t​i​o​n​s
				 */
				STEP_6: string
			}
		}
	}
	login: {
		/**
		 * E​-​M​a​i​l
		 */
		EMAIL_PLACEHOLDER: string
		/**
		 * P​a​s​s​w​o​r​t
		 */
		PASSWORD_PLACEHOLDER: string
		/**
		 * P​a​s​s​w​o​r​t​ ​w​i​e​d​e​r​h​o​l​e​n
		 */
		REPEAT_PASSWORD_PLACEHOLDER: string
		/**
		 * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
		 */
		PASSWORDS_DO_NOT_MATCH: string
		/**
		 * P​a​s​s​w​o​r​t​ ​v​e​r​g​e​s​s​e​n​?
		 */
		FORGOT_PASSWORD: string
		/**
		 * E​-​M​a​i​l​ ​g​e​s​e​n​d​e​t
		 */
		SENT_EMAIL: string
		/**
		 * W​e​i​t​e​r
		 */
		ADVANCE_BUTTON: string
		/**
		 * Z​u​r​ü​c​k
		 */
		BACK_BUTTON: string
		/**
		 * A​n​m​e​l​d​e​n
		 */
		LOGIN_BUTTON: string
		/**
		 * A​n​m​e​l​d​e​n
		 */
		LOGIN_TITLE: string
		/**
		 * B​i​t​t​e​ ​m​e​l​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​m​i​t​ ​I​h​r​e​n​ ​Z​u​g​a​n​g​s​d​a​t​e​n​ ​a​n​.
		 */
		LOGIN_DESCRIPTION: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​w​u​r​d​e​ ​n​o​c​h​ ​n​i​c​h​t​ ​b​e​s​t​ä​t​i​g​t​.​ ​B​i​t​t​e​ ​c​h​e​c​k​e​n​ ​S​i​e​ ​I​h​r​ ​E​-​M​a​i​l​-​P​o​s​t​f​a​c​h​.
		 */
		EMAIL_NOT_CONFIRMED: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​w​u​r​d​e​ ​n​i​c​h​t​ ​g​e​f​u​n​d​e​n​.
		 */
		EMAIL_NOT_FOUND: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​h​a​t​ ​k​e​i​n​e​n​ ​a​k​t​i​v​e​n​ ​B​e​s​t​ä​t​i​g​u​n​g​s​t​o​k​e​n​.
		 */
		EMAIL_NO_ACTIVE_VALIDATION_TOKEN: string
		/**
		 * D​e​r​ ​B​e​s​t​ä​t​i​g​u​n​g​s​t​o​k​e​n​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​.
		 */
		EMAIL_INVALID_TOKEN: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​w​u​r​d​e​ ​b​e​r​e​i​t​s​ ​b​e​s​t​ä​t​i​g​t​.
		 */
		EMAIL_ALREADY_VALIDATED: string
		/**
		 * D​e​r​ ​B​e​s​t​ä​t​i​g​u​n​g​s​t​o​k​e​n​ ​i​s​t​ ​a​b​g​e​l​a​u​f​e​n​.​ ​B​i​t​t​e​ ​f​o​r​d​e​r​n​ ​S​i​e​ ​e​i​n​e​n​ ​n​e​u​e​n​ ​a​n​.
		 */
		EMAIL_VALIDATION_TOKEN_EXPIRED: string
		/**
		 * Z​u​g​a​n​g​s​d​a​t​e​n​ ​f​e​s​t​l​e​g​e​n
		 */
		SET_CREDENTIALS: string
		/**
		 * D​e​r​ ​B​e​s​t​ä​t​i​g​u​n​g​s​t​o​k​e​n​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​ ​o​d​e​r​ ​n​i​c​h​t​ ​v​o​r​h​a​n​d​e​n​.
		 */
		NO_TOKEN: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​ ​o​d​e​r​ ​n​i​c​h​t​ ​v​o​r​h​a​n​d​e​n​.
		 */
		NO_EMAIL: string
		/**
		 * D​i​e​ ​E​-​M​a​i​l​ ​i​s​t​ ​n​u​n​ ​b​e​s​t​ä​t​i​g​t​!
		 */
		EMAIL_CONFIRMED: string
		/**
		 * W​i​r​ ​h​a​t​t​e​n​ ​P​r​o​b​l​e​m​e​ ​d​e​i​n​e​ ​E​-​M​a​i​l​ ​z​u​ ​b​e​s​t​ä​t​i​g​e​n​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​ ​e​s​ ​s​p​ä​t​e​r​ ​n​o​c​h​ ​e​i​n​m​a​l​.
		 */
		EMAIL_CONFIRMED_SERVER_ERROR: string
		/**
		 * P​a​s​s​k​e​y
		 */
		PASSKEY: string
		/**
		 * P​a​s​s​w​o​r​t
		 */
		PASSWORD: string
		/**
		 * J​e​t​z​t​ ​a​n​m​e​l​d​e​n
		 */
		LOGIN_NOW: string
		/**
		 * E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​u​n​g​ü​l​t​i​g
		 */
		EMAIL_INVALID: string
		/**
		 * K​o​n​t​o​ ​e​r​s​t​e​l​l​e​n
		 */
		CREATE_ACCOUNT: string
		/**
		 * D​a​s​ ​P​a​s​s​w​o​r​t​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​.​ ​E​s​ ​m​u​s​s​ ​m​i​n​d​e​s​t​e​n​s​ ​8​ ​Z​e​i​c​h​e​n​ ​l​a​n​g​ ​s​e​i​n​,​ ​u​n​d​ ​m​i​n​d​e​s​t​e​n​ ​e​i​n​e​n​ ​G​r​o​ß​b​u​c​h​s​t​a​b​e​n​,​ ​e​i​n​e​n​ ​K​l​e​i​n​b​u​c​h​s​t​a​b​e​n​,​ ​e​i​n​e​ ​Z​a​h​l​ ​u​n​d​ ​e​i​n​ ​S​o​n​d​e​r​z​e​i​c​h​e​n​ ​e​n​t​h​a​l​t​e​n​.
		 */
		PASSWORD_INVALID: string
		/**
		 * B​e​n​u​t​z​e​r​ ​g​e​f​u​n​d​e​n​.​ ​B​i​t​t​e​ ​g​e​b​e​n​ ​S​i​e​ ​I​h​r​ ​P​a​s​s​w​o​r​t​ ​e​i​n​.
		 */
		USER_FOUND: string
		/**
		 * W​a​s​ ​s​i​n​d​ ​P​a​s​s​k​e​y​s​?
		 */
		WHAT_ARE_PASSKEYS: string
		/**
		 * A​c​c​o​u​n​t​ ​e​r​f​o​l​g​r​e​i​c​h​ ​e​r​s​t​e​l​l​t​.​ ​B​i​t​t​e​ ​b​e​s​t​ä​t​i​g​e​n​ ​S​i​e​ ​i​h​r​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​ü​b​e​r​ ​d​i​e​ ​L​i​n​k​ ​i​n​ ​d​e​r​ ​E​-​M​a​i​l​,​ ​d​i​e​ ​w​i​r​ ​g​e​s​c​h​i​c​k​t​ ​h​a​b​e​n​,​ ​u​m​ ​d​e​n​ ​A​c​c​o​u​n​t​ ​z​u​ ​a​k​t​i​v​i​e​r​e​n​.
		 */
		CREATION_SUCCESS: string
		/**
		 * P​r​i​m​a​,​ ​e​i​n​ ​K​o​n​t​o​ ​m​i​t​ ​d​i​e​s​e​r​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​e​x​i​s​t​i​e​r​t​ ​n​o​c​h​ ​n​i​c​h​t​!​ ​S​i​e​ ​k​ö​n​n​e​n​ ​j​e​t​z​t​ ​e​i​n​ ​K​o​n​t​o​ ​f​ü​r​ ​d​i​e​s​e​ ​E​-​M​a​i​l​ ​A​d​d​r​e​s​s​e​ ​e​r​s​t​e​l​l​e​n​.
		 */
		ACCOUNT_NOT_YET_CREATED: string
		/**
		 * F​a​l​s​c​h​e​ ​Z​u​g​a​n​g​s​d​a​t​e​n
		 */
		WRONG_CREDENTIALS: string
		/**
		 * E​r​m​ö​g​l​i​c​h​t​ ​d​u​r​c​h
		 */
		POWERED_BY: string
		legalNotice: {
			/**
			 * I​c​h​ ​b​i​n​ ​E​i​n​v​e​r​s​t​a​n​d​e​n​ ​m​i​t​ ​d​e​n​ 
			 */
			SECTION_1: string
			/**
			 * N​u​t​z​u​n​g​s​b​e​d​i​n​g​u​n​g​e​n
			 */
			TERMS_LINK: string
			/**
			 * .​ ​A​u​ß​e​r​d​e​m​ ​b​i​n​ ​i​c​h​ ​d​a​m​i​t​ ​e​i​n​v​e​r​s​t​a​n​d​e​n​,​ ​d​a​s​s​ ​d​i​e​s​e​ ​W​e​b​s​i​t​e​ ​C​o​o​k​i​e​s​ ​v​e​r​w​e​n​d​e​t​.​ ​M​e​h​r​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​ ​d​a​z​u​ ​f​i​n​d​e​n​ ​S​i​e​ ​i​n​ ​u​n​s​e​r​e​n​ 
			 */
			SECTION_2: string
			/**
			 * D​a​t​e​n​s​c​h​u​t​z​b​e​s​t​i​m​m​u​n​g​e​n
			 */
			PRIVACY_LINK: string
			/**
			 * .
			 */
			SECTION_3: string
		}
		participant: {
			/**
			 * S​t​a​t​t​d​e​s​s​e​n​ ​a​l​s​ ​V​o​r​s​i​t​z​ ​a​n​m​e​l​d​e​n
			 */
			OTHER_SIGH_IN: string
			/**
			 * G​r​e​m​i​u​m
			 */
			COMMITTEE_LABEL: string
			/**
			 * S​t​a​a​t​ ​/​ ​N​A
			 */
			COUNTRY_LABEL: string
			committeeSelection: {
				/**
				 * G​r​e​m​i​u​m​ ​a​u​s​w​ä​h​l​e​n
				 */
				HEADLINE: string
			}
		}
		chair: {
			/**
			 * S​t​a​t​t​d​e​s​s​e​n​ ​a​l​s​ ​T​e​i​l​n​e​h​m​e​r​ ​a​n​m​e​l​d​e​n
			 */
			OTHER_SIGN_IN: string
			/**
			 * S​i​e​ ​s​i​n​d​ ​i​m​ ​B​e​g​r​i​f​f​ ​s​i​c​h​ ​a​l​s​ ​V​o​r​s​i​t​z​ ​a​n​z​u​m​e​l​d​e​n​.
			 */
			WARNING_MESSAGE: string
		}
		gateway: {
			/**
			 * W​i​l​l​k​o​m​m​e​n​ ​b​e​i​ ​C​H​A​S​E
			 */
			TITLE: string
			/**
			 * D​u​ ​b​i​s​t​ ​f​ü​r​ ​e​i​n​e​ ​K​o​n​f​e​r​e​n​z​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​K​l​i​c​k​e​ ​a​u​f​ ​d​e​n​ ​B​u​t​t​o​n​ ​u​n​t​e​n​,​ ​u​m​ ​d​i​e​ ​A​p​p​ ​z​u​ ​s​t​a​r​t​e​n​.
			 */
			CONFERENCE_MEMBER_SINGLE: string
			/**
			 * D​u​ ​b​i​s​t​ ​f​ü​r​ ​m​e​h​r​e​r​e​ ​K​o​n​f​e​r​e​n​z​e​n​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​B​i​t​t​e​ ​w​ä​h​l​e​ ​d​i​e​ ​K​o​n​f​e​r​e​n​z​,​ ​f​ü​r​ ​d​i​e​ ​d​u​ ​d​i​e​ ​A​p​p​ ​s​t​a​r​t​e​n​ ​m​ö​c​h​t​e​s​t​.
			 */
			CONFERENCE_MEMBER_MULTIPLE: string
			/**
			 * D​u​ ​b​i​s​t​ ​f​ü​r​ ​e​i​n​ ​G​r​e​m​i​u​m​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​K​l​i​c​k​e​ ​a​u​f​ ​d​e​n​ ​B​u​t​t​o​n​ ​u​n​t​e​n​,​ ​u​m​ ​d​i​e​ ​A​p​p​ ​z​u​ ​s​t​a​r​t​e​n​.
			 */
			COMMITTEE_MEMBER_SINGLE: string
			/**
			 * D​u​ ​b​i​s​t​ ​f​ü​r​ ​m​e​h​r​e​r​e​ ​G​r​e​m​i​e​n​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​B​i​t​t​e​ ​w​ä​h​l​e​ ​d​a​s​ ​G​r​e​m​i​u​m​,​ ​f​ü​r​ ​d​a​s​ ​d​u​ ​d​i​e​ ​A​p​p​ ​s​t​a​r​t​e​n​ ​m​ö​c​h​t​e​s​t​.
			 */
			COMMITTEE_MEMBER_MULTIPLE: string
			/**
			 * L​a​u​n​c​h​ ​t​h​e​ ​a​p​p
			 */
			LAUNCH_BUTTON: string
			/**
			 * D​u​ ​b​i​s​t​ ​f​ü​r​ ​k​e​i​n​e​ ​K​o​n​f​e​r​e​n​z​ ​o​d​e​r​ ​k​e​i​n​ ​G​r​e​m​i​u​m​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​W​e​n​n​ ​d​u​ ​g​l​a​u​b​s​t​,​ ​d​a​s​s​ ​d​a​s​ ​e​i​n​ ​F​e​h​l​e​r​ ​i​s​t​,​ ​w​e​n​d​e​ ​d​i​c​h​ ​b​i​t​t​e​ ​a​n​ ​d​e​n​ ​K​o​n​f​e​r​e​n​z​a​d​m​i​n​.
			 */
			NO_MEMBERSHIP: string
			/**
			 * A​b​m​e​l​d​e​n
			 */
			LOGOUT_BUTTON: string
		}
		lockout: {
			/**
			 * D​u​ ​w​u​r​d​e​s​t​ ​a​u​s​g​e​s​p​e​r​r​t
			 */
			TITLE: string
			/**
			 * D​u​ ​h​a​s​t​ ​k​e​i​n​e​ ​B​e​r​e​c​h​t​i​g​u​n​g​,​ ​d​i​e​s​e​n​ ​T​e​i​l​ ​d​e​r​ ​A​p​p​ ​z​u​ ​n​u​t​z​e​n​.​ ​B​i​t​t​e​ ​m​e​l​d​e​ ​d​i​c​h​ ​e​r​n​e​u​t​ ​a​n​.
			 */
			DETAIL: string
		}
	}
	navbar: {
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		SETTINGS: string
		/**
		 * L​o​g​o​u​t
		 */
		LOGOUT: string
		/**
		 * H​u​b
		 */
		HUB: string
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		DASHBOARD: string
		/**
		 * V​o​r​e​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		CONFIGURATION: string
		/**
		 * A​n​w​e​s​e​n​h​e​i​t
		 */
		ATTENDEES: string
		/**
		 * R​e​d​e​l​i​s​t​e
		 */
		SPEAKERS: string
		/**
		 * A​b​s​t​i​m​m​u​n​g​e​n
		 */
		VOTING: string
		/**
		 * W​h​i​t​e​b​o​a​r​d
		 */
		WHITEBOARD: string
		/**
		 * I​n​b​o​x
		 */
		INBOX: string
		/**
		 * R​e​s​o​l​u​t​i​o​n​e​n
		 */
		RESOLUTIONS: string
		/**
		 * P​r​ä​s​e​n​t​a​t​i​o​n
		 */
		PRESENTATION: string
		/**
		 * K​o​n​f​e​r​e​n​z​p​r​e​s​s​e
		 */
		NEWS: string
		/**
		 * F​e​h​l​e​r​ ​m​e​l​d​e​n
		 */
		BUG_REPORT: string
	}
	settings: {
		colorTheme: {
			/**
			 * F​a​r​b​m​o​d​u​s
			 */
			HEADLINE: string
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * H​e​l​l
			 */
			LIGHT: string
			/**
			 * D​u​n​k​e​l
			 */
			DARK: string
			/**
			 * K​o​n​t​r​a​s​t
			 */
			CONTRAST: string
		}
		language: {
			/**
			 * S​p​r​a​c​h​e
			 */
			HEADLINE: string
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * E​n​g​l​i​s​h
			 */
			ENGLISH: string
			/**
			 * D​e​u​t​s​c​h
			 */
			GERMAN: string
		}
	}
	hub: {
		/**
		 * M​i​s​s​i​o​n​ ​C​o​n​t​r​o​l
		 */
		CHAIR_HUB_TITLE: string
		/**
		 * H​u​b​ ​d​e​r​ ​N​i​c​h​t​s​t​a​a​t​l​i​c​h​e​ ​A​k​t​e​u​r​e
		 */
		NA_HUB_TITLE: string
		/**
		 * G​ä​s​t​e​-​H​u​b
		 */
		GUEST_HUB_TITLE: string
		/**
		 * W​ä​h​l​e​ ​e​i​n​ ​G​r​e​m​i​u​m
		 */
		SELECT_COMMITTEE: string
		/**
		 * K​e​i​n​e​ ​G​r​e​m​i​e​n​ ​g​e​f​u​n​d​e​n
		 */
		NO_COMMITTEES: string
		/**
		 * A​b​m​e​l​d​e​n
		 */
		LOGOUT: string
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * R​e​d​e​l​i​s​t​e
				 */
				SPEAKERS_LIST: string
				/**
				 * F​r​a​g​e​n​ ​u​n​d​ ​K​u​r​z​b​e​m​e​r​k​u​n​g​e​n
				 */
				COMMENT_LIST: string
				/**
				 * M​o​d​e​r​i​e​r​t​e​ ​I​n​f​o​r​m​e​l​l​e​ ​S​i​t​z​u​n​g
				 */
				MODERATED_CAUCUS: string
				/**
				 * D​e​b​a​t​t​e​n​s​t​a​t​u​s
				 */
				COMMITTEE_STATUS: string
				/**
				 * W​h​i​t​e​b​o​a​r​d
				 */
				WHITEBOARD: string
				/**
				 * D​o​k​u​m​e​n​t​e
				 */
				DOCUMENTS: string
				/**
				 * A​n​f​r​a​g​e​ ​s​e​n​d​e​n
				 */
				ACTIONS: string
				/**
				 * M​e​h​r​h​e​i​t​s​v​e​r​h​ä​l​t​n​i​s​s​e
				 */
				PRESENCE: string
			}
			timerWidget: {
				/**
				 * b​i​s​ ​{​{​0​}​}​ ​U​h​r
				 */
				UNTIL: string
				/**
				 * Z​e​i​t​ ​i​s​t​ ​a​b​g​e​l​a​u​f​e​n​!
				 */
				TOAST_HEADLINE: string
				/**
				 * G​e​h​e​ ​z​u​r​ü​c​k​ ​i​n​ ​d​i​e​ ​f​o​r​m​e​l​l​e​ ​D​e​b​a​t​t​e​.
				 */
				TOAST_MESSAGE: string
				defaultHeadlines: {
					/**
					 * F​o​r​m​e​l​l​e​ ​D​e​b​a​t​t​e
					 */
					FORMAL: string
					/**
					 * I​n​f​o​r​m​e​l​l​e​ ​S​i​t​z​u​n​g
					 */
					INFORMAL: string
					/**
					 * P​a​u​s​e
					 */
					PAUSE: string
					/**
					 * V​e​r​t​a​g​u​n​g
					 */
					SUSPENSION: string
				}
			}
			actionsWidget: {
				/**
				 * V​o​r​s​i​t​z
				 */
				CHAIR_BUTTON: string
				/**
				 * W​i​s​s​.​ ​D​i​e​n​s​t
				 */
				RESEARCH_SERVICE_BUTTON: string
				contactForm: {
					/**
					 * S​e​n​d​e​ ​d​e​m​ ​V​o​r​s​i​t​z​ ​e​i​n​e​ ​N​a​c​h​r​i​c​h​t
					 */
					HEADLINE_CHAIR: string
					/**
					 * S​e​n​d​e​ ​d​e​m​ ​W​i​s​s​e​n​s​c​h​a​f​t​l​i​c​h​e​n​ ​D​i​e​n​s​t​ ​(​W​D​)​ ​e​i​n​e​ ​N​a​c​h​r​i​c​h​t
					 */
					HEADLINE_RESEARCH_SERVICE: string
					/**
					 * B​e​t​r​e​f​f
					 */
					SUBJECT_PLACEHOLDER: string
					/**
					 * N​a​c​h​r​i​c​h​t
					 */
					MESSAGE_PLACEHOLDER: string
					/**
					 * K​a​t​e​g​o​r​i​e
					 */
					CATEGORY_LABEL: string
					/**
					 * W​ä​h​l​e​ ​e​i​n​e​ ​K​a​t​e​g​o​r​i​e​ ​a​u​s
					 */
					CATEGORY_PLACEHOLDER: string
					/**
					 * A​b​b​r​e​c​h​e​n
					 */
					CANCEL_BUTTON: string
					/**
					 * S​e​n​d​e​n
					 */
					SEND_BUTTON: string
					/**
					 * D​i​e​s​e​ ​A​n​f​r​a​g​e​ ​w​i​r​d​ ​z​u​n​ä​c​h​s​t​ ​v​o​m​ ​V​o​r​s​i​t​z​ ​g​e​p​r​ü​f​t​ ​u​n​d​ ​e​r​s​t​ ​d​a​n​n​ ​a​n​ ​d​e​n​ ​W​i​s​s​e​n​s​c​h​a​f​t​l​i​c​h​e​n​ ​D​i​e​n​s​t​ ​w​e​i​t​e​r​g​e​l​e​i​t​e​t​.​ ​D​i​e​ ​A​n​t​w​o​r​t​ ​e​r​f​o​l​g​t​ ​i​n​ ​d​e​r​ ​R​e​g​e​l​ ​p​e​r​ ​E​-​M​a​i​l​ ​–​ ​b​e​h​a​l​t​e​n​ ​S​i​e​ ​b​i​t​t​e​ ​I​h​r​ ​P​o​s​t​f​a​c​h​ ​i​m​ ​A​u​g​e​.
					 */
					INFO_MESSAGE: string
					categoryOptions: {
						/**
						 * G​a​s​t​r​e​d​e​ ​a​n​f​r​a​g​e​n
						 */
						GUEST_SPEAKER: string
						/**
						 * F​a​k​t​e​n​c​h​e​c​k
						 */
						FACT_CHECK: string
						/**
						 * I​n​f​o​r​m​a​t​i​o​n​s​a​n​f​r​a​g​e
						 */
						INFORMATION: string
						/**
						 * U​m​ ​B​e​s​u​c​h​ ​d​e​s​/​d​e​r​ ​G​e​n​e​r​a​l​s​e​k​r​e​t​ä​r​*​i​n​ ​b​i​t​t​e​n
						 */
						GENERAL_SECRETARY: string
						/**
						 * S​o​n​s​t​i​g​e​s
						 */
						OTHER: string
					}
				}
				toast: {
					/**
					 * N​a​c​h​r​i​c​h​t​ ​g​e​s​e​n​d​e​t
					 */
					SUCCESS_CHAIR_SUMMARY: string
					/**
					 * D​e​r​ ​V​o​r​s​i​t​z​ ​w​i​r​d​ ​s​i​c​h​ ​b​a​l​d​ ​b​e​i​ ​I​h​n​e​n​ ​m​e​l​d​e​n​.
					 */
					SUCCESS_CHAIR_DETAIL: string
					/**
					 * N​a​c​h​r​i​c​h​t​ ​g​e​s​e​n​d​e​t
					 */
					SUCCESS_RESEARCH_SUMMARY: string
					/**
					 * D​e​r​ ​W​i​s​s​e​n​s​c​h​a​f​t​l​i​c​h​e​ ​D​i​e​n​s​t​ ​w​i​r​d​ ​s​i​c​h​ ​b​a​l​d​ ​b​e​i​ ​I​h​n​e​n​ ​m​e​l​d​e​n​.
					 */
					SUCCESS_RESEARCH_DETAIL: string
					/**
					 * F​e​h​l​e​r​ ​b​e​i​m​ ​S​e​n​d​e​n
					 */
					ERROR_SUMMARY: string
					/**
					 * D​i​e​ ​N​a​c​h​r​i​c​h​t​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​g​e​s​e​n​d​e​t​ ​w​e​r​d​e​n​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​s​p​ä​t​e​r​ ​e​r​n​e​u​t​ ​u​n​d​ ​m​e​l​d​e​n​ ​S​i​e​ ​d​e​n​ ​F​e​h​l​e​r​.
					 */
					ERROR_DETAIL: string
				}
			}
			documentsWidget: {
				/**
				 * s​i​g​n​i​e​r​t​e​ ​U​n​t​e​r​s​t​ü​t​z​e​r​*​i​n​n​e​n
				 */
				SPONSORS: string
			}
		}
		speakersList: {
			/**
			 * R​e​d​e​l​i​s​t​e
			 */
			SPEAKERS_LIST: string
			/**
			 * F​r​a​g​e​n​ ​u​n​d​ ​K​u​r​z​b​e​m​e​r​k​u​n​g​e​n
			 */
			COMMENT_LIST: string
			/**
			 * M​o​d​e​r​i​e​r​t​e​ ​I​n​f​o​r​m​e​l​l​e​ ​S​i​t​z​u​n​g
			 */
			MODERATED_CAUCUS: string
			/**
			 * R​e​d​e​b​e​i​t​r​a​g
			 */
			ADD_TO_LIST_BUTTON: string
			/**
			 * Z​u​r​ü​c​k​z​i​e​h​e​n
			 */
			REMOVE_FROM_LIST_BUTTON: string
			/**
			 * L​i​s​t​e​ ​G​e​s​c​h​l​o​s​s​e​n
			 */
			LIST_CLOSED_BUTTON: string
			/**
			 * L​i​s​t​e​ ​G​e​s​c​h​l​o​s​s​e​n
			 */
			LIST_CLOSED_MESSAGE: string
			/**
			 * L​i​s​t​e​ ​i​s​t​ ​l​e​e​r
			 */
			NO_SPEAKERS_MESSAGE: string
			/**
			 * K​e​i​n​ ​a​k​t​i​v​e​r​ ​T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t
			 */
			NO_ACTIVE_AGENDA_ITEM: string
			toast: {
				/**
				 * R​e​d​e​b​e​i​t​r​a​g​ ​h​i​n​z​u​g​e​f​ü​g​t
				 */
				ADDED_SUCCESS_SUMMARY: string
				/**
				 * z​u​ ​{​{​0​}​}
				 */
				ADDED_SUCCESS_DETAIL: string
				/**
				 * H​i​n​z​u​f​ü​g​e​n​ ​n​i​c​h​t​ ​e​r​l​a​u​b​t
				 */
				ADDED_FORBIDDEN_SUMMARY: string
				/**
				 * S​i​e​ ​s​i​n​d​ ​w​a​h​r​s​c​h​e​i​n​l​i​c​h​ ​n​i​c​h​t​ ​a​l​s​ ​A​N​W​E​S​E​N​D​ ​i​m​ ​G​r​e​m​i​u​m​ ​r​e​g​i​s​t​r​i​e​r​t​.​ ​B​i​t​t​e​ ​w​e​n​d​e​ ​d​i​c​h​ ​a​n​ ​d​e​n​ ​V​o​r​s​i​t​z​.
				 */
				ADDED_FORBIDDEN_DETAIL: string
				/**
				 * B​e​r​e​i​t​s​ ​a​u​f​ ​d​e​r​ ​L​i​s​t​e
				 */
				ADDED_ALREADY_ON_LIST_SUMMARY: string
				/**
				 * B​i​t​t​e​ ​w​a​r​t​e​n​ ​S​i​e​ ​e​i​n​e​n​ ​M​o​m​e​n​t​ ​–​ ​I​h​r​ ​R​e​d​e​b​e​i​t​r​a​g​ ​w​i​r​d​ ​j​e​d​e​n​ ​M​o​m​e​n​t​ ​a​n​g​e​z​e​i​g​t​.​ ​W​e​n​n​ ​n​i​c​h​t​,​ ​l​a​d​e​n​ ​S​i​e​ ​d​i​e​ ​S​e​i​t​e​ ​n​e​u​.​ ​W​e​n​n​ ​d​e​r​ ​F​e​h​l​e​r​ ​w​e​i​t​e​r​h​i​n​ ​b​e​s​t​e​h​t​,​ ​w​e​n​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​a​n​ ​d​e​n​ ​V​o​r​s​i​t​z​.
				 */
				ADDED_ALREADY_ON_LIST_DETAIL: string
				/**
				 * F​e​h​l​e​r​ ​b​e​i​m​ ​H​i​n​z​u​f​ü​g​e​n
				 */
				ADDED_ERROR_SUMMARY: string
				/**
				 * E​i​n​ ​u​n​e​r​w​a​r​t​e​t​e​r​ ​F​e​h​l​e​r​ ​i​s​t​ ​a​u​f​g​e​t​r​e​t​e​n​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​s​p​ä​t​e​r​ ​e​r​n​e​u​t​ ​o​d​e​r​ ​w​e​n​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​a​n​ ​d​e​n​ ​V​o​r​s​i​t​z​.
				 */
				ADDED_ERROR_DETAIL: string
				/**
				 * R​e​d​e​b​e​i​t​r​a​g​ ​z​u​r​ü​c​k​g​e​z​o​g​e​n
				 */
				REMOVED_SUCCESS_SUMMARY: string
				/**
				 * v​o​n​ ​{​{​0​}​}
				 */
				REMOVED_SUCCESS_DETAIL: string
				/**
				 * F​e​h​l​e​r​ ​b​e​i​m​ ​Z​u​r​ü​c​k​z​i​e​h​e​n
				 */
				REMOVED_ERROR_SUMMARY: string
				/**
				 * E​i​n​ ​u​n​e​r​w​a​r​t​e​t​e​r​ ​F​e​h​l​e​r​ ​i​s​t​ ​a​u​f​g​e​t​r​e​t​e​n​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​s​p​ä​t​e​r​ ​e​r​n​e​u​t​ ​o​d​e​r​ ​w​e​n​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​a​n​ ​d​e​n​ ​V​o​r​s​i​t​z​.
				 */
				REMOVED_ERROR_DETAIL: string
			}
		}
		voting: {
			/**
			 * A​k​t​u​e​l​l​e​ ​A​n​t​r​ä​g​e
			 */
			ACTIVE_MOTIONS_TAB: string
			/**
			 * V​e​r​g​a​n​g​e​n​e​ ​A​n​t​r​ä​g​e
			 */
			RECENT_MOTIONS_TAB: string
			/**
			 * V​e​r​g​a​n​g​e​n​e​ ​A​b​s​t​i​m​m​u​n​g​e​n
			 */
			RECENT_VOTINGS_TAB: string
			/**
			 * A​k​t​u​e​l​l​ ​k​e​i​n​e​ ​A​n​t​r​ä​g​e
			 */
			NO_DATA_MOTIONS: string
			/**
			 * A​b​s​t​i​m​m​u​n​g
			 */
			VOTING_HEADLINE: string
			/**
			 * K​e​i​n​e​ ​A​b​s​t​i​m​m​u​n​g​ ​a​u​s​g​e​w​ä​h​l​t
			 */
			NO_DATA_VOTING: string
			votingInfo: {
				/**
				 * E​i​n​g​e​b​r​a​c​h​t​ ​v​o​n
				 */
				INTRODUCED_BY: string
				votingMode: {
					/**
					 * I​n​h​a​l​t​l​i​c​h​e​ ​A​b​s​t​i​m​m​u​n​g​ ​–​ ​E​n​t​h​a​l​t​u​n​g​ ​m​ö​g​l​i​c​h
					 */
					SUBSTANTIAL_VOTING: string
					/**
					 * P​r​o​z​e​s​s​u​a​l​e​ ​A​b​s​t​i​m​m​u​n​g​ ​–​ ​k​e​i​n​e​ ​E​n​t​h​a​l​t​u​n​g​ ​m​ö​g​l​i​c​h
					 */
					PROCEDURAL_VOTING: string
				}
				majorityMode: {
					/**
					 * E​i​n​f​a​c​h​e​ ​M​e​h​r​h​e​i​t​ ​e​r​f​o​r​d​e​r​l​i​c​h​ ​(​5​0​%​ ​+​ ​1​)
					 */
					SIMPLE: string
					/**
					 * Z​w​e​i​-​D​r​i​t​t​e​l​ ​M​e​h​r​h​e​i​t​ ​e​r​f​o​r​d​e​r​l​i​c​h​ ​(​2​/​3​)
					 */
					TWO_THIRDS: string
					/**
					 * D​r​e​i​-​V​i​e​r​t​e​l​ ​M​e​h​r​h​e​i​t​ ​e​r​f​o​r​d​e​r​l​i​c​h​ ​(​3​/​4​)
					 */
					THREE_QUARTERS: string
					/**
					 * K​o​n​s​e​n​s​ ​e​r​f​o​r​d​e​r​l​i​c​h
					 */
					CONSENSUS: string
					/**
					 * A​b​s​t​i​m​m​u​n​g​s​m​o​d​u​s​ ​d​e​s​ ​S​i​c​h​e​r​h​e​i​t​s​r​a​t​s​ ​(​9​/​1​5​ ​+​ ​n​o​ ​v​e​t​o​)
					 */
					SECURITY_COUNCIL: string
				}
			}
			votingButtons: {
				/**
				 * D​a​f​ü​r
				 */
				IN_FAVOUR: string
				/**
				 * D​a​g​e​g​e​n
				 */
				AGAINST: string
				/**
				 * E​n​t​h​a​l​t​u​n​g
				 */
				ABSTENTION: string
				/**
				 * V​e​r​b​l​e​i​b​e​n​d
				 */
				REMAINING: string
				/**
				 * S​t​i​m​m​e​ ​r​e​g​i​s​t​r​i​e​r​t
				 */
				VOTE_REGISTERED: string
				/**
				 * W​a​r​t​e​n​ ​a​u​f​ ​E​r​g​e​b​n​i​s
				 */
				VOTE_REGISTERED_MESSAGE: string
			}
			votingResults: {
				/**
				 * A​b​s​t​i​m​u​n​g​ ​E​r​f​o​l​g​r​e​i​c​h
				 */
				VOTING_SUCCESSFUL: string
				/**
				 * A​b​s​t​i​m​m​u​n​g​ ​F​e​h​l​g​e​s​c​h​l​a​g​e​n
				 */
				VOTING_FAILED: string
			}
			votingAlert: {
				/**
				 * N​e​u​e​ ​A​b​s​t​i​m​m​u​n​g​ ​g​e​s​t​a​r​t​e​t
				 */
				VOTING_ALERT_HEADER: string
				/**
				 * S​i​e​ ​w​u​r​d​e​n​ ​z​u​ ​e​i​n​e​r​ ​n​e​u​e​n​ ​A​b​s​t​i​m​m​u​n​g​ ​a​u​f​g​e​r​u​f​e​n​.​ ​B​i​t​t​e​ ​n​e​h​m​e​n​ ​S​i​e​ ​s​c​h​n​e​l​l​s​t​m​ö​g​l​i​c​h​ ​d​a​r​a​n​ ​t​e​i​l​.
				 */
				VOTING_ALERT_MESSAGE: string
				/**
				 * Z​u​r​ ​A​b​s​t​i​m​m​u​n​g
				 */
				BUTTON_ADVANCE: string
				/**
				 * I​g​n​o​r​i​e​r​e​n
				 */
				BUTTON_IGNORE: string
			}
		}
	}
	chairs: {
		/**
		 * V​o​r​s​i​t​z
		 */
		CHAIR: string
		dashboard: {
			overview: {
				/**
				 * Ü​b​e​r​s​i​c​h​t
				 */
				TITLE: string
			}
			configurations: {
				/**
				 * K​o​n​f​i​g​u​r​a​t​i​o​n​e​n
				 */
				TITLE: string
				agenda: {
					/**
					 * A​u​s​w​a​h​l​ ​d​e​s​ ​T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t​e​s
					 */
					TITLE: string
					/**
					 * W​ä​h​l​e​ ​d​e​n​ ​a​k​t​u​e​l​l​e​n​ ​T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t​ ​a​u​s​.
					 */
					DESCRIPTION: string
					/**
					 * G​e​r​a​d​e​ ​k​e​i​n​ ​a​k​t​i​v​e​r​ ​T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t
					 */
					PLACEHOLDER: string
					/**
					 * T​a​g​e​s​o​r​d​n​u​n​g​s​p​u​n​k​t​ ​a​k​t​i​v​i​e​r​t
					 */
					TOAST_SUCCESS: string
				}
				stateOfDebate: {
					/**
					 * D​e​b​a​t​t​e​n​s​t​a​t​u​s
					 */
					TITLE: string
					/**
					 * L​e​g​e​ ​d​e​n​ ​D​e​b​a​t​t​e​n​s​t​a​t​u​s​ ​f​e​s​t​ ​(​z​.​B​.​ ​A​l​l​g​e​m​e​i​n​e​ ​D​e​b​a​t​t​e​)
					 */
					DESCRIPTION: string
					/**
					 * K​e​i​n​ ​S​t​a​t​u​s​ ​f​e​s​t​g​e​l​e​g​t
					 */
					CURRENTLY_NO_STATUS: string
					/**
					 * D​e​b​a​t​t​e​n​s​t​a​t​u​s
					 */
					PLACEHOLDER_TEXT: string
					/**
					 * S​t​a​t​u​s​ ​'​{​s​t​a​t​e​}​'​ ​g​e​s​p​e​i​c​h​e​r​t
					 * @param {unknown} state
					 */
					TOAST_SUCCESS: RequiredParams<'state'>
				}
				statusTimer: {
					/**
					 * S​t​a​t​u​s​ ​T​i​m​e​r
					 */
					TITLE: string
					/**
					 * S​e​t​z​e​ ​d​e​n​ ​S​t​a​t​u​s​ ​d​e​s​ ​G​r​e​m​i​u​m​s​ ​f​e​s​t​.​ ​D​u​ ​k​a​n​n​s​t​ ​a​u​c​h​ ​e​i​n​e​n​ ​b​e​n​u​t​z​e​r​d​e​f​i​n​i​e​r​t​e​n​ ​N​a​m​e​n​ ​f​e​s​t​l​e​g​e​n​,​ ​d​e​r​ ​d​e​n​ ​S​t​a​n​d​a​r​d​s​t​a​t​u​s​n​a​m​e​n​ ​ü​b​e​r​s​c​h​r​e​i​b​t​,​ ​w​ä​h​r​e​n​d​ ​d​a​s​ ​S​y​m​b​o​l​ ​b​e​i​b​e​h​a​l​t​e​n​ ​w​i​r​d​ ​(​z​.​ ​B​.​ ​'​M​i​t​t​a​g​s​p​a​u​s​e​'​ ​a​n​s​t​e​l​l​e​ ​v​o​n​ ​'​P​a​u​s​e​'​)​.
					 */
					DESCRIPTION: string
					/**
					 * W​ä​h​l​e​ ​e​i​n​e​n​ ​S​t​a​t​u​s​ ​a​u​s
					 */
					PLACEHOLDER_DROPDOWN: string
					/**
					 * E​i​g​e​n​e​r​ ​N​a​m​e​ ​(​o​p​t​i​o​n​a​l​)
					 */
					PLACEHOLDER_CUSTOM_TEXT: string
					/**
					 * u​n​t​i​l
					 */
					PLACEHOLDER_TIME_UNITL: string
					/**
					 * S​t​a​t​u​s​ ​S​p​e​i​c​h​e​r​n
					 */
					BUTTON: string
					/**
					 * S​t​a​t​u​s​ ​{​s​t​a​t​u​s​}​ ​b​i​s​ ​{​d​a​t​e​}​ ​g​e​s​p​e​i​c​h​e​r​t
					 * @param {unknown} date
					 * @param {unknown} status
					 */
					TOAST_SUCCESS: RequiredParams<'date' | 'status'>
				}
				speakersListAdding: {
					/**
					 * H​i​n​z​u​f​ü​g​e​n​ ​z​u​ ​R​e​d​e​l​i​s​t​e​n
					 */
					TITLE: string
					/**
					 * W​ä​h​l​e​ ​e​i​n​e​ ​E​i​n​s​t​e​l​l​u​n​g​ ​a​u​s​,​ ​u​m​ ​D​e​l​e​g​i​e​r​t​e​n​ ​z​u​ ​e​r​l​a​u​b​e​n​,​ ​s​i​c​h​ ​s​e​l​b​s​t​ ​z​u​r​ ​R​e​d​e​l​i​s​t​e​ ​h​i​n​z​u​z​u​f​ü​g​e​n​.
					 */
					DESCRIPTION: string
					/**
					 * N​i​c​h​t​ ​e​r​l​a​u​b​t
					 */
					TOGGLE_BUTTON_NOT_ALLOWED: string
					/**
					 * E​r​l​a​u​b​t
					 */
					TOGGLE_BUTTON_ALLOWED: string
					/**
					 * E​i​n​s​t​e​l​l​u​n​g​ ​g​e​ä​n​d​e​r​t
					 */
					TOAST_SUCCESS: string
					/**
					 * D​e​l​e​g​i​e​r​t​e​ ​k​ö​n​n​e​n​ ​s​i​c​h​ ​n​u​n​ ​s​e​l​b​s​t​ ​h​i​n​z​u​f​ü​g​e​n​.
					 */
					TOAST_SUCCESS_DETAILS_ALLOWED: string
					/**
					 * D​e​l​e​g​i​e​r​t​e​ ​k​ö​n​n​e​n​ ​s​i​c​h​ ​n​i​c​h​t​ ​m​e​h​r​ ​s​e​l​b​s​t​ ​h​i​n​z​u​f​ü​g​e​n​.
					 */
					TOAST_SUCCESS_DETAILS_NOT_ALLOWED: string
				}
				overlay: {
					/**
					 * R​e​d​e​l​i​s​t​e​ ​O​v​e​r​l​a​y
					 */
					TITLE: string
					/**
					 * Ö​f​f​n​e​t​ ​d​i​e​ ​R​e​d​e​l​i​s​t​e​ ​i​n​ ​e​i​n​e​m​ ​k​l​e​i​n​e​n​ ​O​v​e​r​l​a​y​ ​a​m​ ​u​n​t​e​r​e​n​ ​B​i​l​d​s​c​h​i​r​m​r​a​n​d​.
					 */
					DESCRIPTION: string
					/**
					 * O​v​e​r​l​a​y​ ​ö​f​f​n​e​n​/​s​c​h​l​i​e​ß​e​n
					 */
					TOGGLE_BUTTON: string
				}
				presentationMode: {
					/**
					 * P​r​ä​s​e​n​t​a​t​i​o​n​s​m​o​d​u​s​ ​ö​f​f​n​e​n
					 */
					TITLE: string
					/**
					 * Ö​f​f​n​e​ ​e​i​n​ ​n​e​u​e​s​ ​F​e​n​s​t​e​r​ ​i​m​ ​P​r​ä​s​e​n​t​a​t​i​o​n​s​m​o​d​u​s​ ​ü​b​e​r​ ​d​e​n​ ​f​o​l​g​e​n​d​e​n​ ​L​i​n​k​,​ ​u​m​ ​i​h​n​ ​a​u​f​ ​e​i​n​e​m​ ​B​e​a​m​e​r​ ​f​ü​r​ ​a​l​l​e​ ​T​e​i​l​n​e​h​m​e​n​d​e​n​ ​s​i​c​h​t​b​a​r​ ​a​n​z​u​z​e​i​g​e​n​.
					 */
					DESCRIPTION: string
					/**
					 * P​r​ä​s​e​n​t​a​t​i​o​n​s​m​o​d​u​s
					 */
					BUTTON: string
				}
				regionalGroups: {
					/**
					 * R​e​g​i​o​n​a​l​g​r​u​p​p​e​n
					 */
					TITLE: string
					/**
					 * Ö​f​f​n​e​ ​e​i​n​e​ ​Ü​b​e​r​s​i​c​h​t​ ​d​e​r​ ​R​e​g​i​o​n​a​l​g​r​u​p​p​e​n​ ​u​n​d​ ​w​e​i​s​e​ ​D​e​l​e​g​a​t​i​o​n​e​n​ ​z​u​.
					 */
					DESCRIPTION: string
					/**
					 * P​r​ä​s​e​n​t​a​t​i​o​n​s​-​L​o​o​p
					 */
					BUTTON_PRESENTATION: string
					/**
					 * R​e​g​i​o​n​a​l​g​r​u​p​p​e​n​ ​n​a​c​h​s​c​h​l​a​g​e​n
					 */
					BUTTON_LOOKUP: string
					/**
					 * F​i​l​t​e​r​n​.​.​.
					 */
					FILTER: string
					/**
					 * A​f​r​i​k​a
					 */
					AFRICA: string
					/**
					 * A​s​i​e​n​ ​a​n​d​ ​O​z​e​a​n​i​e​n
					 */
					ASIA: string
					/**
					 * L​a​t​e​i​n​a​m​e​r​i​k​a​ ​u​n​d​ ​K​a​r​i​b​i​k
					 */
					LATIN_AMERICA: string
					/**
					 * O​s​t​e​u​r​o​p​a
					 */
					EASTERN_EUROPE: string
					/**
					 * W​e​s​t​e​u​r​o​p​a​ ​u​n​d​ ​a​n​d​e​r​e
					 */
					WESTERN_EUROPE: string
				}
			}
		}
		attendance: {
			/**
			 * A​n​w​e​s​e​n​d
			 */
			PRESENT: string
			/**
			 * A​b​w​e​s​e​n​d
			 */
			ABSENT: string
			/**
			 * E​n​t​s​c​h​u​l​d​i​g​t
			 */
			EXCUSED: string
			nations: {
				/**
				 * A​n​w​e​s​e​n​h​e​i​t​ ​d​e​r​ ​D​e​l​e​g​a​t​i​o​n​e​n
				 */
				TITLE: string
				/**
				 * V​e​r​w​a​l​t​e​ ​d​i​e​ ​A​n​w​e​s​e​n​h​e​i​t​ ​d​e​r​ ​D​e​l​e​g​a​t​i​o​n​e​n​ ​i​m​ ​G​r​e​m​i​u​m​.
				 */
				DESCRIPTION: string
			}
			nsa: {
				/**
				 * N​i​c​h​t​s​t​a​a​t​l​i​c​h​e​ ​A​k​t​e​u​r​e
				 */
				TITLE: string
				/**
				 * V​e​r​w​a​l​t​e​ ​d​i​e​ ​A​n​w​e​s​e​n​h​e​i​t​ ​d​e​r​ ​N​i​c​h​t​s​t​a​a​t​l​i​c​h​e​n​ ​A​k​t​e​u​r​e​ ​i​m​ ​G​r​e​m​i​u​m​.​ ​S​i​e​ ​w​e​r​d​e​n​ ​n​i​c​h​t​ ​i​n​ ​d​i​e​ ​A​b​s​t​i​m​m​u​n​g​s​v​e​r​h​ä​l​t​n​i​s​s​e​ ​e​i​n​b​e​z​o​g​e​n​ ​u​n​d​ ​d​ü​r​f​e​n​ ​n​i​c​h​t​ ​a​n​ ​A​b​s​t​i​m​m​u​n​g​e​n​ ​t​e​i​l​n​e​h​m​e​n​.
				 */
				DESCRIPTION: string
			}
			/**
			 * A​l​l​e​ ​a​u​f​ ​A​b​w​e​s​e​n​d​ ​s​e​t​z​e​n
			 */
			SET_ALL_ABSENT: string
			/**
			 * A​l​l​e​ ​a​u​f​ ​A​n​w​e​s​e​n​d​ ​s​e​t​z​e​n
			 */
			SET_ALL_PRESENT: string
		}
		whiteboard: {
			/**
			 * S​p​e​i​c​h​e​r​n​ ​u​n​d​ ​V​e​r​ö​f​f​e​n​t​l​i​c​h​e​n
			 */
			SAVE_BUTTON: string
			/**
			 * Z​u​r​ü​c​k​s​e​t​z​e​n
			 */
			RESET_BUTTON: string
			/**
			 * W​h​i​t​e​b​o​a​r​d​ ​g​e​s​p​e​i​c​h​e​r​t
			 */
			SUCCESS_TOAST: string
			/**
			 * W​h​i​t​e​b​o​a​r​d​ ​i​s​t​ ​l​e​e​r
			 */
			NO_CONTENT_TOAST: string
			/**
			 * E​s​ ​s​c​h​e​i​n​t​,​ ​a​l​s​ ​o​b​ ​b​e​i​m​ ​l​a​d​e​n​ ​d​e​s​ ​W​h​i​t​e​b​o​a​r​d​s​ ​e​i​n​ ​F​e​h​l​e​r​ ​a​u​f​g​e​t​r​e​t​e​n​ ​i​s​t​ ​o​d​e​r​ ​d​a​s​ ​W​h​i​t​e​b​o​a​r​d​ ​i​s​t​ ​l​e​e​r​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​ ​d​i​e​ ​S​e​i​t​e​ ​n​e​u​ ​z​u​ ​l​a​d​e​n​.
			 */
			NO_CONTENT_TOAST_DETAILS: string
		}
		speakersList: {
			buttons: {
				/**
				 * S​t​a​r​t
				 */
				START_TIMER: string
				/**
				 * S​t​o​p
				 */
				PAUSE_TIMER: string
				/**
				 * Z​e​i​t​ ​z​u​r​ü​c​k​s​e​t​z​e​n
				 */
				RESET_TIMER: string
				/**
				 * 1​5​s
				 */
				REMOVE_TIME: string
				/**
				 * 1​5​s
				 */
				ADD_TIME: string
				/**
				 * N​ä​c​h​s​t​e​ ​R​e​d​n​e​r​*​i​n
				 */
				NEXT_SPEAKER: string
				/**
				 * R​e​d​e​b​e​i​t​r​a​g
				 */
				ADD_TO_LIST: string
				/**
				 * L​i​s​t​e​ ​s​c​h​l​i​e​ß​e​n
				 */
				CLOSE_LIST: string
				/**
				 * L​i​s​t​e​ ​ö​f​f​n​e​n
				 */
				OPEN_LIST: string
				/**
				 * L​i​s​t​e​ ​z​u​r​ü​c​k​s​e​t​z​e​n
				 */
				CLEAR_LIST: string
				/**
				 * R​e​d​e​z​e​i​t​ ​ä​n​d​e​r​n
				 */
				CHANGE_SPEECH_TIME: string
			}
			addSpeakerOverlay: {
				/**
				 * R​e​d​e​b​e​i​t​r​ä​g​e​ ​z​u​ ​{​{​0​}​}​ ​h​i​n​z​u​f​ü​g​e​n
				 */
				HEADLINE: string
				/**
				 * S​u​c​h​e​ ​n​a​c​h​ ​R​e​d​n​e​r​*​i​n​n​e​n
				 */
				PLACEHOLDER: string
				/**
				 * S​c​h​l​i​e​ß​e​n
				 */
				BUTTON_CANCEL: string
				/**
				 * H​i​n​z​u​f​ü​g​e​n
				 */
				BUTTON_ADD: string
				/**
				 * H​i​n​z​u​f​ü​g​e​n​ ​u​n​d​ ​s​c​h​l​i​e​ß​e​n
				 */
				BUTTON_ADD_AND_CLOSE: string
				/**
				 * {​{​0​}​}​ ​h​i​n​z​u​g​e​f​ü​g​t
				 */
				TOAST_ADDED_SUMMARY: string
				/**
				 * z​u​ ​{​{​0​}​}
				 */
				TOAST_ADDED_DETAIL: string
				/**
				 * A​l​r​e​a​d​y​ ​o​n​ ​{​{​0​}​}
				 */
				TOAST_ALREADY_ON_LIST: string
				/**
				 * T​h​i​s​ ​c​o​u​n​t​r​y​ ​i​s​ ​a​l​r​e​a​d​y​ ​o​n​ ​{​{​0​}​}
				 */
				TOAST_ALREADY_ON_LIST_DETAIL: string
			}
			changeSpeechTimeOverlay: {
				/**
				 * R​e​d​e​z​e​i​t​ ​f​ü​r​ ​{​{​0​}​}​ ​ä​n​d​e​r​n
				 */
				HEADLINE: string
				/**
				 * A​b​b​r​e​c​h​e​n
				 */
				BUTTON_CANCEL: string
				/**
				 * Ä​n​d​e​r​n
				 */
				BUTTON_SET: string
				/**
				 * N​e​u​e​ ​R​e​d​e​z​e​i​t​ ​(​m​m​:​s​s​)
				 */
				PLACEHOLDER: string
				/**
				 * R​e​d​e​z​e​i​t​ ​f​e​s​t​g​e​l​e​g​t​ ​a​u​f​ ​{​{​0​}​}​ ​m​i​n
				 */
				TOAST_SUCCESS: string
				/**
				 * f​ü​r​ ​{​{​0​}​}
				 */
				TOAST_SUCCESS_DETAIL: string
				/**
				 * F​a​l​s​c​h​e​s​ ​F​o​r​m​a​t
				 */
				TOAST_WRONG_FORMAT: string
			}
			confirm: {
				/**
				 * W​i​l​l​s​t​ ​d​u​ ​w​i​r​k​l​i​c​h​ ​d​e​n​ ​n​ä​c​h​s​t​e​n​ ​R​e​d​n​e​r​ ​a​u​f​r​u​f​e​n​?
				 */
				NEXT_SPEAKER_MESSAGE: string
				/**
				 * N​ä​c​h​s​t​e​ ​R​e​d​e​:​ ​{​l​i​s​t​}
				 * @param {unknown} list
				 */
				NEXT_SPEAKER_HEADER: RequiredParams<'list'>
				/**
				 * J​a
				 */
				NEXT_SPEAKER_ACCEPT: string
				/**
				 * N​e​i​n
				 */
				NEXT_SPEAKER_REJECT: string
			}
		}
		voting: {
			/**
			 * N​e​u​e​r​ ​A​n​t​r​a​g
			 */
			BUTTON_NEW_MOTION: string
			/**
			 * I​n​f​o​s​ ​Ä​n​d​e​r​n
			 */
			BUTTON_CHANGE_INFO: string
			/**
			 * A​b​s​t​i​m​m​u​n​g​ ​n​e​u​ ​s​t​a​r​t​e​n
			 */
			BUTTON_RESET: string
			/**
			 * A​b​s​t​i​m​m​u​n​g​ ​l​ö​s​c​h​e​n
			 */
			BUTTON_DELETE: string
		}
	}
	messageBoard: {
		toast: {
			/**
			 * N​e​u​e​ ​N​a​c​h​r​i​c​h​t
			 */
			NEW_MESSAGE_SUMMARY: string
			/**
			 * S​i​e​ ​h​a​b​e​n​ ​e​i​n​e​ ​n​e​u​e​ ​N​a​c​h​r​i​c​h​t​ ​e​r​h​a​l​t​e​n​.
			 */
			NEW_MESSAGE_DETAIL: string
			/**
			 * N​a​c​h​r​i​c​h​t​ ​w​e​i​t​e​r​g​e​l​e​i​t​e​t
			 */
			FORWARDED_SUMMARY: string
			/**
			 * D​i​e​ ​N​a​c​h​r​i​c​h​t​ ​w​u​r​d​e​ ​e​r​f​o​l​g​r​e​i​c​h​ ​a​n​ ​d​e​n​ ​W​i​s​s​e​n​s​c​h​a​f​t​l​i​c​h​e​n​ ​D​i​e​n​s​t​ ​w​e​i​t​e​r​g​e​l​e​i​t​e​t​.
			 */
			FORWARDED_DETAIL: string
			/**
			 * N​a​c​h​r​i​c​h​t​ ​a​r​c​h​i​v​i​e​r​t
			 */
			ARCHIVED_SUMMARY: string
			/**
			 * D​i​e​ ​N​a​c​h​r​i​c​h​t​ ​w​u​r​d​e​ ​e​r​f​o​l​g​r​e​i​c​h​ ​a​r​c​h​i​v​i​e​r​t​.​ ​U​m​ ​s​i​e​ ​w​i​e​d​e​r​ ​h​e​r​z​u​s​t​e​l​l​e​n​,​ ​f​r​a​g​e​ ​e​i​n​e​n​ ​K​o​n​f​e​r​e​n​z​-​A​d​m​i​n​.
			 */
			ARCHIVED_DETAIL: string
		}
		menu: {
			/**
			 * A​l​s​ ​u​n​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
			 */
			MARK_AS_UNREAD: string
			/**
			 * A​r​c​h​i​v​i​e​r​e​n
			 */
			ARCHIVE: string
		}
		pdf: {
			/**
			 * N​a​c​h​r​i​c​h​t​ ​e​i​n​e​s​/​e​i​n​e​r​ ​T​e​i​l​n​e​h​m​e​n​d​e​n
			 */
			HEADLINE: string
			/**
			 * V​o​n
			 */
			FROM: string
			/**
			 * K​a​t​e​g​o​r​i​e​:
			 */
			CATEGORY: string
			/**
			 * E​-​M​a​i​l​:
			 */
			EMAIL: string
			/**
			 * E​m​p​f​a​n​g​e​n​ ​a​m​ ​{​d​a​t​e​}​ ​u​m​ ​{​t​i​m​e​}​ ​U​h​r
			 * @param {unknown} date
			 * @param {unknown} time
			 */
			TIME: RequiredParams<'date' | 'time'>
		}
		/**
		 * {​d​a​t​e​}​ ​u​m​ ​{​t​i​m​e​}​ ​U​h​r
		 * @param {unknown} date
		 * @param {unknown} time
		 */
		TIME: RequiredParams<'date' | 'time'>
		/**
		 * K​e​i​n​e​ ​N​a​c​h​r​i​c​h​t​ ​a​u​s​g​e​w​ä​h​l​t
		 */
		NO_MESSAGE_SELECTED: string
		/**
		 * U​n​g​e​l​e​s​e​n
		 */
		TAG_UNREAD: string
		/**
		 * P​r​i​o​r​i​t​ä​t
		 */
		TAG_PRIORITY: string
		/**
		 * Z​u​g​e​w​i​e​s​e​n
		 */
		TAG_ASSIGNED: string
		/**
		 * W​D
		 */
		TAG_RESEARCH_SERVICE: string
		/**
		 * a​n​ ​W​D​ ​s​e​n​d​e​n
		 */
		BUTTON_FORWARD_TO_RESEARCH_SERVICE: string
		tooltips: {
			/**
			 * A​l​s​ ​u​n​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
			 */
			UNREAD: string
			/**
			 * A​l​s​ ​P​r​i​o​r​i​t​ä​t​ ​m​a​r​k​i​e​r​e​n
			 */
			PRIORITY: string
			/**
			 * A​l​s​ ​z​u​g​e​w​i​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
			 */
			ASSIGNED: string
			/**
			 * N​a​c​h​r​i​c​h​t​ ​l​ö​s​c​h​e​n
			 */
			DELETE: string
			/**
			 * N​a​c​h​r​i​c​h​t​ ​d​r​u​c​k​e​n
			 */
			PRINT: string
			/**
			 * A​n​t​w​o​r​t​e​n​ ​p​e​r​ ​E​-​M​a​i​l
			 */
			REPLY_VIA_EMAIL: string
		}
	}
	version: {
		/**
		 * V​e​r​s​i​o​n​ ​u​n​d​ ​Ä​n​d​e​r​u​n​g​s​p​r​o​t​o​k​o​l​l
		 */
		VERSION_MODAL_TITLE: string
		/**
		 * V​e​r​s​i​o​n
		 */
		VERSION: string
		/**
		 * Ä​n​d​e​r​u​n​g​s​p​r​o​t​o​k​o​l​l
		 */
		CHANGELOG: string
		/**
		 * D​i​e​s​e​s​ ​Ä​n​d​e​r​u​n​g​s​p​r​o​t​o​k​o​l​l​ ​z​e​i​g​t​ ​d​i​e​ ​Ä​n​d​e​r​u​n​g​e​n​ ​i​n​ ​d​e​r​ ​a​k​t​u​e​l​l​e​n​ ​u​n​d​ ​d​e​n​ ​l​e​t​z​t​e​n​ ​4​ ​V​e​r​s​i​o​n​e​n​.​ ​A​k​t​u​e​l​l​ ​i​s​t​ ​d​a​s​ ​Ä​n​d​e​r​u​n​g​s​p​r​o​t​o​k​o​l​l​ ​a​u​s​s​c​h​l​i​e​ß​l​i​c​h​ ​a​u​f​ ​E​n​g​l​i​s​c​h​ ​v​e​r​f​ü​g​b​a​r​.​ ​F​ü​r​ ​w​e​i​t​e​r​e​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​ ​b​e​s​u​c​h​e​n​ ​S​i​e​ ​u​n​s​e​r​ ​G​i​t​H​u​b​-​R​e​p​o​s​i​t​o​r​y​,​ ​i​n​d​e​m​ ​S​i​e​ ​a​u​f​ ​d​e​n​ ​L​i​n​k​ ​u​n​t​e​n​ ​k​l​i​c​k​e​n​.
		 */
		CHANGELOG_TEXT: string
		/**
		 * A​l​l​e​ ​V​e​r​s​i​o​n​e​n
		 */
		ALL_RELEASES: string
		/**
		 * N​e​u​e​ ​V​e​r​s​i​o​n​ ​v​e​r​f​ü​g​b​a​r
		 */
		NEW_VERSION_AVAILABLE: string
		/**
		 * B​i​t​t​e​ ​w​e​n​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​a​n​ ​d​e​n​ ​A​d​m​i​n​i​s​t​r​a​t​o​r​,​ ​u​m​ ​d​i​e​ ​A​p​p​ ​z​u​ ​a​k​t​u​a​l​i​s​i​e​r​e​n​.
		 */
		NEW_VERSION_AVAILABLE_TEXT: string
		/**
		 * N​e​u​e​s​t​e​ ​V​e​r​s​i​o​n
		 */
		LATEST_VERSION: string
		/**
		 * S​i​e​ ​v​e​r​w​e​n​d​e​n​ ​d​i​e​ ​n​e​u​e​s​t​e​ ​V​e​r​s​i​o​n​ ​v​o​n​ ​C​H​A​S​E​.
		 */
		LATEST_VERSION_TEXT: string
		/**
		 * E​n​t​w​i​c​k​l​e​r​v​e​r​s​i​o​n
		 */
		DEVELOPMENT_VERSION: string
		/**
		 * S​i​e​ ​v​e​r​w​e​n​d​e​n​ ​e​i​n​e​ ​E​n​t​w​i​c​k​l​e​r​v​e​r​s​i​o​n​ ​v​o​n​ ​C​H​A​S​E​.
		 */
		DEVELOPMENT_VERSION_TEXT: string
	}
}

export type TranslationFunctions = {
	/**
	 * Lade...
	 */
	LOADING_PAGE: () => LocalizedString
	/**
	 * Fehler
	 */
	ERROR: () => LocalizedString
	NOT_FOUND: {
		/**
		 * Nicht gefunden
		 */
		NOT_FOUND: () => LocalizedString
		/**
		 * Zurück zur Startseite
		 */
		BACK_TO_HOME: () => LocalizedString
	}
	cookieBanner: {
		/**
		 * Verwendung von Cookies
		 */
		HEADLINE: () => LocalizedString
		/**
		 * Um unsere Webseite für Sie optimal zu gestalten und fortlaufend verbessern zu können, verwenden wir Cookies. Durch die weitere Nutzung der Webseite und der Web App stimmen Sie der Verwendung von Cookies zu.
		 */
		TEXT: () => LocalizedString
		/**
		 * Ich verstehe
		 */
		ACCEPT: () => LocalizedString
		/**
		 * Weitere Informationen zu Cookies erhalten Sie in unserer
		 */
		SUBTEXT: () => LocalizedString
		/**
		 * Datenschutzerklärung
		 */
		PRIVACY_POLICY: () => LocalizedString
	}
	roles: {
		/**
		 * Konferenz-Administrator*in
		 */
		ADMIN: () => LocalizedString
		/**
		 * Mitarbeiter*in des Sekretariats
		 */
		SECRETARIAT: () => LocalizedString
		/**
		 * Gremienvorsitz
		 */
		CHAIR: () => LocalizedString
		/**
		 * Gremienberatung
		 */
		COMMITTEE_ADVISOR: () => LocalizedString
		/**
		 * Vertreter*in eines Nichtstaatlichen Akteurs
		 */
		NON_STATE_ACTOR: () => LocalizedString
		/**
		 * Mitglied der Konferenzpresse
		 */
		PRESS_CORPS: () => LocalizedString
		/**
		 * Gast
		 */
		GUEST: () => LocalizedString
		/**
		 * Teilnehmendenbetreuung
		 */
		PARTICIPANT_CARE: () => LocalizedString
		/**
		 * Teammitglied
		 */
		MISCELLANEOUS_TEAM: () => LocalizedString
		/**
		 * Unbekannte Rolle
		 */
		UNKNOWN: () => LocalizedString
	}
	messageCategories: {
		/**
		 * Anfrage an den Vorsitz
		 */
		TO_CHAIR: () => LocalizedString
		/**
		 * Gastrede anfragen
		 */
		GUEST_SPEAKER: () => LocalizedString
		/**
		 * Faktencheck
		 */
		FACT_CHECK: () => LocalizedString
		/**
		 * Informationsanfrage
		 */
		INFORMATION: () => LocalizedString
		/**
		 * Um Besuch des/der Generalsekretär*in bitten
		 */
		GENERAL_SECRETARY: () => LocalizedString
		/**
		 * Sonstiges
		 */
		OTHER: () => LocalizedString
	}
	home: {
		/**
		 *  im 21. Jahrhundert
		 */
		CAPTION: () => LocalizedString
		/**
		 * Debattenmanagement bei Model United Nations Konferenzen bekommt endlich ein Upgrade.
		 */
		HERO_TEXT: () => LocalizedString
		navbar: {
			/**
			 * Admin
			 */
			LOGIN_ADMIN: () => LocalizedString
			/**
			 * Vorsitz
			 */
			LOGIN_CHAIR: () => LocalizedString
			/**
			 * Dokumentation
			 */
			DOCUMENTATION: () => LocalizedString
			/**
			 * FAQ
			 */
			FAQ: () => LocalizedString
			/**
			 * Zur App
			 */
			TO_APP: () => LocalizedString
		}
		heroCards: {
			/**
			 * Debatten
			 */
			CARD_1_TITLE: () => LocalizedString
			/**
			 * Verwalte Rede- und Kurzbemerkungsliste einfach und effizient. Keine Papierlisten mehr!
			 */
			CARD_1_TEXT: () => LocalizedString
			/**
			 * Abstimmungen
			 */
			CARD_2_TITLE: () => LocalizedString
			/**
			 * Verwalte Anträge und Abstimmungen elektronisch und mit vorbereiteten Anträgen nach Ihrer Geschäftsordnung.
			 */
			CARD_2_TEXT: () => LocalizedString
			/**
			 * Resolutionen
			 */
			CARD_3_TITLE: () => LocalizedString
			/**
			 * Erstelle und bearbeite Resolutionen gemeinsam mit anderen Delegierten. Kein Papier oder Google Docs mehr!
			 */
			CARD_3_TEXT: () => LocalizedString
			/**
			 * Kommt bald
			 */
			COMING_SOON: () => LocalizedString
		}
		/**
		 * Über CHASE
		 */
		ABOUT_TITEL: () => LocalizedString
		/**
		 * CHASE (CHAirSoftwarE) ist eine Webanwendung zur Verwaltung und Durchführung von Debatten in Model United Nations Konferenzen. Sie ist für Vorsitzende und Delegierte gleichermaßen konzipiert. CHASE ermöglicht es Vorsitzenden, Debatten einfach zu verwalten, während Delegierte der Debatte folgen und mit anderen Delegierten auf intuitive und strukturierte Weise zusammenarbeiten können. CHASE ist freie und open source Software.
		 */
		ABOUT_TEXT: () => LocalizedString
		/**
		 * Unsere Mission
		 */
		MISSION_TITLE: () => LocalizedString
		/**
		 * CHASE wird von Mitgliedern des deutschen Vereins DMUN e.V. entwickelt. Wir wollen eine kostenlose und frei zugängliche Alternative zu anderen Debatten-Management Anwendungen schaffen und damit den Zugang auch für kleinere Konferenzen erleichtern. CHASE ist primär für die deutschsprachigen Konferenzen von DMUN in Deutschland – MUN-SH, MUNBW und MUNBB – entwickelt worden. Wir sind aber offen dafür, CHASE an andere Konferenzen anzupassen.
		 */
		MISSION_TEXT: () => LocalizedString
		/**
		 * Mehr über DMUN erfahren
		 */
		MISSION_BUTTON_LABEL: () => LocalizedString
		/**
		 * Mithelfen
		 */
		CONTRIBUTE_TITEL: () => LocalizedString
		/**
		 * CHASE ist ein wichtiger Bestandteil der Open-Source-Initiative 'MUNify' von DMUN. Das bedeutet, dass jeder, der möchte, zur Entwicklung beitragen kann. Wir freuen uns über jede Hilfe, die wir bekommen können. Wenn Sie also Erfahrung im Web-Development haben, oder einfach nur neue Skills lernen und mithelfen möchten, schauen Sie doch mal auf unserem GitHub vorbei!
		 */
		CONTRIBUTE_TEXT: () => LocalizedString
		/**
		 * MUNify auf GitHub
		 */
		CONTRIBUTE_BUTTON_LABEL: () => LocalizedString
		/**
		 * Version und Änderungen
		 */
		VERSION_BUTTON: () => LocalizedString
		footer: {
			sitemap: {
				/**
				 * Sitemap
				 */
				TITEL: () => LocalizedString
				/**
				 * Home
				 */
				HOME: () => LocalizedString
				/**
				 * FAQs
				 */
				FAQ: () => LocalizedString
				/**
				 * Dokumentation
				 */
				DOCS: () => LocalizedString
				/**
				 * Login
				 */
				LOGIN: () => LocalizedString
				/**
				 * Datenschutzbestimmungen
				 */
				PRIVACY: () => LocalizedString
			}
			imprint: {
				/**
				 * Impressum
				 */
				TITEL: () => LocalizedString
				/**
				 * Deutsche Model United Nations (DMUN) e.V.
				 */
				ORGANISATION: () => LocalizedString
				/**
				 * Birkenweg 1, 24235 Laboe
				 */
				ADDRESS: () => LocalizedString
				/**
				 * vorstand@dmun.de
				 */
				EMAIL: () => LocalizedString
				/**
				 * www.dmun.de
				 */
				WEBSITE: () => LocalizedString
			}
		}
	}
	docs: {
		/**
		 * Dokumentation
		 */
		TITLE: () => LocalizedString
		/**
		 * Hier finden Sie eine Übersicht über die Funktionen und Möglichkeiten von CHASE.
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * Zurück zur Startseite
		 */
		BACK_TO_HOME: () => LocalizedString
	}
	faq: {
		/**
		 * FAQs
		 */
		TITLE: () => LocalizedString
		/**
		 * Hier finden Sie Antworten auf häufig gestellte Fragen zu CHASE.
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * Back to home
		 */
		BACK_TO_HOME: () => LocalizedString
	}
	admin: {
		login: {
			/**
			 * Admin Login
			 */
			TITLE: () => LocalizedString
			/**
			 * Konferenz ID
			 */
			CONFERENCE_ID: () => LocalizedString
			/**
			 * Erstellen
			 */
			CREATE_INSTEAD: () => LocalizedString
			/**
			 * Login
			 */
			SUBMIT: () => LocalizedString
		}
		onboarding: {
			/**
			 * Neue Konferenz erstellen
			 */
			title: () => LocalizedString
			/**
			 * Name der Konferenz
			 */
			conferenceName: () => LocalizedString
			/**
			 * Zeitraum
			 */
			dates: () => LocalizedString
			/**
			 * Erstellungstoken
			 */
			token: () => LocalizedString
			/**
			 * Anmelden
			 */
			login: () => LocalizedString
			/**
			 * Erstellen
			 */
			submit: () => LocalizedString
			/**
			 * Erfolg
			 */
			success: () => LocalizedString
			/**
			 * Die Konferenz wurde erstellt!
			 */
			successDetails: () => LocalizedString
			error: {
				/**
				 * Fehler
				 */
				title: () => LocalizedString
				/**
				 * Das Token ist ungültig.
				 */
				wrongToken: () => LocalizedString
				/**
				 * Eine Konferenz mit diesem Namen existiert bereits.
				 */
				conferenceExists: () => LocalizedString
				/**
				 * Ein Fehler ist aufgetreten.
				 */
				generic: () => LocalizedString
				/**
				 * Aus rechtlichen Gründen nicht erreichbar (keiner Verwendung von Cookies zugestimmt).
				 */
				unavailable: () => LocalizedString
			}
			/**
			 * Einrichtung beenden
			 */
			SAVE_AND_QUIT: () => LocalizedString
			/**
			 * Wollen Sie die Einrichtung wirklich beenden? Sie kann später jederzeit fortgesetzt werden.
			 */
			SAVE_AND_QUIT_MESSAGE: () => LocalizedString
			/**
			 * Weiter
			 */
			BUTTON_ADVANCE: () => LocalizedString
			/**
			 * Zurück
			 */
			BUTTON_BACK: () => LocalizedString
			structure: {
				/**
				 * Alles löschen
				 */
				DELETE_ALL: () => LocalizedString
				/**
				 * Are you sure you want to delete all committees?
				 */
				DELETE_ALL_CONFIRM: () => LocalizedString
				/**
				 * Gremium hinzufügen
				 */
				ADD_COMMITTEE: () => LocalizedString
				/**
				 * Gremium hinzugefügt
				 */
				SUCCESS_ADD_COMMITTEE: () => LocalizedString
				/**
				 * Keine Gremien vorhanden. Klicke oben rechts auf 'Gremium hinzufügen', um ein neues Gremium zu erstellen.
				 */
				EMPTY_MESSAGE: () => LocalizedString
				/**
				 * Name
				 */
				COMMITTEE_LONG: () => LocalizedString
				/**
				 * Abkürzung
				 */
				COMMITTEE_SHORT: () => LocalizedString
				/**
				 * Kategorie
				 */
				CATEGORY: () => LocalizedString
				/**
				 * Insgesamt {{0}} Gremien.
				 */
				FOOTER: (arg0: number | string | boolean) => LocalizedString
				input: {
					/**
					 * Hinzufügen
					 */
					BUTTON_ADD: () => LocalizedString
					/**
					 * Abbrechen
					 */
					BUTTON_CANCEL: () => LocalizedString
					/**
					 * Kategorie
					 */
					CATEGORY: () => LocalizedString
					/**
					 * Gremium
					 */
					CATEGORY_SWITCH_COMMITTEE: () => LocalizedString
					/**
					 * Krise
					 */
					CATEGORY_SWITCH_CRISIS: () => LocalizedString
					/**
					 * IGH
					 */
					CATEGORY_SWITCH_ICJ: () => LocalizedString
					/**
					 * Ist Vorlegendes Gremium / Untergremium
					 */
					IS_SUBCOMMITTEE: () => LocalizedString
					/**
					 * Beschlussfassendes Gremium / Übergeordnetes Gremium
					 */
					PARENT_COMMITTEE: () => LocalizedString
				}
				/**
				 * Keine Gremien vorhanden
				 */
				ERROR_NO_COMMITTEES: () => LocalizedString
				/**
				 * Bitte erstellen Sie ein Gremium, um fortzufahren.
				 */
				ERROR_NO_COMMITTEES_DETAILS: () => LocalizedString
			}
			teampool: {
				/**
				 * Alle löschen
				 */
				DELETE_ALL: () => LocalizedString
				/**
				 * CSV hochladen
				 */
				UPLOAD_TEAM: () => LocalizedString
				/**
				 * Teammitglied hinzufügen
				 */
				ADD_TEAMMEMBER: () => LocalizedString
				/**
				 * Keine Teammitglieder vorhanden. Klicke oben rechts auf 'Teammitglied hinzufügen', um ein neues Teammitglied zu erstellen.
				 */
				EMPTY_MESSAGE: () => LocalizedString
				/**
				 * Insgesamt {{0}} Teammitglieder.
				 */
				FOOTER: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Rolle
				 */
				ROLE: () => LocalizedString
				/**
				 * Anzahl
				 */
				COUNT: () => LocalizedString
				roles: {
					/**
					 * Admin
					 */
					ADMIN: () => LocalizedString
					/**
					 * Sekretariat
					 */
					SECRETARIAT: () => LocalizedString
					/**
					 * Vorsitz
					 */
					CHAIR: () => LocalizedString
					/**
					 * Gremienberatung
					 */
					COMMITTEE_ADVISOR: () => LocalizedString
					/**
					 * Nichtstaatliche Akteur
					 */
					NON_STATE_ACTOR: () => LocalizedString
					/**
					 * Konferenzpresse
					 */
					PRESS_CORPS: () => LocalizedString
					/**
					 * Gast
					 */
					GUEST: () => LocalizedString
					/**
					 * Teilnehmendenbetreuung
					 */
					PARTICIPANT_CARE: () => LocalizedString
					/**
					 * Sonstiges Team
					 */
					MISCELLANEOUS_TEAM: () => LocalizedString
				}
				input: {
					/**
					 * Anzahl
					 */
					COUNT: () => LocalizedString
					/**
					 * Hinzufügen
					 */
					BUTTON_ADD: () => LocalizedString
					/**
					 * Abbrechen
					 */
					BUTTON_CANCEL: () => LocalizedString
				}
			}
			committees: {
				/**
				 * Vorsitzende auswählen
				 */
				CHAIRS: () => LocalizedString
				/**
				 * Gremienberatung auswählen
				 */
				ADVISORS: () => LocalizedString
				/**
				 * Tagesordnung
				 */
				AGENDA_ITEMS: () => LocalizedString
				/**
				 * Tagesordnungspunkt hinzufügen
				 */
				ADD_AGENDA_ITEM: () => LocalizedString
				/**
				 * Hinzufügen
				 */
				ADD_ITEM_BUTTON: () => LocalizedString
			}
			delegations: {
				/**
				 * Delegation hinzufügen
				 */
				ADD_DELEGATION_BUTTON: () => LocalizedString
				/**
				 * Delegation
				 */
				DELEGATION_COLUMN: () => LocalizedString
				/**
				 * Summe
				 */
				TOTAL_NUMBER_OF_DELEGATIONS: () => LocalizedString
				/**
				 * Keine Delegationen gefunden
				 */
				EMPTY_MESSAGE: () => LocalizedString
				add_delegation: {
					/**
					 * Delegation hinzufügen
					 */
					HEADLINE: () => LocalizedString
					/**
					 * Nach Delegation suchen
					 */
					SEARCH_PLACEHOLDER: () => LocalizedString
					/**
					 * Zurück
					 */
					BACK_BUTTON: () => LocalizedString
					/**
					 * Hinzufügen und schließen
					 */
					ADD_BUTTON: () => LocalizedString
					/**
					 * Hinzufügen
					 */
					ADD_MORE_BUTTON: () => LocalizedString
				}
			}
			configs: {
				/**
				 * Presse Website
				 */
				pressWebsiteTitle: () => LocalizedString
				/**
				 * Hier kannst du die URL der Pressewebsite konfigurieren.
				 */
				pressWebsiteDescription: () => LocalizedString
				/**
				 * Feedback Website
				 */
				feedbackWebsiteTitle: () => LocalizedString
				/**
				 * Hier kannst du die URL der Feedbackwebsite konfigurieren.
				 */
				feedbackWebsiteDescription: () => LocalizedString
				/**
				 * Einstellungen gespeichert
				 */
				successToast: () => LocalizedString
			}
			steps: {
				/**
				 * Struktur
				 */
				STEP_1: () => LocalizedString
				/**
				 * Teampool
				 */
				STEP_2: () => LocalizedString
				/**
				 * Gremien
				 */
				STEP_3: () => LocalizedString
				/**
				 * Delegationen
				 */
				STEP_4: () => LocalizedString
				/**
				 * NAs
				 */
				STEP_5: () => LocalizedString
				/**
				 * Configurations
				 */
				STEP_6: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * E-Mail
		 */
		EMAIL_PLACEHOLDER: () => LocalizedString
		/**
		 * Passwort
		 */
		PASSWORD_PLACEHOLDER: () => LocalizedString
		/**
		 * Passwort wiederholen
		 */
		REPEAT_PASSWORD_PLACEHOLDER: () => LocalizedString
		/**
		 * Passwörter stimmen nicht überein
		 */
		PASSWORDS_DO_NOT_MATCH: () => LocalizedString
		/**
		 * Passwort vergessen?
		 */
		FORGOT_PASSWORD: () => LocalizedString
		/**
		 * E-Mail gesendet
		 */
		SENT_EMAIL: () => LocalizedString
		/**
		 * Weiter
		 */
		ADVANCE_BUTTON: () => LocalizedString
		/**
		 * Zurück
		 */
		BACK_BUTTON: () => LocalizedString
		/**
		 * Anmelden
		 */
		LOGIN_BUTTON: () => LocalizedString
		/**
		 * Anmelden
		 */
		LOGIN_TITLE: () => LocalizedString
		/**
		 * Bitte melden Sie sich mit Ihren Zugangsdaten an.
		 */
		LOGIN_DESCRIPTION: () => LocalizedString
		/**
		 * Die E-Mail-Adresse wurde noch nicht bestätigt. Bitte checken Sie Ihr E-Mail-Postfach.
		 */
		EMAIL_NOT_CONFIRMED: () => LocalizedString
		/**
		 * Die E-Mail-Adresse wurde nicht gefunden.
		 */
		EMAIL_NOT_FOUND: () => LocalizedString
		/**
		 * Die E-Mail-Adresse hat keinen aktiven Bestätigungstoken.
		 */
		EMAIL_NO_ACTIVE_VALIDATION_TOKEN: () => LocalizedString
		/**
		 * Der Bestätigungstoken ist ungültig.
		 */
		EMAIL_INVALID_TOKEN: () => LocalizedString
		/**
		 * Die E-Mail-Adresse wurde bereits bestätigt.
		 */
		EMAIL_ALREADY_VALIDATED: () => LocalizedString
		/**
		 * Der Bestätigungstoken ist abgelaufen. Bitte fordern Sie einen neuen an.
		 */
		EMAIL_VALIDATION_TOKEN_EXPIRED: () => LocalizedString
		/**
		 * Zugangsdaten festlegen
		 */
		SET_CREDENTIALS: () => LocalizedString
		/**
		 * Der Bestätigungstoken ist ungültig oder nicht vorhanden.
		 */
		NO_TOKEN: () => LocalizedString
		/**
		 * Die E-Mail ist ungültig oder nicht vorhanden.
		 */
		NO_EMAIL: () => LocalizedString
		/**
		 * Die E-Mail ist nun bestätigt!
		 */
		EMAIL_CONFIRMED: () => LocalizedString
		/**
		 * Wir hatten Probleme deine E-Mail zu bestätigen. Bitte versuche es später noch einmal.
		 */
		EMAIL_CONFIRMED_SERVER_ERROR: () => LocalizedString
		/**
		 * Passkey
		 */
		PASSKEY: () => LocalizedString
		/**
		 * Passwort
		 */
		PASSWORD: () => LocalizedString
		/**
		 * Jetzt anmelden
		 */
		LOGIN_NOW: () => LocalizedString
		/**
		 * E-Mail-Adresse ungültig
		 */
		EMAIL_INVALID: () => LocalizedString
		/**
		 * Konto erstellen
		 */
		CREATE_ACCOUNT: () => LocalizedString
		/**
		 * Das Passwort ist ungültig. Es muss mindestens 8 Zeichen lang sein, und mindesten einen Großbuchstaben, einen Kleinbuchstaben, eine Zahl und ein Sonderzeichen enthalten.
		 */
		PASSWORD_INVALID: () => LocalizedString
		/**
		 * Benutzer gefunden. Bitte geben Sie Ihr Passwort ein.
		 */
		USER_FOUND: () => LocalizedString
		/**
		 * Was sind Passkeys?
		 */
		WHAT_ARE_PASSKEYS: () => LocalizedString
		/**
		 * Account erfolgreich erstellt. Bitte bestätigen Sie ihre E-Mail-Adresse über die Link in der E-Mail, die wir geschickt haben, um den Account zu aktivieren.
		 */
		CREATION_SUCCESS: () => LocalizedString
		/**
		 * Prima, ein Konto mit dieser E-Mail-Adresse existiert noch nicht! Sie können jetzt ein Konto für diese E-Mail Addresse erstellen.
		 */
		ACCOUNT_NOT_YET_CREATED: () => LocalizedString
		/**
		 * Falsche Zugangsdaten
		 */
		WRONG_CREDENTIALS: () => LocalizedString
		/**
		 * Ermöglicht durch
		 */
		POWERED_BY: () => LocalizedString
		legalNotice: {
			/**
			 * Ich bin Einverstanden mit den 
			 */
			SECTION_1: () => LocalizedString
			/**
			 * Nutzungsbedingungen
			 */
			TERMS_LINK: () => LocalizedString
			/**
			 * . Außerdem bin ich damit einverstanden, dass diese Website Cookies verwendet. Mehr Informationen dazu finden Sie in unseren 
			 */
			SECTION_2: () => LocalizedString
			/**
			 * Datenschutzbestimmungen
			 */
			PRIVACY_LINK: () => LocalizedString
			/**
			 * .
			 */
			SECTION_3: () => LocalizedString
		}
		participant: {
			/**
			 * Stattdessen als Vorsitz anmelden
			 */
			OTHER_SIGH_IN: () => LocalizedString
			/**
			 * Gremium
			 */
			COMMITTEE_LABEL: () => LocalizedString
			/**
			 * Staat / NA
			 */
			COUNTRY_LABEL: () => LocalizedString
			committeeSelection: {
				/**
				 * Gremium auswählen
				 */
				HEADLINE: () => LocalizedString
			}
		}
		chair: {
			/**
			 * Stattdessen als Teilnehmer anmelden
			 */
			OTHER_SIGN_IN: () => LocalizedString
			/**
			 * Sie sind im Begriff sich als Vorsitz anzumelden.
			 */
			WARNING_MESSAGE: () => LocalizedString
		}
		gateway: {
			/**
			 * Willkommen bei CHASE
			 */
			TITLE: () => LocalizedString
			/**
			 * Du bist für eine Konferenz registriert. Klicke auf den Button unten, um die App zu starten.
			 */
			CONFERENCE_MEMBER_SINGLE: () => LocalizedString
			/**
			 * Du bist für mehrere Konferenzen registriert. Bitte wähle die Konferenz, für die du die App starten möchtest.
			 */
			CONFERENCE_MEMBER_MULTIPLE: () => LocalizedString
			/**
			 * Du bist für ein Gremium registriert. Klicke auf den Button unten, um die App zu starten.
			 */
			COMMITTEE_MEMBER_SINGLE: () => LocalizedString
			/**
			 * Du bist für mehrere Gremien registriert. Bitte wähle das Gremium, für das du die App starten möchtest.
			 */
			COMMITTEE_MEMBER_MULTIPLE: () => LocalizedString
			/**
			 * Launch the app
			 */
			LAUNCH_BUTTON: () => LocalizedString
			/**
			 * Du bist für keine Konferenz oder kein Gremium registriert. Wenn du glaubst, dass das ein Fehler ist, wende dich bitte an den Konferenzadmin.
			 */
			NO_MEMBERSHIP: () => LocalizedString
			/**
			 * Abmelden
			 */
			LOGOUT_BUTTON: () => LocalizedString
		}
		lockout: {
			/**
			 * Du wurdest ausgesperrt
			 */
			TITLE: () => LocalizedString
			/**
			 * Du hast keine Berechtigung, diesen Teil der App zu nutzen. Bitte melde dich erneut an.
			 */
			DETAIL: () => LocalizedString
		}
	}
	navbar: {
		/**
		 * Einstellungen
		 */
		SETTINGS: () => LocalizedString
		/**
		 * Logout
		 */
		LOGOUT: () => LocalizedString
		/**
		 * Hub
		 */
		HUB: () => LocalizedString
		/**
		 * Dashboard
		 */
		DASHBOARD: () => LocalizedString
		/**
		 * Voreinstellungen
		 */
		CONFIGURATION: () => LocalizedString
		/**
		 * Anwesenheit
		 */
		ATTENDEES: () => LocalizedString
		/**
		 * Redeliste
		 */
		SPEAKERS: () => LocalizedString
		/**
		 * Abstimmungen
		 */
		VOTING: () => LocalizedString
		/**
		 * Whiteboard
		 */
		WHITEBOARD: () => LocalizedString
		/**
		 * Inbox
		 */
		INBOX: () => LocalizedString
		/**
		 * Resolutionen
		 */
		RESOLUTIONS: () => LocalizedString
		/**
		 * Präsentation
		 */
		PRESENTATION: () => LocalizedString
		/**
		 * Konferenzpresse
		 */
		NEWS: () => LocalizedString
		/**
		 * Fehler melden
		 */
		BUG_REPORT: () => LocalizedString
	}
	settings: {
		colorTheme: {
			/**
			 * Farbmodus
			 */
			HEADLINE: () => LocalizedString
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * Hell
			 */
			LIGHT: () => LocalizedString
			/**
			 * Dunkel
			 */
			DARK: () => LocalizedString
			/**
			 * Kontrast
			 */
			CONTRAST: () => LocalizedString
		}
		language: {
			/**
			 * Sprache
			 */
			HEADLINE: () => LocalizedString
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * English
			 */
			ENGLISH: () => LocalizedString
			/**
			 * Deutsch
			 */
			GERMAN: () => LocalizedString
		}
	}
	hub: {
		/**
		 * Mission Control
		 */
		CHAIR_HUB_TITLE: () => LocalizedString
		/**
		 * Hub der Nichtstaatliche Akteure
		 */
		NA_HUB_TITLE: () => LocalizedString
		/**
		 * Gäste-Hub
		 */
		GUEST_HUB_TITLE: () => LocalizedString
		/**
		 * Wähle ein Gremium
		 */
		SELECT_COMMITTEE: () => LocalizedString
		/**
		 * Keine Gremien gefunden
		 */
		NO_COMMITTEES: () => LocalizedString
		/**
		 * Abmelden
		 */
		LOGOUT: () => LocalizedString
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * Redeliste
				 */
				SPEAKERS_LIST: () => LocalizedString
				/**
				 * Fragen und Kurzbemerkungen
				 */
				COMMENT_LIST: () => LocalizedString
				/**
				 * Moderierte Informelle Sitzung
				 */
				MODERATED_CAUCUS: () => LocalizedString
				/**
				 * Debattenstatus
				 */
				COMMITTEE_STATUS: () => LocalizedString
				/**
				 * Whiteboard
				 */
				WHITEBOARD: () => LocalizedString
				/**
				 * Dokumente
				 */
				DOCUMENTS: () => LocalizedString
				/**
				 * Anfrage senden
				 */
				ACTIONS: () => LocalizedString
				/**
				 * Mehrheitsverhältnisse
				 */
				PRESENCE: () => LocalizedString
			}
			timerWidget: {
				/**
				 * bis {{0}} Uhr
				 */
				UNTIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Zeit ist abgelaufen!
				 */
				TOAST_HEADLINE: () => LocalizedString
				/**
				 * Gehe zurück in die formelle Debatte.
				 */
				TOAST_MESSAGE: () => LocalizedString
				defaultHeadlines: {
					/**
					 * Formelle Debatte
					 */
					FORMAL: () => LocalizedString
					/**
					 * Informelle Sitzung
					 */
					INFORMAL: () => LocalizedString
					/**
					 * Pause
					 */
					PAUSE: () => LocalizedString
					/**
					 * Vertagung
					 */
					SUSPENSION: () => LocalizedString
				}
			}
			actionsWidget: {
				/**
				 * Vorsitz
				 */
				CHAIR_BUTTON: () => LocalizedString
				/**
				 * Wiss. Dienst
				 */
				RESEARCH_SERVICE_BUTTON: () => LocalizedString
				contactForm: {
					/**
					 * Sende dem Vorsitz eine Nachricht
					 */
					HEADLINE_CHAIR: () => LocalizedString
					/**
					 * Sende dem Wissenschaftlichen Dienst (WD) eine Nachricht
					 */
					HEADLINE_RESEARCH_SERVICE: () => LocalizedString
					/**
					 * Betreff
					 */
					SUBJECT_PLACEHOLDER: () => LocalizedString
					/**
					 * Nachricht
					 */
					MESSAGE_PLACEHOLDER: () => LocalizedString
					/**
					 * Kategorie
					 */
					CATEGORY_LABEL: () => LocalizedString
					/**
					 * Wähle eine Kategorie aus
					 */
					CATEGORY_PLACEHOLDER: () => LocalizedString
					/**
					 * Abbrechen
					 */
					CANCEL_BUTTON: () => LocalizedString
					/**
					 * Senden
					 */
					SEND_BUTTON: () => LocalizedString
					/**
					 * Diese Anfrage wird zunächst vom Vorsitz geprüft und erst dann an den Wissenschaftlichen Dienst weitergeleitet. Die Antwort erfolgt in der Regel per E-Mail – behalten Sie bitte Ihr Postfach im Auge.
					 */
					INFO_MESSAGE: () => LocalizedString
					categoryOptions: {
						/**
						 * Gastrede anfragen
						 */
						GUEST_SPEAKER: () => LocalizedString
						/**
						 * Faktencheck
						 */
						FACT_CHECK: () => LocalizedString
						/**
						 * Informationsanfrage
						 */
						INFORMATION: () => LocalizedString
						/**
						 * Um Besuch des/der Generalsekretär*in bitten
						 */
						GENERAL_SECRETARY: () => LocalizedString
						/**
						 * Sonstiges
						 */
						OTHER: () => LocalizedString
					}
				}
				toast: {
					/**
					 * Nachricht gesendet
					 */
					SUCCESS_CHAIR_SUMMARY: () => LocalizedString
					/**
					 * Der Vorsitz wird sich bald bei Ihnen melden.
					 */
					SUCCESS_CHAIR_DETAIL: () => LocalizedString
					/**
					 * Nachricht gesendet
					 */
					SUCCESS_RESEARCH_SUMMARY: () => LocalizedString
					/**
					 * Der Wissenschaftliche Dienst wird sich bald bei Ihnen melden.
					 */
					SUCCESS_RESEARCH_DETAIL: () => LocalizedString
					/**
					 * Fehler beim Senden
					 */
					ERROR_SUMMARY: () => LocalizedString
					/**
					 * Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später erneut und melden Sie den Fehler.
					 */
					ERROR_DETAIL: () => LocalizedString
				}
			}
			documentsWidget: {
				/**
				 * signierte Unterstützer*innen
				 */
				SPONSORS: () => LocalizedString
			}
		}
		speakersList: {
			/**
			 * Redeliste
			 */
			SPEAKERS_LIST: () => LocalizedString
			/**
			 * Fragen und Kurzbemerkungen
			 */
			COMMENT_LIST: () => LocalizedString
			/**
			 * Moderierte Informelle Sitzung
			 */
			MODERATED_CAUCUS: () => LocalizedString
			/**
			 * Redebeitrag
			 */
			ADD_TO_LIST_BUTTON: () => LocalizedString
			/**
			 * Zurückziehen
			 */
			REMOVE_FROM_LIST_BUTTON: () => LocalizedString
			/**
			 * Liste Geschlossen
			 */
			LIST_CLOSED_BUTTON: () => LocalizedString
			/**
			 * Liste Geschlossen
			 */
			LIST_CLOSED_MESSAGE: () => LocalizedString
			/**
			 * Liste ist leer
			 */
			NO_SPEAKERS_MESSAGE: () => LocalizedString
			/**
			 * Kein aktiver Tagesordnungspunkt
			 */
			NO_ACTIVE_AGENDA_ITEM: () => LocalizedString
			toast: {
				/**
				 * Redebeitrag hinzugefügt
				 */
				ADDED_SUCCESS_SUMMARY: () => LocalizedString
				/**
				 * zu {{0}}
				 */
				ADDED_SUCCESS_DETAIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Hinzufügen nicht erlaubt
				 */
				ADDED_FORBIDDEN_SUMMARY: () => LocalizedString
				/**
				 * Sie sind wahrscheinlich nicht als ANWESEND im Gremium registriert. Bitte wende dich an den Vorsitz.
				 */
				ADDED_FORBIDDEN_DETAIL: () => LocalizedString
				/**
				 * Bereits auf der Liste
				 */
				ADDED_ALREADY_ON_LIST_SUMMARY: () => LocalizedString
				/**
				 * Bitte warten Sie einen Moment – Ihr Redebeitrag wird jeden Moment angezeigt. Wenn nicht, laden Sie die Seite neu. Wenn der Fehler weiterhin besteht, wenden Sie sich an den Vorsitz.
				 */
				ADDED_ALREADY_ON_LIST_DETAIL: () => LocalizedString
				/**
				 * Fehler beim Hinzufügen
				 */
				ADDED_ERROR_SUMMARY: () => LocalizedString
				/**
				 * Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut oder wenden Sie sich an den Vorsitz.
				 */
				ADDED_ERROR_DETAIL: () => LocalizedString
				/**
				 * Redebeitrag zurückgezogen
				 */
				REMOVED_SUCCESS_SUMMARY: () => LocalizedString
				/**
				 * von {{0}}
				 */
				REMOVED_SUCCESS_DETAIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Fehler beim Zurückziehen
				 */
				REMOVED_ERROR_SUMMARY: () => LocalizedString
				/**
				 * Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut oder wenden Sie sich an den Vorsitz.
				 */
				REMOVED_ERROR_DETAIL: () => LocalizedString
			}
		}
		voting: {
			/**
			 * Aktuelle Anträge
			 */
			ACTIVE_MOTIONS_TAB: () => LocalizedString
			/**
			 * Vergangene Anträge
			 */
			RECENT_MOTIONS_TAB: () => LocalizedString
			/**
			 * Vergangene Abstimmungen
			 */
			RECENT_VOTINGS_TAB: () => LocalizedString
			/**
			 * Aktuell keine Anträge
			 */
			NO_DATA_MOTIONS: () => LocalizedString
			/**
			 * Abstimmung
			 */
			VOTING_HEADLINE: () => LocalizedString
			/**
			 * Keine Abstimmung ausgewählt
			 */
			NO_DATA_VOTING: () => LocalizedString
			votingInfo: {
				/**
				 * Eingebracht von
				 */
				INTRODUCED_BY: () => LocalizedString
				votingMode: {
					/**
					 * Inhaltliche Abstimmung – Enthaltung möglich
					 */
					SUBSTANTIAL_VOTING: () => LocalizedString
					/**
					 * Prozessuale Abstimmung – keine Enthaltung möglich
					 */
					PROCEDURAL_VOTING: () => LocalizedString
				}
				majorityMode: {
					/**
					 * Einfache Mehrheit erforderlich (50% + 1)
					 */
					SIMPLE: () => LocalizedString
					/**
					 * Zwei-Drittel Mehrheit erforderlich (2/3)
					 */
					TWO_THIRDS: () => LocalizedString
					/**
					 * Drei-Viertel Mehrheit erforderlich (3/4)
					 */
					THREE_QUARTERS: () => LocalizedString
					/**
					 * Konsens erforderlich
					 */
					CONSENSUS: () => LocalizedString
					/**
					 * Abstimmungsmodus des Sicherheitsrats (9/15 + no veto)
					 */
					SECURITY_COUNCIL: () => LocalizedString
				}
			}
			votingButtons: {
				/**
				 * Dafür
				 */
				IN_FAVOUR: () => LocalizedString
				/**
				 * Dagegen
				 */
				AGAINST: () => LocalizedString
				/**
				 * Enthaltung
				 */
				ABSTENTION: () => LocalizedString
				/**
				 * Verbleibend
				 */
				REMAINING: () => LocalizedString
				/**
				 * Stimme registriert
				 */
				VOTE_REGISTERED: () => LocalizedString
				/**
				 * Warten auf Ergebnis
				 */
				VOTE_REGISTERED_MESSAGE: () => LocalizedString
			}
			votingResults: {
				/**
				 * Abstimung Erfolgreich
				 */
				VOTING_SUCCESSFUL: () => LocalizedString
				/**
				 * Abstimmung Fehlgeschlagen
				 */
				VOTING_FAILED: () => LocalizedString
			}
			votingAlert: {
				/**
				 * Neue Abstimmung gestartet
				 */
				VOTING_ALERT_HEADER: () => LocalizedString
				/**
				 * Sie wurden zu einer neuen Abstimmung aufgerufen. Bitte nehmen Sie schnellstmöglich daran teil.
				 */
				VOTING_ALERT_MESSAGE: () => LocalizedString
				/**
				 * Zur Abstimmung
				 */
				BUTTON_ADVANCE: () => LocalizedString
				/**
				 * Ignorieren
				 */
				BUTTON_IGNORE: () => LocalizedString
			}
		}
	}
	chairs: {
		/**
		 * Vorsitz
		 */
		CHAIR: () => LocalizedString
		dashboard: {
			overview: {
				/**
				 * Übersicht
				 */
				TITLE: () => LocalizedString
			}
			configurations: {
				/**
				 * Konfigurationen
				 */
				TITLE: () => LocalizedString
				agenda: {
					/**
					 * Auswahl des Tagesordnungspunktes
					 */
					TITLE: () => LocalizedString
					/**
					 * Wähle den aktuellen Tagesordnungspunkt aus.
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Gerade kein aktiver Tagesordnungspunkt
					 */
					PLACEHOLDER: () => LocalizedString
					/**
					 * Tagesordnungspunkt aktiviert
					 */
					TOAST_SUCCESS: () => LocalizedString
				}
				stateOfDebate: {
					/**
					 * Debattenstatus
					 */
					TITLE: () => LocalizedString
					/**
					 * Lege den Debattenstatus fest (z.B. Allgemeine Debatte)
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Kein Status festgelegt
					 */
					CURRENTLY_NO_STATUS: () => LocalizedString
					/**
					 * Debattenstatus
					 */
					PLACEHOLDER_TEXT: () => LocalizedString
					/**
					 * Status '{state}' gespeichert
					 */
					TOAST_SUCCESS: (arg: { state: unknown }) => LocalizedString
				}
				statusTimer: {
					/**
					 * Status Timer
					 */
					TITLE: () => LocalizedString
					/**
					 * Setze den Status des Gremiums fest. Du kannst auch einen benutzerdefinierten Namen festlegen, der den Standardstatusnamen überschreibt, während das Symbol beibehalten wird (z. B. 'Mittagspause' anstelle von 'Pause').
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Wähle einen Status aus
					 */
					PLACEHOLDER_DROPDOWN: () => LocalizedString
					/**
					 * Eigener Name (optional)
					 */
					PLACEHOLDER_CUSTOM_TEXT: () => LocalizedString
					/**
					 * until
					 */
					PLACEHOLDER_TIME_UNITL: () => LocalizedString
					/**
					 * Status Speichern
					 */
					BUTTON: () => LocalizedString
					/**
					 * Status {status} bis {date} gespeichert
					 */
					TOAST_SUCCESS: (arg: { date: unknown, status: unknown }) => LocalizedString
				}
				speakersListAdding: {
					/**
					 * Hinzufügen zu Redelisten
					 */
					TITLE: () => LocalizedString
					/**
					 * Wähle eine Einstellung aus, um Delegierten zu erlauben, sich selbst zur Redeliste hinzuzufügen.
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Nicht erlaubt
					 */
					TOGGLE_BUTTON_NOT_ALLOWED: () => LocalizedString
					/**
					 * Erlaubt
					 */
					TOGGLE_BUTTON_ALLOWED: () => LocalizedString
					/**
					 * Einstellung geändert
					 */
					TOAST_SUCCESS: () => LocalizedString
					/**
					 * Delegierte können sich nun selbst hinzufügen.
					 */
					TOAST_SUCCESS_DETAILS_ALLOWED: () => LocalizedString
					/**
					 * Delegierte können sich nicht mehr selbst hinzufügen.
					 */
					TOAST_SUCCESS_DETAILS_NOT_ALLOWED: () => LocalizedString
				}
				overlay: {
					/**
					 * Redeliste Overlay
					 */
					TITLE: () => LocalizedString
					/**
					 * Öffnet die Redeliste in einem kleinen Overlay am unteren Bildschirmrand.
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Overlay öffnen/schließen
					 */
					TOGGLE_BUTTON: () => LocalizedString
				}
				presentationMode: {
					/**
					 * Präsentationsmodus öffnen
					 */
					TITLE: () => LocalizedString
					/**
					 * Öffne ein neues Fenster im Präsentationsmodus über den folgenden Link, um ihn auf einem Beamer für alle Teilnehmenden sichtbar anzuzeigen.
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Präsentationsmodus
					 */
					BUTTON: () => LocalizedString
				}
				regionalGroups: {
					/**
					 * Regionalgruppen
					 */
					TITLE: () => LocalizedString
					/**
					 * Öffne eine Übersicht der Regionalgruppen und weise Delegationen zu.
					 */
					DESCRIPTION: () => LocalizedString
					/**
					 * Präsentations-Loop
					 */
					BUTTON_PRESENTATION: () => LocalizedString
					/**
					 * Regionalgruppen nachschlagen
					 */
					BUTTON_LOOKUP: () => LocalizedString
					/**
					 * Filtern...
					 */
					FILTER: () => LocalizedString
					/**
					 * Afrika
					 */
					AFRICA: () => LocalizedString
					/**
					 * Asien and Ozeanien
					 */
					ASIA: () => LocalizedString
					/**
					 * Lateinamerika und Karibik
					 */
					LATIN_AMERICA: () => LocalizedString
					/**
					 * Osteuropa
					 */
					EASTERN_EUROPE: () => LocalizedString
					/**
					 * Westeuropa und andere
					 */
					WESTERN_EUROPE: () => LocalizedString
				}
			}
		}
		attendance: {
			/**
			 * Anwesend
			 */
			PRESENT: () => LocalizedString
			/**
			 * Abwesend
			 */
			ABSENT: () => LocalizedString
			/**
			 * Entschuldigt
			 */
			EXCUSED: () => LocalizedString
			nations: {
				/**
				 * Anwesenheit der Delegationen
				 */
				TITLE: () => LocalizedString
				/**
				 * Verwalte die Anwesenheit der Delegationen im Gremium.
				 */
				DESCRIPTION: () => LocalizedString
			}
			nsa: {
				/**
				 * Nichtstaatliche Akteure
				 */
				TITLE: () => LocalizedString
				/**
				 * Verwalte die Anwesenheit der Nichtstaatlichen Akteure im Gremium. Sie werden nicht in die Abstimmungsverhältnisse einbezogen und dürfen nicht an Abstimmungen teilnehmen.
				 */
				DESCRIPTION: () => LocalizedString
			}
			/**
			 * Alle auf Abwesend setzen
			 */
			SET_ALL_ABSENT: () => LocalizedString
			/**
			 * Alle auf Anwesend setzen
			 */
			SET_ALL_PRESENT: () => LocalizedString
		}
		whiteboard: {
			/**
			 * Speichern und Veröffentlichen
			 */
			SAVE_BUTTON: () => LocalizedString
			/**
			 * Zurücksetzen
			 */
			RESET_BUTTON: () => LocalizedString
			/**
			 * Whiteboard gespeichert
			 */
			SUCCESS_TOAST: () => LocalizedString
			/**
			 * Whiteboard ist leer
			 */
			NO_CONTENT_TOAST: () => LocalizedString
			/**
			 * Es scheint, als ob beim laden des Whiteboards ein Fehler aufgetreten ist oder das Whiteboard ist leer. Bitte versuche die Seite neu zu laden.
			 */
			NO_CONTENT_TOAST_DETAILS: () => LocalizedString
		}
		speakersList: {
			buttons: {
				/**
				 * Start
				 */
				START_TIMER: () => LocalizedString
				/**
				 * Stop
				 */
				PAUSE_TIMER: () => LocalizedString
				/**
				 * Zeit zurücksetzen
				 */
				RESET_TIMER: () => LocalizedString
				/**
				 * 15s
				 */
				REMOVE_TIME: () => LocalizedString
				/**
				 * 15s
				 */
				ADD_TIME: () => LocalizedString
				/**
				 * Nächste Redner*in
				 */
				NEXT_SPEAKER: () => LocalizedString
				/**
				 * Redebeitrag
				 */
				ADD_TO_LIST: () => LocalizedString
				/**
				 * Liste schließen
				 */
				CLOSE_LIST: () => LocalizedString
				/**
				 * Liste öffnen
				 */
				OPEN_LIST: () => LocalizedString
				/**
				 * Liste zurücksetzen
				 */
				CLEAR_LIST: () => LocalizedString
				/**
				 * Redezeit ändern
				 */
				CHANGE_SPEECH_TIME: () => LocalizedString
			}
			addSpeakerOverlay: {
				/**
				 * Redebeiträge zu {{0}} hinzufügen
				 */
				HEADLINE: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Suche nach Redner*innen
				 */
				PLACEHOLDER: () => LocalizedString
				/**
				 * Schließen
				 */
				BUTTON_CANCEL: () => LocalizedString
				/**
				 * Hinzufügen
				 */
				BUTTON_ADD: () => LocalizedString
				/**
				 * Hinzufügen und schließen
				 */
				BUTTON_ADD_AND_CLOSE: () => LocalizedString
				/**
				 * {{0}} hinzugefügt
				 */
				TOAST_ADDED_SUMMARY: (arg0: number | string | boolean) => LocalizedString
				/**
				 * zu {{0}}
				 */
				TOAST_ADDED_DETAIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Already on {{0}}
				 */
				TOAST_ALREADY_ON_LIST: (arg0: number | string | boolean) => LocalizedString
				/**
				 * This country is already on {{0}}
				 */
				TOAST_ALREADY_ON_LIST_DETAIL: (arg0: number | string | boolean) => LocalizedString
			}
			changeSpeechTimeOverlay: {
				/**
				 * Redezeit für {{0}} ändern
				 */
				HEADLINE: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Abbrechen
				 */
				BUTTON_CANCEL: () => LocalizedString
				/**
				 * Ändern
				 */
				BUTTON_SET: () => LocalizedString
				/**
				 * Neue Redezeit (mm:ss)
				 */
				PLACEHOLDER: () => LocalizedString
				/**
				 * Redezeit festgelegt auf {{0}} min
				 */
				TOAST_SUCCESS: (arg0: number | string | boolean) => LocalizedString
				/**
				 * für {{0}}
				 */
				TOAST_SUCCESS_DETAIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Falsches Format
				 */
				TOAST_WRONG_FORMAT: () => LocalizedString
			}
			confirm: {
				/**
				 * Willst du wirklich den nächsten Redner aufrufen?
				 */
				NEXT_SPEAKER_MESSAGE: () => LocalizedString
				/**
				 * Nächste Rede: {list}
				 */
				NEXT_SPEAKER_HEADER: (arg: { list: unknown }) => LocalizedString
				/**
				 * Ja
				 */
				NEXT_SPEAKER_ACCEPT: () => LocalizedString
				/**
				 * Nein
				 */
				NEXT_SPEAKER_REJECT: () => LocalizedString
			}
		}
		voting: {
			/**
			 * Neuer Antrag
			 */
			BUTTON_NEW_MOTION: () => LocalizedString
			/**
			 * Infos Ändern
			 */
			BUTTON_CHANGE_INFO: () => LocalizedString
			/**
			 * Abstimmung neu starten
			 */
			BUTTON_RESET: () => LocalizedString
			/**
			 * Abstimmung löschen
			 */
			BUTTON_DELETE: () => LocalizedString
		}
	}
	messageBoard: {
		toast: {
			/**
			 * Neue Nachricht
			 */
			NEW_MESSAGE_SUMMARY: () => LocalizedString
			/**
			 * Sie haben eine neue Nachricht erhalten.
			 */
			NEW_MESSAGE_DETAIL: () => LocalizedString
			/**
			 * Nachricht weitergeleitet
			 */
			FORWARDED_SUMMARY: () => LocalizedString
			/**
			 * Die Nachricht wurde erfolgreich an den Wissenschaftlichen Dienst weitergeleitet.
			 */
			FORWARDED_DETAIL: () => LocalizedString
			/**
			 * Nachricht archiviert
			 */
			ARCHIVED_SUMMARY: () => LocalizedString
			/**
			 * Die Nachricht wurde erfolgreich archiviert. Um sie wieder herzustellen, frage einen Konferenz-Admin.
			 */
			ARCHIVED_DETAIL: () => LocalizedString
		}
		menu: {
			/**
			 * Als ungelesen markieren
			 */
			MARK_AS_UNREAD: () => LocalizedString
			/**
			 * Archivieren
			 */
			ARCHIVE: () => LocalizedString
		}
		pdf: {
			/**
			 * Nachricht eines/einer Teilnehmenden
			 */
			HEADLINE: () => LocalizedString
			/**
			 * Von
			 */
			FROM: () => LocalizedString
			/**
			 * Kategorie:
			 */
			CATEGORY: () => LocalizedString
			/**
			 * E-Mail:
			 */
			EMAIL: () => LocalizedString
			/**
			 * Empfangen am {date} um {time} Uhr
			 */
			TIME: (arg: { date: unknown, time: unknown }) => LocalizedString
		}
		/**
		 * {date} um {time} Uhr
		 */
		TIME: (arg: { date: unknown, time: unknown }) => LocalizedString
		/**
		 * Keine Nachricht ausgewählt
		 */
		NO_MESSAGE_SELECTED: () => LocalizedString
		/**
		 * Ungelesen
		 */
		TAG_UNREAD: () => LocalizedString
		/**
		 * Priorität
		 */
		TAG_PRIORITY: () => LocalizedString
		/**
		 * Zugewiesen
		 */
		TAG_ASSIGNED: () => LocalizedString
		/**
		 * WD
		 */
		TAG_RESEARCH_SERVICE: () => LocalizedString
		/**
		 * an WD senden
		 */
		BUTTON_FORWARD_TO_RESEARCH_SERVICE: () => LocalizedString
		tooltips: {
			/**
			 * Als ungelesen markieren
			 */
			UNREAD: () => LocalizedString
			/**
			 * Als Priorität markieren
			 */
			PRIORITY: () => LocalizedString
			/**
			 * Als zugewiesen markieren
			 */
			ASSIGNED: () => LocalizedString
			/**
			 * Nachricht löschen
			 */
			DELETE: () => LocalizedString
			/**
			 * Nachricht drucken
			 */
			PRINT: () => LocalizedString
			/**
			 * Antworten per E-Mail
			 */
			REPLY_VIA_EMAIL: () => LocalizedString
		}
	}
	version: {
		/**
		 * Version und Änderungsprotokoll
		 */
		VERSION_MODAL_TITLE: () => LocalizedString
		/**
		 * Version
		 */
		VERSION: () => LocalizedString
		/**
		 * Änderungsprotokoll
		 */
		CHANGELOG: () => LocalizedString
		/**
		 * Dieses Änderungsprotokoll zeigt die Änderungen in der aktuellen und den letzten 4 Versionen. Aktuell ist das Änderungsprotokoll ausschließlich auf Englisch verfügbar. Für weitere Informationen besuchen Sie unser GitHub-Repository, indem Sie auf den Link unten klicken.
		 */
		CHANGELOG_TEXT: () => LocalizedString
		/**
		 * Alle Versionen
		 */
		ALL_RELEASES: () => LocalizedString
		/**
		 * Neue Version verfügbar
		 */
		NEW_VERSION_AVAILABLE: () => LocalizedString
		/**
		 * Bitte wenden Sie sich an den Administrator, um die App zu aktualisieren.
		 */
		NEW_VERSION_AVAILABLE_TEXT: () => LocalizedString
		/**
		 * Neueste Version
		 */
		LATEST_VERSION: () => LocalizedString
		/**
		 * Sie verwenden die neueste Version von CHASE.
		 */
		LATEST_VERSION_TEXT: () => LocalizedString
		/**
		 * Entwicklerversion
		 */
		DEVELOPMENT_VERSION: () => LocalizedString
		/**
		 * Sie verwenden eine Entwicklerversion von CHASE.
		 */
		DEVELOPMENT_VERSION_TEXT: () => LocalizedString
	}
}

export type Formatters = {}
