// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING_PAGE: string
	admin: {
		onboarding: {
			/**
			 * S​e​t​u​p​ ​n​e​w​ ​C​o​n​f​e​r​e​n​c​e
			 */
			title: string
			/**
			 * C​o​n​f​e​r​e​n​c​e​ ​N​a​m​e
			 */
			conferenceName: string
			/**
			 * D​a​t​e​s
			 */
			dates: string
			/**
			 * C​r​e​a​t​i​o​n​ ​T​o​k​e​n
			 */
			token: string
			/**
			 * L​o​g​i​n
			 */
			login: string
			/**
			 * C​r​e​a​t​e
			 */
			submit: string
			/**
			 * S​u​c​c​e​s​s
			 */
			success: string
			/**
			 * C​o​n​f​e​r​e​n​c​e​ ​c​r​e​a​t​e​d​!
			 */
			successDetails: string
			error: {
				/**
				 * E​r​r​o​r
				 */
				title: string
				/**
				 * T​h​e​ ​t​o​k​e​n​ ​i​s​ ​i​n​v​a​l​i​d​.
				 */
				wrongToken: string
				/**
				 * A​ ​c​o​n​f​e​r​e​n​c​e​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
				 */
				conferenceExists: string
				/**
				 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.
				 */
				generic: string
			}
			/**
			 * S​a​v​e​ ​a​n​d​ ​Q​u​i​t​ ​S​e​t​u​p
			 */
			SAVE_AND_QUIT: string
			/**
			 * S​a​v​e​ ​a​n​d​ ​C​o​n​t​i​n​u​e
			 */
			BUTTON_ADVANCE: string
			/**
			 * B​a​c​k
			 */
			BUTTON_BACK: string
			structure: {
				/**
				 * D​e​l​e​t​e​ ​A​l​l
				 */
				DELETE_ALL: string
				/**
				 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​c​o​m​m​i​t​t​e​e​s​?
				 */
				DELETE_ALL_CONFIRM: string
				/**
				 * A​d​d​ ​C​o​m​m​i​t​t​e​e
				 */
				ADD_COMMITTEE: string
				/**
				 * N​o​ ​C​o​m​m​i​t​t​e​e​s​ ​y​e​t​.​ ​C​l​i​c​k​ ​'​A​d​d​ ​C​o​m​m​i​t​t​e​e​'​ ​i​n​ ​t​h​e​ ​t​o​p​ ​r​i​g​h​t​ ​c​o​r​n​e​r​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​o​n​e​.
				 */
				EMPTY_MESSAGE: string
				/**
				 * N​a​m​e
				 */
				COMMITTEE_LONG: string
				/**
				 * A​b​b​r​e​v​i​a​t​i​o​n
				 */
				COMMITTEE_SHORT: string
				/**
				 * C​a​t​e​g​o​r​y
				 */
				CATEGORY: string
				/**
				 * I​n​ ​t​o​t​a​l​ ​{​{​0​}​}​ ​c​o​m​m​i​t​t​e​e​s​.
				 */
				FOOTER: string
				input: {
					/**
					 * A​d​d
					 */
					BUTTON_ADD: string
					/**
					 * C​a​n​c​e​l
					 */
					BUTTON_CANCEL: string
					/**
					 * C​a​t​e​g​o​r​y
					 */
					CATEGORY: string
					/**
					 * C​o​m​m​i​t​t​e​e
					 */
					CATEGORY_SWITCH_COMMITTEE: string
					/**
					 * C​r​i​s​i​s
					 */
					CATEGORY_SWITCH_CRISIS: string
					/**
					 * I​C​J
					 */
					CATEGORY_SWITCH_ICJ: string
					/**
					 * I​s​ ​S​u​b​-​C​o​m​m​i​t​t​e​e
					 */
					IS_SUBCOMMITTEE: string
					/**
					 * P​a​r​e​n​t​ ​C​o​m​m​i​t​t​e​e
					 */
					PARENT_COMMITTEE: string
				}
				/**
				 * N​o​ ​C​o​m​m​i​t​t​e​e​s​ ​f​o​u​n​d
				 */
				ERROR_NO_COMMITTEES: string
				/**
				 * P​l​e​a​s​e​ ​c​r​e​a​t​e​ ​a​ ​c​o​m​m​i​t​t​e​e​ ​b​e​f​o​r​e​ ​c​o​n​t​i​n​u​i​n​g​.
				 */
				ERROR_NO_COMMITTEES_DETAILS: string
			}
			steps: {
				/**
				 * S​t​r​u​c​t​u​r​e
				 */
				STEP_1: string
				/**
				 * T​e​a​m​ ​P​o​o​l
				 */
				STEP_2: string
				/**
				 * C​o​m​m​i​t​t​e​e​s
				 */
				STEP_3: string
				/**
				 * D​e​l​e​g​a​t​i​o​n​s
				 */
				STEP_4: string
				/**
				 * R​o​l​e​s
				 */
				STEP_5: string
			}
		}
	}
	login: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		USERNAME_PLACEHOLDER: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		PASSWORD_PLACEHOLDER: string
		/**
		 * A​d​v​a​n​c​e
		 */
		ADVANCE_BUTTON: string
		/**
		 * B​a​c​k
		 */
		BACK_BUTTON: string
		/**
		 * L​o​g​i​n
		 */
		LOGIN_BUTTON: string
		/**
		 * P​o​w​e​r​e​d​ ​b​y
		 */
		POWERED_BY: string
		legalNotice: {
			/**
			 * I​ ​a​g​r​e​e​ ​w​i​t​h​ ​t​h​e​ 
			 */
			SECTION_1: string
			/**
			 * T​e​r​m​s​ ​o​f​ ​U​s​e
			 */
			TERMS_LINK: string
			/**
			 * .​ ​I​ ​a​l​s​o​ ​a​g​r​e​e​ ​t​h​a​t​ ​t​h​i​s​ ​w​e​b​s​i​t​e​ ​u​s​e​s​ ​c​o​o​k​i​e​s​.​ ​Y​o​u​ ​c​a​n​ ​f​i​n​d​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​t​h​i​s​ ​i​n​ ​o​u​r​ 
			 */
			SECTION_2: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			PRIVACY_LINK: string
			/**
			 * .
			 */
			SECTION_3: string
		}
		participant: {
			/**
			 * S​i​g​n​ ​i​n​ ​a​s​ ​c​h​a​i​r​ ​i​n​s​t​e​a​d
			 */
			OTHER_SIGH_IN: string
			/**
			 * C​o​m​m​i​t​t​e​e
			 */
			COMMITTEE_LABEL: string
			/**
			 * C​o​u​n​t​r​y​ ​/​ ​N​S​A
			 */
			COUNTRY_LABEL: string
			committeeSelection: {
				/**
				 * S​e​l​e​c​t​ ​t​h​e​ ​c​o​m​m​i​t​t​e​e
				 */
				HEADLINE: string
			}
		}
		chair: {
			/**
			 * S​i​g​n​ ​i​n​ ​a​s​ ​p​a​r​t​i​c​i​p​a​n​t​ ​i​n​s​t​e​a​d
			 */
			OTHER_SIGN_IN: string
			/**
			 * Y​o​u​ ​a​r​e​ ​a​b​o​u​t​ ​t​o​ ​s​i​g​n​ ​i​n​ ​a​s​ ​a​ ​c​h​a​i​r​.
			 */
			WARNING_MESSAGE: string
		}
	}
	navbar: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		SETTINGS: string
		/**
		 * L​o​g​o​u​t
		 */
		LOGOUT: string
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		DASHBOARD: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		CONFIGURATION: string
		/**
		 * A​t​t​e​n​d​e​e​s
		 */
		ATTENDEES: string
		/**
		 * S​p​e​a​k​e​r​s​ ​L​i​s​t
		 */
		SPEAKERS: string
		/**
		 * V​o​t​i​n​g
		 */
		VOTING: string
		/**
		 * W​h​i​t​e​b​o​a​r​d
		 */
		WHITEBOARD: string
		/**
		 * R​e​s​o​l​u​t​i​o​n​s
		 */
		RESOLUTIONS: string
		/**
		 * P​r​e​s​e​n​t​a​t​i​o​n
		 */
		PRESENTATION: string
		/**
		 * C​o​n​f​e​r​e​n​c​e​ ​P​r​e​s​s
		 */
		NEWS: string
	}
	settings: {
		colorTheme: {
			/**
			 * C​o​l​o​r​ ​M​o​d​e
			 */
			HEADLINE: string
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * L​i​g​h​t
			 */
			LIGHT: string
			/**
			 * D​a​r​k
			 */
			DARK: string
			/**
			 * C​o​n​t​r​a​s​t
			 */
			CONTRAST: string
		}
		language: {
			/**
			 * L​a​n​g​u​a​g​e
			 */
			HEADLINE: string
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * E​n​g​l​i​s​h
			 */
			ENGLISH: string
			/**
			 * D​e​u​t​s​c​h
			 */
			GERMAN: string
		}
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * S​p​e​a​k​e​r​s​ ​L​i​s​t
				 */
				SPEAKERS_LIST: string
				/**
				 * C​o​m​m​e​n​t​ ​L​i​s​t
				 */
				COMMENT_LIST: string
				/**
				 * C​o​m​m​i​t​t​e​e​ ​S​t​a​t​u​s
				 */
				COMMITTEE_STATUS: string
				/**
				 * W​h​i​t​e​b​o​a​r​d
				 */
				WHITEBOARD: string
				/**
				 * D​o​c​u​m​e​n​t​s
				 */
				DOCUMENTS: string
				/**
				 * S​e​n​d​ ​R​e​q​u​e​s​t
				 */
				ACTIONS: string
			}
			timerWidget: {
				/**
				 * u​n​t​i​l
				 */
				UNTIL_1: string
				UNTIL_2: string
				/**
				 * T​i​m​e​ ​i​s​ ​u​p​!
				 */
				TOAST_HEADLINE: string
				/**
				 * G​o​i​n​g​ ​b​a​c​k​ ​t​o​ ​f​o​r​m​a​l​ ​d​e​b​a​t​e​.
				 */
				TOAST_MESSAGE: string
			}
			actionsWidget: {
				/**
				 * C​h​a​i​r
				 */
				CHAIR_BUTTON: string
				/**
				 * R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e
				 */
				RESEARCH_SERVICE_BUTTON: string
				contactForm: {
					/**
					 * S​e​n​d​ ​a​ ​M​e​s​s​a​g​e​ ​t​o​ ​t​h​e​ ​C​h​a​i​r
					 */
					HEADLINE_CHAIR: string
					/**
					 * S​e​n​d​ ​a​ ​M​e​s​s​a​g​e​ ​t​o​ ​t​h​e​ ​R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e
					 */
					HEADLINE_RESEARCH_SERVICE: string
					/**
					 * S​u​b​j​e​c​t
					 */
					SUBJECT_PLACEHOLDER: string
					/**
					 * M​e​s​s​a​g​e
					 */
					MESSAGE_PLACEHOLDER: string
					/**
					 * C​a​t​e​g​o​r​y
					 */
					CATEGORY_LABEL: string
					/**
					 * S​e​l​e​c​t​ ​a​ ​C​a​t​e​g​o​r​y
					 */
					CATEGORY_PLACEHOLDER: string
					/**
					 * C​a​n​c​e​l
					 */
					CANCEL_BUTTON: string
					/**
					 * S​e​n​d
					 */
					SEND_BUTTON: string
					/**
					 * T​h​i​s​ ​r​e​q​u​e​s​t​ ​w​i​l​l​ ​b​e​ ​v​i​e​w​e​d​ ​a​n​d​ ​c​h​e​c​k​e​d​ ​b​y​ ​t​h​e​ ​c​h​a​i​r​ ​f​i​r​s​t​ ​a​n​d​ ​t​h​e​n​ ​f​o​r​w​a​r​d​e​d​ ​t​o​ ​t​h​e​ ​R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e​.
					 */
					INFO_MESSAGE: string
					categoryOptions: {
						/**
						 * G​u​e​s​t​ ​S​p​e​a​k​e​r​ ​R​e​q​u​e​s​t
						 */
						GUEST_SPEAKER: string
						/**
						 * F​a​c​t​ ​C​h​e​c​k​ ​R​e​q​u​e​s​t
						 */
						FACT_CHECK: string
						/**
						 * I​n​f​o​r​m​a​t​i​o​n​ ​R​e​q​u​e​s​t
						 */
						INFORMATION: string
						/**
						 * G​e​n​e​r​a​l​ ​S​e​c​r​e​t​a​r​y​ ​V​i​s​i​t​ ​R​e​q​u​e​s​t
						 */
						GENERAL_SECRETARY: string
						/**
						 * O​t​h​e​r
						 */
						OTHER: string
					}
				}
			}
			documentsWidget: {
				/**
				 * s​i​g​n​e​d​ ​S​p​o​n​s​o​r​s
				 */
				SPONSORS: string
			}
		}
		speakersList: {
			/**
			 * S​p​e​a​k​e​r​s​ ​L​i​s​t
			 */
			SPEAKERS_LIST: string
			/**
			 * C​o​m​m​e​n​t​ ​L​i​s​t
			 */
			COMMENT_LIST: string
			/**
			 * S​p​e​e​c​h
			 */
			ADD_TO_LIST_BUTTON: string
			/**
			 * R​e​m​o​v​e
			 */
			REMOVE_FROM_LIST_BUTTON: string
			/**
			 * L​i​s​t​ ​C​l​o​s​e​d
			 */
			LIST_CLOSED_BUTTON: string
			/**
			 * L​i​s​t​ ​C​l​o​s​e​d
			 */
			LIST_CLOSED_MESSAGE: string
			/**
			 * N​o​ ​S​p​e​a​k​e​r​s​ ​o​n​ ​t​h​e​ ​L​i​s​t
			 */
			NO_SPEAKERS_MESSAGE: string
		}
		voting: {
			/**
			 * M​o​t​i​o​n​s​ ​o​n​ ​t​h​e​ ​F​l​o​o​r
			 */
			ACTIVE_MOTIONS_TAB: string
			/**
			 * R​e​c​e​n​t​ ​M​o​t​i​o​n​s
			 */
			RECENT_MOTIONS_TAB: string
			/**
			 * R​e​c​e​n​t​ ​V​o​t​i​n​g​s
			 */
			RECENT_VOTINGS_TAB: string
			/**
			 * N​o​ ​o​p​e​n​ ​m​o​t​i​o​n​s
			 */
			NO_DATA_MOTIONS: string
			/**
			 * V​o​t​i​n​g
			 */
			VOTING_HEADLINE: string
			/**
			 * N​o​ ​v​o​t​i​n​g​ ​s​e​l​e​c​t​e​d
			 */
			NO_DATA_VOTING: string
			votingInfo: {
				/**
				 * I​n​t​r​o​d​u​c​e​d​ ​b​y
				 */
				INTRODUCED_BY: string
				votingMode: {
					/**
					 * S​u​b​s​t​a​n​t​i​a​l​ ​V​o​t​i​n​g​ ​–​ ​P​o​s​s​i​b​i​l​i​t​y​ ​t​o​ ​A​b​s​t​a​i​n
					 */
					SUBSTANTIAL_VOTING: string
					/**
					 * P​r​o​c​e​d​u​r​a​l​ ​V​o​t​i​n​g​ ​–​ ​N​o​ ​A​b​s​t​e​n​t​i​o​n
					 */
					PROCEDURAL_VOTING: string
				}
				majorityMode: {
					/**
					 * S​i​m​p​l​e​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​5​0​%​ ​+​ ​1​)
					 */
					SIMPLE: string
					/**
					 * T​w​o​-​T​h​i​r​d​s​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​2​/​3​)
					 */
					TWO_THIRDS: string
					/**
					 * T​h​r​e​e​-​Q​u​a​r​t​e​r​s​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​3​/​4​)
					 */
					THREE_QUARTERS: string
					/**
					 * C​o​n​s​e​n​s​u​s​ ​n​e​e​d​e​d
					 */
					CONSENSUS: string
					/**
					 * S​e​c​u​r​i​t​y​ ​C​o​u​n​c​i​l​ ​(​9​/​1​5​ ​+​ ​n​o​ ​v​e​t​o​)
					 */
					SECURITY_COUNCIL: string
				}
			}
			votingButtons: {
				/**
				 * I​n​ ​F​a​v​o​u​r
				 */
				IN_FAVOUR: string
				/**
				 * A​g​a​i​n​s​t
				 */
				AGAINST: string
				/**
				 * A​b​s​t​e​n​t​i​o​n
				 */
				ABSTENTION: string
				/**
				 * R​e​m​a​i​n​i​n​g
				 */
				REMAINING: string
				/**
				 * V​o​t​e​ ​R​e​g​i​s​t​e​r​e​d
				 */
				VOTE_REGISTERED: string
				/**
				 * W​a​i​t​i​n​g​ ​f​o​r​ ​r​e​s​u​l​t​s​.​.​.
				 */
				VOTE_REGISTERED_MESSAGE: string
			}
			votingResults: {
				/**
				 * V​o​t​i​n​g​ ​S​u​c​c​e​s​s​f​u​l
				 */
				VOTING_SUCCESSFUL: string
				/**
				 * V​o​t​i​n​g​ ​F​a​i​l​e​d
				 */
				VOTING_FAILED: string
			}
			votingAlert: {
				/**
				 * N​e​w​ ​V​o​t​e​ ​S​t​a​r​t​e​d
				 */
				VOTING_ALERT_HEADER: string
				/**
				 * A​ ​n​e​w​ ​v​o​t​e​ ​h​a​s​ ​b​e​e​n​ ​s​t​a​r​t​e​d​.​ ​P​l​e​a​s​e​ ​v​o​t​e​ ​n​o​w​.
				 */
				VOTING_ALERT_MESSAGE: string
				/**
				 * T​o​ ​V​o​t​i​n​g
				 */
				BUTTON_ADVANCE: string
				/**
				 * I​g​n​o​r​e
				 */
				BUTTON_IGNORE: string
			}
		}
	}
	chairs: {
		/**
		 * C​h​a​i​r
		 */
		CHAIR: string
		attendance: {
			/**
			 * A​t​t​e​n​d​a​n​c​e
			 */
			HEADLINE: string
			/**
			 * P​r​e​s​e​n​t
			 */
			PRESENT: string
			/**
			 * A​b​s​e​n​t
			 */
			ABSENT: string
			/**
			 * E​x​c​u​s​e​d
			 */
			EXCUSED: string
		}
		whiteboard: {
			/**
			 * S​a​v​e​ ​a​n​d​ ​p​u​b​l​i​s​h
			 */
			SAVE_BUTTON: string
			/**
			 * R​e​s​e​t
			 */
			RESET_BUTTON: string
		}
		speakersList: {
			buttons: {
				/**
				 * S​t​a​r​t​ ​T​i​m​e​r
				 */
				START_TIMER: string
				/**
				 * S​t​o​p​ ​T​i​m​e​r
				 */
				PAUSE_TIMER: string
				/**
				 * R​e​s​e​t​ ​T​i​m​e​r
				 */
				RESET_TIMER: string
				/**
				 * 1​5​s
				 */
				REMOVE_TIME: string
				/**
				 * 1​5​s
				 */
				ADD_TIME: string
				/**
				 * N​e​x​t​ ​S​p​e​a​k​e​r
				 */
				NEXT_SPEAKER: string
				/**
				 * A​d​d​ ​t​o​ ​L​i​s​t
				 */
				ADD_TO_LIST: string
				/**
				 * C​l​o​s​e​ ​L​i​s​t
				 */
				CLOSE_LIST: string
				/**
				 * O​p​e​n​ ​L​i​s​t
				 */
				OPEN_LIST: string
				/**
				 * R​e​s​e​t​ ​L​i​s​t
				 */
				CLEAR_LIST: string
				/**
				 * C​h​a​n​g​e​ ​S​p​e​e​c​h​ ​T​i​m​e
				 */
				CHANGE_SPEECH_TIME: string
			}
			addSpeakerOverlay: {
				/**
				 * A​d​d​ ​S​p​e​a​k​e​r​ ​t​o​ ​{​{​0​}​}
				 */
				HEADLINE: string
				/**
				 * S​e​l​e​c​t​ ​a​ ​S​p​e​a​k​e​r
				 */
				PLACEHOLDER: string
				/**
				 * C​a​n​c​e​l
				 */
				BUTTON_CANCEL: string
				/**
				 * A​d​d
				 */
				BUTTON_ADD: string
				/**
				 * A​d​d​ ​a​n​d​ ​C​l​o​s​e
				 */
				BUTTON_ADD_AND_CLOSE: string
				/**
				 * {​{​0​}​}​ ​a​d​d​e​d
				 */
				TOAST_ADDED_SUMMARY: string
				/**
				 * t​o​ ​t​h​e​ ​{​{​0​}​}
				 */
				TOAST_ADDED_DETAIL: string
			}
			changeSpeechTimeOverlay: {
				/**
				 * C​h​a​n​g​e​ ​S​p​e​e​c​h​ ​T​i​m​e​ ​f​o​r​ ​{​{​0​}​}
				 */
				HEADLINE: string
				/**
				 * C​a​n​c​e​l
				 */
				BUTTON_CANCEL: string
				/**
				 * C​h​a​n​g​e
				 */
				BUTTON_SET: string
				/**
				 * N​e​w​ ​S​p​e​e​c​h​ ​T​i​m​e​ ​(​m​m​:​s​s​)
				 */
				PLACEHOLDER: string
				/**
				 * S​p​e​e​c​h​ ​T​i​m​e​ ​c​h​a​n​g​e​d​ ​t​o​ ​{​{​0​}​}​ ​m​i​n
				 */
				TOAST_SUCCESS: string
				/**
				 * f​o​r​ ​{​{​0​}​}
				 */
				TOAST_SUCCESS_DETAIL: string
				/**
				 * W​r​o​n​g​ ​F​o​r​m​a​t
				 */
				TOAST_WRONG_FORMAT: string
			}
		}
		voting: {
			/**
			 * N​e​w​ ​M​o​t​i​o​n
			 */
			BUTTON_NEW_MOTION: string
			/**
			 * C​h​a​n​g​e​ ​I​n​f​o
			 */
			BUTTON_CHANGE_INFO: string
			/**
			 * R​e​s​t​a​r​t​ ​V​o​t​i​n​g
			 */
			BUTTON_RESET: string
			/**
			 * D​e​l​e​t​e​ ​V​o​t​i​n​g
			 */
			BUTTON_DELETE: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Loading...
	 */
	LOADING_PAGE: () => LocalizedString
	admin: {
		onboarding: {
			/**
			 * Setup new Conference
			 */
			title: () => LocalizedString
			/**
			 * Conference Name
			 */
			conferenceName: () => LocalizedString
			/**
			 * Dates
			 */
			dates: () => LocalizedString
			/**
			 * Creation Token
			 */
			token: () => LocalizedString
			/**
			 * Login
			 */
			login: () => LocalizedString
			/**
			 * Create
			 */
			submit: () => LocalizedString
			/**
			 * Success
			 */
			success: () => LocalizedString
			/**
			 * Conference created!
			 */
			successDetails: () => LocalizedString
			error: {
				/**
				 * Error
				 */
				title: () => LocalizedString
				/**
				 * The token is invalid.
				 */
				wrongToken: () => LocalizedString
				/**
				 * A conference with this name already exists.
				 */
				conferenceExists: () => LocalizedString
				/**
				 * An error occurred.
				 */
				generic: () => LocalizedString
			}
			/**
			 * Save and Quit Setup
			 */
			SAVE_AND_QUIT: () => LocalizedString
			/**
			 * Save and Continue
			 */
			BUTTON_ADVANCE: () => LocalizedString
			/**
			 * Back
			 */
			BUTTON_BACK: () => LocalizedString
			structure: {
				/**
				 * Delete All
				 */
				DELETE_ALL: () => LocalizedString
				/**
				 * Are you sure you want to delete all committees?
				 */
				DELETE_ALL_CONFIRM: () => LocalizedString
				/**
				 * Add Committee
				 */
				ADD_COMMITTEE: () => LocalizedString
				/**
				 * No Committees yet. Click 'Add Committee' in the top right corner to create a new one.
				 */
				EMPTY_MESSAGE: () => LocalizedString
				/**
				 * Name
				 */
				COMMITTEE_LONG: () => LocalizedString
				/**
				 * Abbreviation
				 */
				COMMITTEE_SHORT: () => LocalizedString
				/**
				 * Category
				 */
				CATEGORY: () => LocalizedString
				/**
				 * In total {{0}} committees.
				 */
				FOOTER: (arg0: number | string | boolean) => LocalizedString
				input: {
					/**
					 * Add
					 */
					BUTTON_ADD: () => LocalizedString
					/**
					 * Cancel
					 */
					BUTTON_CANCEL: () => LocalizedString
					/**
					 * Category
					 */
					CATEGORY: () => LocalizedString
					/**
					 * Committee
					 */
					CATEGORY_SWITCH_COMMITTEE: () => LocalizedString
					/**
					 * Crisis
					 */
					CATEGORY_SWITCH_CRISIS: () => LocalizedString
					/**
					 * ICJ
					 */
					CATEGORY_SWITCH_ICJ: () => LocalizedString
					/**
					 * Is Sub-Committee
					 */
					IS_SUBCOMMITTEE: () => LocalizedString
					/**
					 * Parent Committee
					 */
					PARENT_COMMITTEE: () => LocalizedString
				}
				/**
				 * No Committees found
				 */
				ERROR_NO_COMMITTEES: () => LocalizedString
				/**
				 * Please create a committee before continuing.
				 */
				ERROR_NO_COMMITTEES_DETAILS: () => LocalizedString
			}
			steps: {
				/**
				 * Structure
				 */
				STEP_1: () => LocalizedString
				/**
				 * Team Pool
				 */
				STEP_2: () => LocalizedString
				/**
				 * Committees
				 */
				STEP_3: () => LocalizedString
				/**
				 * Delegations
				 */
				STEP_4: () => LocalizedString
				/**
				 * Roles
				 */
				STEP_5: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Username
		 */
		USERNAME_PLACEHOLDER: () => LocalizedString
		/**
		 * Password
		 */
		PASSWORD_PLACEHOLDER: () => LocalizedString
		/**
		 * Advance
		 */
		ADVANCE_BUTTON: () => LocalizedString
		/**
		 * Back
		 */
		BACK_BUTTON: () => LocalizedString
		/**
		 * Login
		 */
		LOGIN_BUTTON: () => LocalizedString
		/**
		 * Powered by
		 */
		POWERED_BY: () => LocalizedString
		legalNotice: {
			/**
			 * I agree with the 
			 */
			SECTION_1: () => LocalizedString
			/**
			 * Terms of Use
			 */
			TERMS_LINK: () => LocalizedString
			/**
			 * . I also agree that this website uses cookies. You can find more information about this in our 
			 */
			SECTION_2: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			PRIVACY_LINK: () => LocalizedString
			/**
			 * .
			 */
			SECTION_3: () => LocalizedString
		}
		participant: {
			/**
			 * Sign in as chair instead
			 */
			OTHER_SIGH_IN: () => LocalizedString
			/**
			 * Committee
			 */
			COMMITTEE_LABEL: () => LocalizedString
			/**
			 * Country / NSA
			 */
			COUNTRY_LABEL: () => LocalizedString
			committeeSelection: {
				/**
				 * Select the committee
				 */
				HEADLINE: () => LocalizedString
			}
		}
		chair: {
			/**
			 * Sign in as participant instead
			 */
			OTHER_SIGN_IN: () => LocalizedString
			/**
			 * You are about to sign in as a chair.
			 */
			WARNING_MESSAGE: () => LocalizedString
		}
	}
	navbar: {
		/**
		 * Settings
		 */
		SETTINGS: () => LocalizedString
		/**
		 * Logout
		 */
		LOGOUT: () => LocalizedString
		/**
		 * Dashboard
		 */
		DASHBOARD: () => LocalizedString
		/**
		 * Configuration
		 */
		CONFIGURATION: () => LocalizedString
		/**
		 * Attendees
		 */
		ATTENDEES: () => LocalizedString
		/**
		 * Speakers List
		 */
		SPEAKERS: () => LocalizedString
		/**
		 * Voting
		 */
		VOTING: () => LocalizedString
		/**
		 * Whiteboard
		 */
		WHITEBOARD: () => LocalizedString
		/**
		 * Resolutions
		 */
		RESOLUTIONS: () => LocalizedString
		/**
		 * Presentation
		 */
		PRESENTATION: () => LocalizedString
		/**
		 * Conference Press
		 */
		NEWS: () => LocalizedString
	}
	settings: {
		colorTheme: {
			/**
			 * Color Mode
			 */
			HEADLINE: () => LocalizedString
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * Light
			 */
			LIGHT: () => LocalizedString
			/**
			 * Dark
			 */
			DARK: () => LocalizedString
			/**
			 * Contrast
			 */
			CONTRAST: () => LocalizedString
		}
		language: {
			/**
			 * Language
			 */
			HEADLINE: () => LocalizedString
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * English
			 */
			ENGLISH: () => LocalizedString
			/**
			 * Deutsch
			 */
			GERMAN: () => LocalizedString
		}
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * Speakers List
				 */
				SPEAKERS_LIST: () => LocalizedString
				/**
				 * Comment List
				 */
				COMMENT_LIST: () => LocalizedString
				/**
				 * Committee Status
				 */
				COMMITTEE_STATUS: () => LocalizedString
				/**
				 * Whiteboard
				 */
				WHITEBOARD: () => LocalizedString
				/**
				 * Documents
				 */
				DOCUMENTS: () => LocalizedString
				/**
				 * Send Request
				 */
				ACTIONS: () => LocalizedString
			}
			timerWidget: {
				/**
				 * until
				 */
				UNTIL_1: () => LocalizedString
				UNTIL_2: () => LocalizedString
				/**
				 * Time is up!
				 */
				TOAST_HEADLINE: () => LocalizedString
				/**
				 * Going back to formal debate.
				 */
				TOAST_MESSAGE: () => LocalizedString
			}
			actionsWidget: {
				/**
				 * Chair
				 */
				CHAIR_BUTTON: () => LocalizedString
				/**
				 * Research Service
				 */
				RESEARCH_SERVICE_BUTTON: () => LocalizedString
				contactForm: {
					/**
					 * Send a Message to the Chair
					 */
					HEADLINE_CHAIR: () => LocalizedString
					/**
					 * Send a Message to the Research Service
					 */
					HEADLINE_RESEARCH_SERVICE: () => LocalizedString
					/**
					 * Subject
					 */
					SUBJECT_PLACEHOLDER: () => LocalizedString
					/**
					 * Message
					 */
					MESSAGE_PLACEHOLDER: () => LocalizedString
					/**
					 * Category
					 */
					CATEGORY_LABEL: () => LocalizedString
					/**
					 * Select a Category
					 */
					CATEGORY_PLACEHOLDER: () => LocalizedString
					/**
					 * Cancel
					 */
					CANCEL_BUTTON: () => LocalizedString
					/**
					 * Send
					 */
					SEND_BUTTON: () => LocalizedString
					/**
					 * This request will be viewed and checked by the chair first and then forwarded to the Research Service.
					 */
					INFO_MESSAGE: () => LocalizedString
					categoryOptions: {
						/**
						 * Guest Speaker Request
						 */
						GUEST_SPEAKER: () => LocalizedString
						/**
						 * Fact Check Request
						 */
						FACT_CHECK: () => LocalizedString
						/**
						 * Information Request
						 */
						INFORMATION: () => LocalizedString
						/**
						 * General Secretary Visit Request
						 */
						GENERAL_SECRETARY: () => LocalizedString
						/**
						 * Other
						 */
						OTHER: () => LocalizedString
					}
				}
			}
			documentsWidget: {
				/**
				 * signed Sponsors
				 */
				SPONSORS: () => LocalizedString
			}
		}
		speakersList: {
			/**
			 * Speakers List
			 */
			SPEAKERS_LIST: () => LocalizedString
			/**
			 * Comment List
			 */
			COMMENT_LIST: () => LocalizedString
			/**
			 * Speech
			 */
			ADD_TO_LIST_BUTTON: () => LocalizedString
			/**
			 * Remove
			 */
			REMOVE_FROM_LIST_BUTTON: () => LocalizedString
			/**
			 * List Closed
			 */
			LIST_CLOSED_BUTTON: () => LocalizedString
			/**
			 * List Closed
			 */
			LIST_CLOSED_MESSAGE: () => LocalizedString
			/**
			 * No Speakers on the List
			 */
			NO_SPEAKERS_MESSAGE: () => LocalizedString
		}
		voting: {
			/**
			 * Motions on the Floor
			 */
			ACTIVE_MOTIONS_TAB: () => LocalizedString
			/**
			 * Recent Motions
			 */
			RECENT_MOTIONS_TAB: () => LocalizedString
			/**
			 * Recent Votings
			 */
			RECENT_VOTINGS_TAB: () => LocalizedString
			/**
			 * No open motions
			 */
			NO_DATA_MOTIONS: () => LocalizedString
			/**
			 * Voting
			 */
			VOTING_HEADLINE: () => LocalizedString
			/**
			 * No voting selected
			 */
			NO_DATA_VOTING: () => LocalizedString
			votingInfo: {
				/**
				 * Introduced by
				 */
				INTRODUCED_BY: () => LocalizedString
				votingMode: {
					/**
					 * Substantial Voting – Possibility to Abstain
					 */
					SUBSTANTIAL_VOTING: () => LocalizedString
					/**
					 * Procedural Voting – No Abstention
					 */
					PROCEDURAL_VOTING: () => LocalizedString
				}
				majorityMode: {
					/**
					 * Simple Majority needed (50% + 1)
					 */
					SIMPLE: () => LocalizedString
					/**
					 * Two-Thirds Majority needed (2/3)
					 */
					TWO_THIRDS: () => LocalizedString
					/**
					 * Three-Quarters Majority needed (3/4)
					 */
					THREE_QUARTERS: () => LocalizedString
					/**
					 * Consensus needed
					 */
					CONSENSUS: () => LocalizedString
					/**
					 * Security Council (9/15 + no veto)
					 */
					SECURITY_COUNCIL: () => LocalizedString
				}
			}
			votingButtons: {
				/**
				 * In Favour
				 */
				IN_FAVOUR: () => LocalizedString
				/**
				 * Against
				 */
				AGAINST: () => LocalizedString
				/**
				 * Abstention
				 */
				ABSTENTION: () => LocalizedString
				/**
				 * Remaining
				 */
				REMAINING: () => LocalizedString
				/**
				 * Vote Registered
				 */
				VOTE_REGISTERED: () => LocalizedString
				/**
				 * Waiting for results...
				 */
				VOTE_REGISTERED_MESSAGE: () => LocalizedString
			}
			votingResults: {
				/**
				 * Voting Successful
				 */
				VOTING_SUCCESSFUL: () => LocalizedString
				/**
				 * Voting Failed
				 */
				VOTING_FAILED: () => LocalizedString
			}
			votingAlert: {
				/**
				 * New Vote Started
				 */
				VOTING_ALERT_HEADER: () => LocalizedString
				/**
				 * A new vote has been started. Please vote now.
				 */
				VOTING_ALERT_MESSAGE: () => LocalizedString
				/**
				 * To Voting
				 */
				BUTTON_ADVANCE: () => LocalizedString
				/**
				 * Ignore
				 */
				BUTTON_IGNORE: () => LocalizedString
			}
		}
	}
	chairs: {
		/**
		 * Chair
		 */
		CHAIR: () => LocalizedString
		attendance: {
			/**
			 * Attendance
			 */
			HEADLINE: () => LocalizedString
			/**
			 * Present
			 */
			PRESENT: () => LocalizedString
			/**
			 * Absent
			 */
			ABSENT: () => LocalizedString
			/**
			 * Excused
			 */
			EXCUSED: () => LocalizedString
		}
		whiteboard: {
			/**
			 * Save and publish
			 */
			SAVE_BUTTON: () => LocalizedString
			/**
			 * Reset
			 */
			RESET_BUTTON: () => LocalizedString
		}
		speakersList: {
			buttons: {
				/**
				 * Start Timer
				 */
				START_TIMER: () => LocalizedString
				/**
				 * Stop Timer
				 */
				PAUSE_TIMER: () => LocalizedString
				/**
				 * Reset Timer
				 */
				RESET_TIMER: () => LocalizedString
				/**
				 * 15s
				 */
				REMOVE_TIME: () => LocalizedString
				/**
				 * 15s
				 */
				ADD_TIME: () => LocalizedString
				/**
				 * Next Speaker
				 */
				NEXT_SPEAKER: () => LocalizedString
				/**
				 * Add to List
				 */
				ADD_TO_LIST: () => LocalizedString
				/**
				 * Close List
				 */
				CLOSE_LIST: () => LocalizedString
				/**
				 * Open List
				 */
				OPEN_LIST: () => LocalizedString
				/**
				 * Reset List
				 */
				CLEAR_LIST: () => LocalizedString
				/**
				 * Change Speech Time
				 */
				CHANGE_SPEECH_TIME: () => LocalizedString
			}
			addSpeakerOverlay: {
				/**
				 * Add Speaker to {{0}}
				 */
				HEADLINE: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Select a Speaker
				 */
				PLACEHOLDER: () => LocalizedString
				/**
				 * Cancel
				 */
				BUTTON_CANCEL: () => LocalizedString
				/**
				 * Add
				 */
				BUTTON_ADD: () => LocalizedString
				/**
				 * Add and Close
				 */
				BUTTON_ADD_AND_CLOSE: () => LocalizedString
				/**
				 * {{0}} added
				 */
				TOAST_ADDED_SUMMARY: (arg0: number | string | boolean) => LocalizedString
				/**
				 * to the {{0}}
				 */
				TOAST_ADDED_DETAIL: (arg0: number | string | boolean) => LocalizedString
			}
			changeSpeechTimeOverlay: {
				/**
				 * Change Speech Time for {{0}}
				 */
				HEADLINE: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Cancel
				 */
				BUTTON_CANCEL: () => LocalizedString
				/**
				 * Change
				 */
				BUTTON_SET: () => LocalizedString
				/**
				 * New Speech Time (mm:ss)
				 */
				PLACEHOLDER: () => LocalizedString
				/**
				 * Speech Time changed to {{0}} min
				 */
				TOAST_SUCCESS: (arg0: number | string | boolean) => LocalizedString
				/**
				 * for {{0}}
				 */
				TOAST_SUCCESS_DETAIL: (arg0: number | string | boolean) => LocalizedString
				/**
				 * Wrong Format
				 */
				TOAST_WRONG_FORMAT: () => LocalizedString
			}
		}
		voting: {
			/**
			 * New Motion
			 */
			BUTTON_NEW_MOTION: () => LocalizedString
			/**
			 * Change Info
			 */
			BUTTON_CHANGE_INFO: () => LocalizedString
			/**
			 * Restart Voting
			 */
			BUTTON_RESET: () => LocalizedString
			/**
			 * Delete Voting
			 */
			BUTTON_DELETE: () => LocalizedString
		}
	}
}

export type Formatters = {}
