// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	login: {
		/**
		 * S​i​g​n​ ​i​n​ ​a​s​ ​c​h​a​i​r​ ​i​n​s​t​e​a​d
		 */
		otherSignIn: string
	}
}

export type TranslationFunctions = {
	login: {
		/**
		 * Sign in as chair instead
		 */
		otherSignIn: () => LocalizedString
	}
}

export type Formatters = {}
