// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING_PAGE: string
	login: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		USERNAME_PLACEHOLDER: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		PASSWORD_PLACEHOLDER: string
		/**
		 * A​d​v​a​n​c​e
		 */
		ADVANCE_BUTTON: string
		/**
		 * B​a​c​k
		 */
		BACK_BUTTON: string
		/**
		 * L​o​g​i​n
		 */
		LOGIN_BUTTON: string
		legalNotice: {
			/**
			 * I​ ​a​g​r​e​e​ ​w​i​t​h​ ​t​h​e​ 
			 */
			SECTION_1: string
			/**
			 * T​e​r​m​s​ ​o​f​ ​U​s​e
			 */
			TERMS_LINK: string
			/**
			 * .​ ​I​ ​a​l​s​o​ ​a​g​r​e​e​ ​t​h​a​t​ ​t​h​i​s​ ​w​e​b​s​i​t​e​ ​u​s​e​s​ ​c​o​o​k​i​e​s​.​ ​Y​o​u​ ​c​a​n​ ​f​i​n​d​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​t​h​i​s​ ​i​n​ ​o​u​r​ 
			 */
			SECTION_2: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			PRIVACY_LINK: string
			/**
			 * .
			 */
			SECTION_3: string
		}
		participant: {
			/**
			 * S​i​g​n​ ​i​n​ ​a​s​ ​c​h​a​i​r​ ​i​n​s​t​e​a​d
			 */
			OTHER_SIGH_IN: string
			/**
			 * C​o​m​m​i​t​t​e​e
			 */
			COMMITTEE_LABEL: string
			/**
			 * C​o​u​n​t​r​y​ ​/​ ​N​S​A
			 */
			COUNTRY_LABLE: string
			committeeSelection: {
				/**
				 * S​e​l​e​c​t​ ​t​h​e​ ​c​o​m​m​i​t​t​e​e
				 */
				HEADLINE: string
			}
		}
		chair: {
			/**
			 * S​i​g​n​ ​i​n​ ​a​s​ ​p​a​r​t​i​c​i​p​a​n​t​ ​i​n​s​t​e​a​d
			 */
			OTHER_SIGN_IN: string
			/**
			 * Y​o​u​ ​a​r​e​ ​a​b​o​u​t​ ​t​o​ ​s​i​g​n​ ​i​n​ ​a​s​ ​a​ ​c​h​a​i​r​.
			 */
			WARNING_MESSAGE: string
		}
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * S​p​e​a​k​e​r​s​ ​L​i​s​t
				 */
				SPEAKERS_LIST: string
				/**
				 * C​o​m​m​e​n​t​ ​L​i​s​t
				 */
				COMMENT_LIST: string
				/**
				 * C​o​m​m​i​t​t​e​e​ ​S​t​a​t​u​s
				 */
				COMMITTEE_STATUS: string
				/**
				 * W​h​i​t​e​b​o​a​r​d
				 */
				WHITEBOARD: string
				/**
				 * D​o​c​u​m​e​n​t​s
				 */
				DOCUMENTS: string
				/**
				 * S​e​n​d​ ​R​e​q​u​e​s​t
				 */
				ACTIONS: string
			}
			timerWidget: {
				/**
				 * u​n​t​i​l
				 */
				UNTIL_1: string
				UNTIL_2: string
				/**
				 * T​i​m​e​ ​i​s​ ​u​p​!
				 */
				TOAST_HEADLINE: string
				/**
				 * G​o​i​n​g​ ​b​a​c​k​ ​t​o​ ​f​o​r​m​a​l​ ​d​e​b​a​t​e​.
				 */
				TOAST_MESSAGE: string
			}
			actionsWidget: {
				/**
				 * C​h​a​i​r
				 */
				CHAIR_BUTTON: string
				/**
				 * R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e
				 */
				RESEARCH_SERVICE_BUTTON: string
				contactForm: {
					/**
					 * S​e​n​d​ ​a​ ​M​e​s​s​a​g​e​ ​t​o​ ​t​h​e​ ​C​h​a​i​r
					 */
					HEADLINE_CHAIR: string
					/**
					 * S​e​n​d​ ​a​ ​M​e​s​s​a​g​e​ ​t​o​ ​t​h​e​ ​R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e
					 */
					HEADLINE_RESEARCH_SERVICE: string
					/**
					 * S​u​b​j​e​c​t
					 */
					SUBJECT_PLACEHOLDER: string
					/**
					 * M​e​s​s​a​g​e
					 */
					MESSAGE_PLACEHOLDER: string
					/**
					 * C​a​t​e​g​o​r​y
					 */
					CATEGORY_LABEL: string
					/**
					 * S​e​l​e​c​t​ ​a​ ​C​a​t​e​g​o​r​y
					 */
					CATEGORY_PLACEHOLDER: string
					/**
					 * C​a​n​c​e​l
					 */
					CANCEL_BUTTON: string
					/**
					 * S​e​n​d
					 */
					SEND_BUTTON: string
					/**
					 * T​h​i​s​ ​r​e​q​u​e​s​t​ ​w​i​l​l​ ​b​e​ ​v​i​e​w​e​d​ ​a​n​d​ ​c​h​e​c​k​e​d​ ​b​y​ ​t​h​e​ ​c​h​a​i​r​ ​f​i​r​s​t​ ​a​n​d​ ​t​h​e​n​ ​f​o​r​w​a​r​d​e​d​ ​t​o​ ​t​h​e​ ​R​e​s​e​a​r​c​h​ ​S​e​r​v​i​c​e​.
					 */
					INFO_MESSAGE: string
					categoryOptions: {
						/**
						 * G​u​e​s​t​ ​S​p​e​a​k​e​r​ ​R​e​q​u​e​s​t
						 */
						GUEST_SPEAKER: string
						/**
						 * F​a​c​t​ ​C​h​e​c​k​ ​R​e​q​u​e​s​t
						 */
						FACT_CHECK: string
						/**
						 * I​n​f​o​r​m​a​t​i​o​n​ ​R​e​q​u​e​s​t
						 */
						INFORMATION: string
						/**
						 * G​e​n​e​r​a​l​ ​S​e​c​r​e​t​a​r​y​ ​V​i​s​i​t​ ​R​e​q​u​e​s​t
						 */
						GENERAL_SECRETARY: string
						/**
						 * O​t​h​e​r
						 */
						OTHER: string
					}
				}
			}
			documentsWidget: {
				/**
				 * s​i​g​n​e​d​ ​S​p​o​n​s​o​r​s
				 */
				SPONSORS: string
			}
		}
		speakersList: {
			/**
			 * S​p​e​a​k​e​r​s​ ​L​i​s​t
			 */
			SPEAKERS_LIST: string
			/**
			 * C​o​m​m​e​n​t​ ​L​i​s​t
			 */
			COMMENT_LIST: string
			/**
			 * S​p​e​e​c​h
			 */
			ADD_TO_LIST_BUTTON: string
			/**
			 * R​e​m​o​v​e
			 */
			REMOVE_FROM_LIST_BUTTON: string
			/**
			 * L​i​s​t​ ​C​l​o​s​e​d
			 */
			LIST_CLOSED_BUTTON: string
			/**
			 * L​i​s​t​ ​C​l​o​s​e​d
			 */
			LIST_CLOSED_MESSAGE: string
			/**
			 * N​o​ ​S​p​e​a​k​e​r​s​ ​o​n​ ​t​h​e​ ​L​i​s​t
			 */
			NO_SPEAKERS_MESSAGE: string
		}
		voting: {
			/**
			 * M​o​t​i​o​n​s
			 */
			MOTIONS_HEADLINE: string
			/**
			 * N​o​ ​o​p​e​n​ ​m​o​t​i​o​n​s
			 */
			NO_DATA_MOTIONS: string
			/**
			 * V​o​t​i​n​g
			 */
			VOTING_HEADLINE: string
			/**
			 * N​o​ ​o​p​e​n​ ​v​o​t​i​n​g​s
			 */
			NO_DATA_VOTING: string
			votingInfo: {
				/**
				 * I​n​t​r​o​d​u​c​e​d​ ​b​y
				 */
				INTRODUCED_BY: string
				votingMode: {
					/**
					 * S​u​b​s​t​a​n​t​i​a​l​ ​V​o​t​i​n​g​ ​–​ ​P​o​s​s​i​b​i​l​i​t​y​ ​t​o​ ​A​b​s​t​a​i​n
					 */
					SUBSTANTIAL_VOTING: string
					/**
					 * P​r​o​c​e​d​u​r​a​l​ ​V​o​t​i​n​g​ ​–​ ​N​o​ ​A​b​s​t​e​n​t​i​o​n
					 */
					PROCEDURAL_VOTING: string
				}
				majorityMode: {
					/**
					 * S​i​m​p​l​e​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​5​0​%​ ​+​ ​1​)
					 */
					SIMPLE: string
					/**
					 * T​w​o​-​T​h​i​r​d​s​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​2​/​3​)
					 */
					TWO_THIRDS: string
					/**
					 * T​h​r​e​e​-​Q​u​a​r​t​e​r​s​ ​M​a​j​o​r​i​t​y​ ​n​e​e​d​e​d​ ​(​3​/​4​)
					 */
					THREE_QUARTERS: string
					/**
					 * C​o​n​s​e​n​s​u​s​ ​n​e​e​d​e​d
					 */
					CONSENSUS: string
					/**
					 * S​e​c​u​r​i​t​y​ ​C​o​u​n​c​i​l​ ​(​9​/​1​5​ ​+​ ​n​o​ ​v​e​t​o​)
					 */
					SECURITY_COUNCIL: string
				}
			}
			votingButtons: {
				/**
				 * I​n​ ​F​a​v​o​u​r
				 */
				IN_FAVOUR: string
				/**
				 * A​g​a​i​n​s​t
				 */
				AGAINST: string
				/**
				 * A​b​s​t​e​n​t​i​o​n
				 */
				ABSTENTION: string
				/**
				 * R​e​m​a​i​n​i​n​g
				 */
				REMAINING: string
				/**
				 * V​o​t​e​ ​R​e​g​i​s​t​e​r​e​d
				 */
				VOTE_REGISTERED: string
				/**
				 * W​a​i​t​i​n​g​ ​f​o​r​ ​r​e​s​u​l​t​s​.​.​.
				 */
				VOTE_REGISTERED_MESSAGE: string
			}
			votingResults: {
				/**
				 * V​o​t​i​n​g​ ​S​u​c​c​e​s​s​f​u​l
				 */
				VOTING_SUCCESSFUL: string
				/**
				 * V​o​t​i​n​g​ ​F​a​i​l​e​d
				 */
				VOTING_FAILED: string
			}
			votingAlert: {
				/**
				 * N​e​w​ ​V​o​t​e​ ​S​t​a​r​t​e​d
				 */
				VOTING_ALERT_HEADER: string
				/**
				 * A​ ​n​e​w​ ​v​o​t​e​ ​h​a​s​ ​b​e​e​n​ ​s​t​a​r​t​e​d​.​ ​P​l​e​a​s​e​ ​v​o​t​e​ ​n​o​w​.
				 */
				VOTING_ALERT_MESSAGE: string
				/**
				 * T​o​ ​V​o​t​i​n​g
				 */
				BUTTON_ADVANCE: string
				/**
				 * I​g​n​o​r​e
				 */
				BUTTON_IGNORE: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Loading...
	 */
	LOADING_PAGE: () => LocalizedString
	login: {
		/**
		 * Username
		 */
		USERNAME_PLACEHOLDER: () => LocalizedString
		/**
		 * Password
		 */
		PASSWORD_PLACEHOLDER: () => LocalizedString
		/**
		 * Advance
		 */
		ADVANCE_BUTTON: () => LocalizedString
		/**
		 * Back
		 */
		BACK_BUTTON: () => LocalizedString
		/**
		 * Login
		 */
		LOGIN_BUTTON: () => LocalizedString
		legalNotice: {
			/**
			 * I agree with the 
			 */
			SECTION_1: () => LocalizedString
			/**
			 * Terms of Use
			 */
			TERMS_LINK: () => LocalizedString
			/**
			 * . I also agree that this website uses cookies. You can find more information about this in our 
			 */
			SECTION_2: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			PRIVACY_LINK: () => LocalizedString
			/**
			 * .
			 */
			SECTION_3: () => LocalizedString
		}
		participant: {
			/**
			 * Sign in as chair instead
			 */
			OTHER_SIGH_IN: () => LocalizedString
			/**
			 * Committee
			 */
			COMMITTEE_LABEL: () => LocalizedString
			/**
			 * Country / NSA
			 */
			COUNTRY_LABLE: () => LocalizedString
			committeeSelection: {
				/**
				 * Select the committee
				 */
				HEADLINE: () => LocalizedString
			}
		}
		chair: {
			/**
			 * Sign in as participant instead
			 */
			OTHER_SIGN_IN: () => LocalizedString
			/**
			 * You are about to sign in as a chair.
			 */
			WARNING_MESSAGE: () => LocalizedString
		}
	}
	participants: {
		dashboard: {
			widgetHeadlines: {
				/**
				 * Speakers List
				 */
				SPEAKERS_LIST: () => LocalizedString
				/**
				 * Comment List
				 */
				COMMENT_LIST: () => LocalizedString
				/**
				 * Committee Status
				 */
				COMMITTEE_STATUS: () => LocalizedString
				/**
				 * Whiteboard
				 */
				WHITEBOARD: () => LocalizedString
				/**
				 * Documents
				 */
				DOCUMENTS: () => LocalizedString
				/**
				 * Send Request
				 */
				ACTIONS: () => LocalizedString
			}
			timerWidget: {
				/**
				 * until
				 */
				UNTIL_1: () => LocalizedString
				UNTIL_2: () => LocalizedString
				/**
				 * Time is up!
				 */
				TOAST_HEADLINE: () => LocalizedString
				/**
				 * Going back to formal debate.
				 */
				TOAST_MESSAGE: () => LocalizedString
			}
			actionsWidget: {
				/**
				 * Chair
				 */
				CHAIR_BUTTON: () => LocalizedString
				/**
				 * Research Service
				 */
				RESEARCH_SERVICE_BUTTON: () => LocalizedString
				contactForm: {
					/**
					 * Send a Message to the Chair
					 */
					HEADLINE_CHAIR: () => LocalizedString
					/**
					 * Send a Message to the Research Service
					 */
					HEADLINE_RESEARCH_SERVICE: () => LocalizedString
					/**
					 * Subject
					 */
					SUBJECT_PLACEHOLDER: () => LocalizedString
					/**
					 * Message
					 */
					MESSAGE_PLACEHOLDER: () => LocalizedString
					/**
					 * Category
					 */
					CATEGORY_LABEL: () => LocalizedString
					/**
					 * Select a Category
					 */
					CATEGORY_PLACEHOLDER: () => LocalizedString
					/**
					 * Cancel
					 */
					CANCEL_BUTTON: () => LocalizedString
					/**
					 * Send
					 */
					SEND_BUTTON: () => LocalizedString
					/**
					 * This request will be viewed and checked by the chair first and then forwarded to the Research Service.
					 */
					INFO_MESSAGE: () => LocalizedString
					categoryOptions: {
						/**
						 * Guest Speaker Request
						 */
						GUEST_SPEAKER: () => LocalizedString
						/**
						 * Fact Check Request
						 */
						FACT_CHECK: () => LocalizedString
						/**
						 * Information Request
						 */
						INFORMATION: () => LocalizedString
						/**
						 * General Secretary Visit Request
						 */
						GENERAL_SECRETARY: () => LocalizedString
						/**
						 * Other
						 */
						OTHER: () => LocalizedString
					}
				}
			}
			documentsWidget: {
				/**
				 * signed Sponsors
				 */
				SPONSORS: () => LocalizedString
			}
		}
		speakersList: {
			/**
			 * Speakers List
			 */
			SPEAKERS_LIST: () => LocalizedString
			/**
			 * Comment List
			 */
			COMMENT_LIST: () => LocalizedString
			/**
			 * Speech
			 */
			ADD_TO_LIST_BUTTON: () => LocalizedString
			/**
			 * Remove
			 */
			REMOVE_FROM_LIST_BUTTON: () => LocalizedString
			/**
			 * List Closed
			 */
			LIST_CLOSED_BUTTON: () => LocalizedString
			/**
			 * List Closed
			 */
			LIST_CLOSED_MESSAGE: () => LocalizedString
			/**
			 * No Speakers on the List
			 */
			NO_SPEAKERS_MESSAGE: () => LocalizedString
		}
		voting: {
			/**
			 * Motions
			 */
			MOTIONS_HEADLINE: () => LocalizedString
			/**
			 * No open motions
			 */
			NO_DATA_MOTIONS: () => LocalizedString
			/**
			 * Voting
			 */
			VOTING_HEADLINE: () => LocalizedString
			/**
			 * No open votings
			 */
			NO_DATA_VOTING: () => LocalizedString
			votingInfo: {
				/**
				 * Introduced by
				 */
				INTRODUCED_BY: () => LocalizedString
				votingMode: {
					/**
					 * Substantial Voting – Possibility to Abstain
					 */
					SUBSTANTIAL_VOTING: () => LocalizedString
					/**
					 * Procedural Voting – No Abstention
					 */
					PROCEDURAL_VOTING: () => LocalizedString
				}
				majorityMode: {
					/**
					 * Simple Majority needed (50% + 1)
					 */
					SIMPLE: () => LocalizedString
					/**
					 * Two-Thirds Majority needed (2/3)
					 */
					TWO_THIRDS: () => LocalizedString
					/**
					 * Three-Quarters Majority needed (3/4)
					 */
					THREE_QUARTERS: () => LocalizedString
					/**
					 * Consensus needed
					 */
					CONSENSUS: () => LocalizedString
					/**
					 * Security Council (9/15 + no veto)
					 */
					SECURITY_COUNCIL: () => LocalizedString
				}
			}
			votingButtons: {
				/**
				 * In Favour
				 */
				IN_FAVOUR: () => LocalizedString
				/**
				 * Against
				 */
				AGAINST: () => LocalizedString
				/**
				 * Abstention
				 */
				ABSTENTION: () => LocalizedString
				/**
				 * Remaining
				 */
				REMAINING: () => LocalizedString
				/**
				 * Vote Registered
				 */
				VOTE_REGISTERED: () => LocalizedString
				/**
				 * Waiting for results...
				 */
				VOTE_REGISTERED_MESSAGE: () => LocalizedString
			}
			votingResults: {
				/**
				 * Voting Successful
				 */
				VOTING_SUCCESSFUL: () => LocalizedString
				/**
				 * Voting Failed
				 */
				VOTING_FAILED: () => LocalizedString
			}
			votingAlert: {
				/**
				 * New Vote Started
				 */
				VOTING_ALERT_HEADER: () => LocalizedString
				/**
				 * A new vote has been started. Please vote now.
				 */
				VOTING_ALERT_MESSAGE: () => LocalizedString
				/**
				 * To Voting
				 */
				BUTTON_ADVANCE: () => LocalizedString
				/**
				 * Ignore
				 */
				BUTTON_IGNORE: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
