<script lang="ts">
	interface Props {
		size?: 'xs' | 'sm';
	}
	let { size = 'xs' }: Props = $props();
</script>

<!-- Static robot badge indicating this content was produced by AI -->
<i
	class="fas fa-robot opacity-60 {size === 'xs' ? 'text-[0.55rem]' : 'text-xs'}"
	aria-label="AI generated"
	title="Generated by AI"
></i>
